"""Build ``docs/PIKMIN2_ADMITTED_PLACEMENT.json`` from species constraints (#948).

The committed placement document is the single source of truth for where a
P2 species may be placed (CONTRIBUTING "Placement: don't hard-code where a
species may go"). This module regenerates it from data, never from history:

* **Slots**: every production campaign generator (``campaign_data.CAMPAIGN_SLOTS``,
  72 rows across the ground/dwarf/grub/frog/aquatic/flying cohorts), the P1
  ship-part holder slots (:mod:`randomizer.p2_held_parts`) and the P1 boss
  arenas (:mod:`randomizer.p2_boss_arenas`). A slot's terrain class comes from
  the P1 species class that spawns there in vanilla; ``evidence`` records
  which native probes have run at the slot and is informational only.
* **Profiles**: the lane-04 constraint profiles
  (:mod:`randomizer.p2_placement_catalog`): terrain, footprint, flight space,
  water depth, burrow ground, home anchor, helpers, corpse route and, for
  bosses, the encounter descriptor (footprint vs measured clearance,
  protected drops). Pool species carry the admission gates; everything else
  stays default-deny.
* **accepted_slot_uids**: computed for every gated profile as the set of
  slots the profile is constraint-compatible with. Evidence slot ids (where
  a run happened) never narrow the list.

Run ``py -3.12 -m randomizer.p2_admitted_placement`` to rewrite the document;
``tests/test_pikmin2_admitted_document.py`` fails when the committed file
drifts from this generator.
"""
from __future__ import annotations

import json
from pathlib import Path

from . import p2_placement as _placement
from . import p2_placement_catalog as _catalog
from .p2_boss_arenas import ARENA_MEASUREMENTS, apply_to_document as _apply_arenas
from .p2_held_parts import apply_to_document as _apply_held_parts

DOCUMENT_PATH = Path(__file__).resolve().parents[1] / "docs" / "PIKMIN2_ADMITTED_PLACEMENT.json"

# Admission gates recorded on every pool species' profile: the generated
# placement bridge contract (P2_PLACEMENT_SLOT xyz/terrain/route ->
# P2_GENERATED_PLACEMENT bound=1 -> identity READY). Identity behaviour is
# each family lane's six natural gates (roster admission, seed.P2_PLAYABLE_POOL).
ADMITTED_GATES = ("placement.xyz", "placement.terrain", "placement.route", "bridge.spawn")

# Ordinary slots the native P2_PLACEMENT_SLOT probe has visited (terrain and
# route sampled at the slot XYZ): the 33 ground campaign slots and the two
# Spring dwarf singletons, from the six-gate run rev8 (native eb510ff4,
# output/claude-orch/evidence/doc-reconcile/rev8-native.log) and proxy probe
# pk1 (native ba6832cef, output/claude-orch/evidence/packs-forest/native.log).
# Evidence only: an unprobed slot is a to-do, not a restriction (#951 R3).
PROBED_SLOT_UIDS = frozenset({
    5465461, 328297937, 407876267, 513430982, 568677317, 873045719, 983680291,
    1254096625, 1646783045, 1725053560, 1787125272, 1808550463, 1849273021,
    1858120135, 1866045954, 1877315663, 1911597745, 1945764764, 2049888785,
    2074106479, 2175753366, 2506165730, 2700289662, 3138990329, 3640055869,
    3731060235, 3850487044, 3886812794, 3921089765, 3960948767, 4063112254,
    4141612035, 4222852521, 4224027716, 4281359481,
})

NOTES = (
    "P2 admitted placement (#948): every production campaign generator, the P1 "
    "ship-part holder slots and the P1 boss arenas, with each pool species' "
    "accepted_slot_uids derived from its constraint profile (terrain, footprint, "
    "flight space, water, burrow ground, home, helpers, corpse route; encounter "
    "footprint vs measured arena clearance for bosses). Regenerated by "
    "randomizer/p2_admitted_placement.py; evidence lives in the evidence documents, "
    "not here. Slot evidence flags record native probe history and gate nothing."
)


def _pool_identities(pool_ids, roster=None):
    from experimental.pikmin2_enemy_roster import load_roster
    roster = roster if roster is not None else load_roster()
    by_source = {entry.source_id: entry.enum_name for entry in roster}
    return {by_source[source_id]: source_id for source_id in pool_ids if source_id in by_source}


def ordinary_slots():
    """Every campaign generator as a slot, with probe evidence where recorded."""
    slots = []
    for slot in _catalog.slots_from_campaign():
        slot = dict(slot)
        probed = slot["uid"] in PROBED_SLOT_UIDS
        slot["evidence"] = {"xyz": bool(slot["evidence"].get("xyz")), "terrain": probed, "route": probed}
        slots.append(_placement.normalize_slot(slot))
    return slots


def build_admitted_document(pool_ids=None, roster=None):
    """Return the validated admitted placement document."""
    if pool_ids is None:
        from .seed import PLAYABLE_P2_SPECIES
        pool_ids = PLAYABLE_P2_SPECIES
    identities = _pool_identities(pool_ids, roster)
    document = _catalog.build_waterwraith_document(slots=ordinary_slots())
    profiles = []
    for profile in document["profiles"]:
        profile = dict(profile)
        source_id = identities.get(profile["identity"])
        if source_id is not None:
            profile["accepted_gates"] = list(ADMITTED_GATES)
            profile["notes"] = (
                f"P2 source_id {source_id}; admitted pool species (seed.P2_PLAYABLE_POOL); "
                "accepted_slot_uids are every constraint-compatible slot (#948), not the "
                "slots an evidence run happened to use. | " + profile.get("notes", ""))
        profiles.append(profile)
    document["profiles"] = profiles
    document["notes"] = NOTES
    document = _apply_arenas(document, ARENA_MEASUREMENTS, pool_ids=pool_ids)
    document = _apply_held_parts(document)
    return _placement.validate_document(finalize_accepted_slots(document))


def finalize_accepted_slots(document):
    """(Re)compute ``accepted_slot_uids`` for every gated profile from constraints.

    A profile without admission gates keeps no list (it is denied anyway).
    """
    document = dict(document)
    slots = [_placement.normalize_slot(slot) for slot in document["slots"]]
    encounters = {enc["id"]: enc for enc in document.get("encounters", [])}
    profiles = []
    for profile in document["profiles"]:
        profile = dict(profile)
        profile.pop("accepted_slot_uids", None)
        normalized = _placement.normalize_profile(profile)
        if normalized["accepted_gates"]:
            accepted = [slot["uid"] for slot in slots
                        if _placement.evaluate(slot, normalized, encounters)["status"] == "legal"]
            profile["accepted_slot_uids"] = accepted
        profiles.append(profile)
    document["profiles"] = profiles
    return document


def write_document(path=DOCUMENT_PATH, document=None):
    document = document if document is not None else build_admitted_document()
    Path(path).write_text(json.dumps(document, indent=2) + "\n", encoding="utf-8")
    return document


def summary(document=None):
    """Per-identity accepted slot counts plus the ordinary target set size."""
    document = document if document is not None else build_admitted_document()
    ordinary = [s for s in document["slots"] if not s.get("boss_slot") and not s.get("protected")]
    return {
        "slots": len(document["slots"]),
        "ordinary_slots": len(ordinary),
        "accepted": {p["identity"]: len(p.get("accepted_slot_uids") or [])
                     for p in document["profiles"] if p.get("accepted_gates")},
    }


def main(argv=None):
    import argparse
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--document", type=Path, default=DOCUMENT_PATH)
    parser.add_argument("--summary", action="store_true")
    args = parser.parse_args(argv)
    document = write_document(args.document)
    if args.summary:
        print(json.dumps(summary(document), indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
