"""Canonical Pikmin 2 source-ID roster and eligibility ledger (lane 02, #438).

Source of truth
---------------
The numeric identities and per-enemy facts come from the projectPiki/pikmin2
decompilation (``include/Game/enemyInfo.h`` ``EnemyTypeID`` and
``src/plugProjectYamashitaU/enemyInfo.cpp`` ``gEnemyInfo``), inspected read-only.
The committed snapshot at ``docs/PIKMIN2_ENEMY_ROSTER.json`` is generated by
``scripts/generate_pikmin2_enemy_roster.py``; regenerate it, never hand-edit it.

Design contract (agreed input to lanes 03/04/05)
------------------------------------------------
* One record per concrete source ID, including aliases/helpers and non-spawnable
  bases, so consumers never have to special-case a species by name.
* Classification separates randomizable enemies from plants, hazards,
  projectiles, nests, manager bases and non-spawnable aliases.
* ``eligibility`` defaults to ``"denied"``. Only a reviewed overlay in
  ``docs/PIKMIN2_ENEMY_ROSTER_EVIDENCE.json`` may raise it, and only when the
  required six-gate evidence is present. Source facts do not imply gameplay PASS.
"""
from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass, field
from pathlib import Path

SCHEMA = "p2-enemy-roster-1"

REPO_ROOT = Path(__file__).resolve().parents[1]
ROSTER_PATH = REPO_ROOT / "docs" / "PIKMIN2_ENEMY_ROSTER.json"
EVIDENCE_PATH = REPO_ROOT / "docs" / "PIKMIN2_ENEMY_ROSTER_EVIDENCE.json"

# Schema documentation block copied into a freshly synthesized evidence overlay
# so write_admission never emits an overlay missing the field descriptions.
EVIDENCE_FIELDS = {
    "native_module": "engine/pc_port module implementing the identity, or null",
    "owner_lane": "family/shared lane that owns the identity",
    "gates": "map of the six gate IDs to PASS/FAIL/BLOCKED/UNTESTED/N/A; a PASS needs root/native/exe pins, inputs and observed result",
    "delivery_receipt": "citation of an actual transport/reward delivery for gate 5 (transport_reward), or null; required for admission",
    "eligibility": "denied | candidate | admitted | excluded",
    "eligibility_reason": "short justification",
    "source": "list of docs/PIKMIN2_*.md filenames the evidence is transcribed from",
    "notes": "free-form review notes (natural vs injected labels)",
}

# Six arena gates every admitted identity must eventually report.
GATE_IDS = (
    "identity_spawn",
    "movement_animation",
    "attacks_receivers",
    "death_corpse",
    "transport_reward",
    "cleanup_reentry",
)
# The five gates an identity must hold as a natural PASS to satisfy the
# admission contract; gate 5 (``transport_reward``) is satisfied instead by a
# cited ``delivery_receipt`` proving real transport/collection, not by a gate
# status.
ADMISSION_GATES = (
    "identity_spawn",
    "movement_animation",
    "attacks_receivers",
    "death_corpse",
    "cleanup_reentry",
)
GATE_STATUS = ("PASS", "FAIL", "BLOCKED", "UNTESTED", "N/A")

# A row whose notes/eligibility_reason carry any of these markers is treated as
# non-natural evidence: a PASS on an admission gate in such a row is refused as
# "<gate>:injected" rather than accepted as natural. This is the enforced version
# of the "only natural PASS admits" rule (it is not merely assumed by construction).
NONNATURAL_MARKERS = re.compile(
    r"inject|\bproxy\b|fixture-only|\bforced\b|\bvehicle\b|\bvisual\b|\bhost\b|\bdisplay\b",
    re.IGNORECASE,
)

# A delivery_receipt is a durable citation matching lane 06's per-identity scheme:
# either an ``onion:``/``corpse:``/``receipt:`` key, or a doc/log citation (a
# filename with a recognized extension or a path separator). A blank or arbitrary
# string is refused.
RECEIPT_KEY_PREFIXES = ("onion:", "corpse:", "receipt:")
RECEIPT_CITATION_MARKERS = (".md", ".log", ".txt", ".json", "/", "\\")

CLASSIFICATIONS = (
    "enemy",
    "boss",
    "boss_helper",
    "plant",
    "hazard",
    "projectile",
    "nest",
    "manager_base",
    "non_spawnable",
)
ELIGIBILITY = ("denied", "candidate", "admitted", "excluded")

# Identity roles separate how a source identity participates in a randomizer
# pool from its source classification. Consumers (03/04/05) select only
# ``source``/``variant`` identities; helpers and aliases are never seeded on
# their own. ``identity_role`` is derived from the roster facts, never stored.
ROLES = (
    "source",        # standalone randomizable enemy/boss with its own manager
    "variant",       # randomizable identity sharing a parent manager/base
    "helper",        # boss helper or dependent birth, not an independent spawn
    "plant",
    "hazard",
    "projectile",
    "nest",
    "manager_base",
    "non_spawnable",
)

# Source-backed classification sets, keyed by decomp enum name. Lane 02 decision,
# reviewable by lanes 03/04/05; the audit flags any identity left unclassified.
PLANTS = frozenset({
    "Pelplant", "BluePom", "RedPom", "YellowPom", "BlackPom", "WhitePom", "RandPom",
    "Tanpopo", "Clover", "HikariKinoko", "Ooinu_s", "Ooinu_l", "Wakame_s", "Wakame_l",
    "Tukushi", "Watage", "DaiodoRed", "DaiodoGreen", "Magaret", "Nekojarashi",
    "Chiyogami", "Zenmai", "KareOoinu_s", "KareOoinu_l",
})
HAZARDS = frozenset({"Hiba", "GasHiba", "ElecHiba"})
PROJECTILES = frozenset({"Rock", "Stone", "Bomb", "Egg"})
NESTS = frozenset({"PanHouse", "PanModokiNest", "JigumoNest"})
MANAGER_BASES = frozenset({"Pom", "UmiMushiBase"})
BOSS_HELPERS = frozenset({"Baby", "Tyre"})
# IS_ENEMY_BOSS in enemyInfo.h; audited against the source each generation.
BOSSES = frozenset({
    "Queen", "SnakeCrow", "KingChappy", "Damagumo", "OoPanModoki", "Houdai",
    "UmiMushiBlind", "BlackMan", "DangoMushi", "BigFoot", "SnakeWhole",
    "UmiMushi", "BigTreasure",
})

# Macros used in gEnemyInfo child counts.
CHILD_COUNT_MACROS = {
    "SHIJIMICHOU_GROUP_COUNT": 25,
    "TAMAGOMUSHI_GROUP_COUNT": 30,
}


class RosterError(ValueError):
    """Raised when the roster snapshot or evidence overlay is inconsistent."""


@dataclass(frozen=True)
class RosterEntry:
    source_id: int
    enum_name: str
    source_name: str | None
    common_name: str
    classification: str
    parent_id: int | None = None
    parent_name: str | None = None
    members: int = 1
    spawnable: bool = False
    use_own_id: bool = False
    has_no_info: bool = False
    day_end_max: int | None = None
    drop_type: str | None = None
    child_id: int | None = None
    child_name: str | None = None
    child_count: int = 0
    assets: dict[str, str] = field(default_factory=dict)
    in_info_table: bool = True
    native_module: str | None = None
    owner_lane: str | None = None
    gates: dict[str, str] = field(default_factory=dict)
    delivery_receipt: str | None = None
    eligibility: str = "denied"
    eligibility_reason: str = "no accepted evidence; defaults denied"
    source: tuple[str, ...] = ()
    notes: tuple[str, ...] = ()

    @property
    def is_randomizable_candidate(self) -> bool:
        return self.classification in ("enemy", "boss")

    def gate_report(self) -> str:
        if not self.gates:
            return "UNTESTED"
        return "/".join(self.gates.get(g, "UNTESTED") for g in GATE_IDS)


# ---------------------------------------------------------------------------
# Source parsing. Kept independent of the research checkout so tests can feed
# synthetic text; the generator supplies the real decompilation files.
# ---------------------------------------------------------------------------

def _split_top_level(text: str) -> list[str]:
    """Split ``text`` on commas outside quoted strings and parentheses."""
    fields: list[str] = []
    current: list[str] = []
    depth = 0
    in_string = False
    escaped = False
    for char in text:
        if in_string:
            current.append(char)
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == '"':
                in_string = False
            continue
        if char == '"':
            in_string = True
            current.append(char)
        elif char == "(":
            depth += 1
            current.append(char)
        elif char == ")":
            depth -= 1
            current.append(char)
        elif char == "," and depth == 0:
            fields.append("".join(current).strip())
            current = []
        else:
            current.append(char)
    tail = "".join(current).strip()
    if tail:
        fields.append(tail)
    return fields


def parse_enum_header(text: str) -> dict[str, dict]:
    import re
    pattern = re.compile(r"^\s*EnemyID_(\w+)\s*=\s*(-?\d+)\s*,\s*//\s*(.*?)\s*$")
    records: dict[str, dict] = {}
    for line in text.splitlines():
        match = pattern.match(line)
        if not match:
            continue
        enum_name, numeric, comment = match.groups()
        records[enum_name] = {
            "source_id": int(numeric),
            "common_name": comment.rstrip(",").strip(),
        }
    return records


def _enum_ref(field_text: str) -> str | None:
    field_text = field_text.strip()
    if field_text in ("-1", ""):
        return None
    if "EnemyID_" in field_text:
        return field_text.rsplit("EnemyID_", 1)[1].strip()
    raise RosterError(f"unexpected enum reference: {field_text!r}")


def _unquote(field_text: str) -> str:
    field_text = field_text.strip()
    if len(field_text) >= 2 and field_text[0] == '"' and field_text[-1] == '"':
        return field_text[1:-1]
    raise RosterError(f"expected string literal, got {field_text!r}")


def parse_info_table(text: str) -> dict[str, dict]:
    start = text.index("gEnemyInfo[]")
    start = text.index("{", start)
    end = text.index("};", start)
    body = text[start + 1:end]
    records: dict[str, dict] = {}
    for raw_line in body.splitlines():
        line = raw_line.strip()
        if not line.startswith("{") or "#" in line:
            continue
        line = line.rstrip(",")
        fields = _split_top_level(line[1:-1])
        if len(fields) < 15:
            continue
        name = _unquote(fields[0])
        enum_name = _enum_ref(fields[1])
        if enum_name is None:
            continue
        parent = _enum_ref(fields[2])
        members = int(fields[3])
        flags_text = fields[4]
        assets = {
            "model": _unquote(fields[5]),
            "anim": _unquote(fields[6]),
            "anim_mgr": _unquote(fields[7]),
            "texture": _unquote(fields[8]),
            "param": _unquote(fields[9]),
            "collision": _unquote(fields[10]),
            "stone": _unquote(fields[11]),
        }
        child = _enum_ref(fields[12])
        child_count = fields[13].strip()
        if child_count in CHILD_COUNT_MACROS:
            child_count = CHILD_COUNT_MACROS[child_count]
        drop_type = fields[14].strip()
        day_end_max = None
        for flag, value in (("EFlag_DayEndMax1", 1), ("EFlag_DayEndMax2", 2), ("EFlag_DayEndMax4", 4)):
            if flag in flags_text:
                day_end_max = value
        records[name] = {
            "enum_name": enum_name,
            "source_name": name,
            "parent_name": parent,
            "members": members,
            "spawnable": "EFlag_CanBeSpawned" in flags_text,
            "use_own_id": "EFlag_UseOwnID" in flags_text,
            "has_no_info": "EFlag_HasNoInfo" in flags_text,
            "day_end_max": day_end_max,
            "drop_type": drop_type,
            "child_name": child,
            "child_count": int(child_count),
            "assets": assets,
        }
    return records


# ---------------------------------------------------------------------------
# Classification and roster assembly.
# ---------------------------------------------------------------------------

def classify(enum_name: str, facts: dict) -> str:
    if enum_name in MANAGER_BASES:
        return "manager_base"
    if enum_name in BOSSES:
        return "boss"
    if enum_name in BOSS_HELPERS:
        return "boss_helper"
    if enum_name in NESTS:
        return "nest"
    if enum_name in PLANTS:
        return "plant"
    if enum_name in HAZARDS:
        return "hazard"
    if enum_name in PROJECTILES:
        return "projectile"
    if not facts.get("spawnable", False):
        return "non_spawnable"
    if str(facts.get("drop_type", "")) in ("BDT_Boss", "BDT_FinalBoss"):
        return "boss"
    return "enemy"


def identity_role(entry: RosterEntry) -> str:
    """How an identity participates in a pool: source, variant, helper or other.

    A randomizable identity that shares a parent manager/base (for example
    ``UmiMushi``/``UmiMushiBlind`` on ``UmiMushiBase``) is a *variant*; a
    standalone enemy or boss is a *source*. Helpers and dependent births are
    never seeded independently even if they carry an enemy-like classification.
    """
    if entry.classification == "boss_helper":
        return "helper"
    if entry.classification in ("plant", "hazard", "projectile", "nest",
                                "manager_base", "non_spawnable"):
        return entry.classification
    if not entry.spawnable:
        return "non_spawnable"
    if entry.parent_id is not None:
        return "variant"
    return "source"


def _nonnatural_evidence(entry: RosterEntry) -> bool:
    """True when the row's notes/reason carry injected/proxy/display markers."""
    text = " ".join([entry.eligibility_reason or ""] + list(entry.notes))
    return NONNATURAL_MARKERS.search(text) is not None


def _receipt_shaped(text: str) -> bool:
    value = text.strip()
    if not value:
        return False
    if value.startswith(RECEIPT_KEY_PREFIXES):
        return True
    return any(marker in value for marker in RECEIPT_CITATION_MARKERS)


def admission_requirements(entry: RosterEntry) -> list[str]:
    """Exact list of admission gaps for one identity, empty when it qualifies.

    The contract requires a *natural* PASS on each gate in :data:`ADMISSION_GATES`
    and a ``delivery_receipt`` matching lane 06's scheme for ``transport_reward``.
    A PASS is accepted only when the row's notes/reason carry no
    :data:`NONNATURAL_MARKERS`; otherwise the gate is reported as ``<gate>:injected``.
    A blank or malformed receipt is reported as ``transport_reward`` or
    ``transport_reward:invalid_receipt`` respectively.
    """
    nonnatural = _nonnatural_evidence(entry)
    missing: list[str] = []
    for gate in ADMISSION_GATES:
        if entry.gates.get(gate) != "PASS":
            missing.append(gate)
        elif nonnatural:
            missing.append(f"{gate}:injected")
    receipt = (entry.delivery_receipt or "").strip()
    if not receipt:
        missing.append("transport_reward")
    elif not _receipt_shaped(receipt):
        missing.append("transport_reward:invalid_receipt")
    return missing


def admission_contract(roster: list[RosterEntry]) -> dict:
    """Fail-closed admission set computed from gate evidence, never from a flag.

    Returns ``{"admitted": [source_id...], "blocking": {source_id: [missing...]}}``.
    Only a seedable role (``source``/``variant``) participates; an explicitly
    ``excluded`` identity is blocked with ``["excluded"]``; any other role is
    ignored. This is the authoritative admission gate: today's ledger has no
    identity with the five natural PASSes plus a delivery receipt, so it admits
    nothing until a family supplies the full generated-session chain.
    """
    admitted: list[int] = []
    blocking: dict[int, list[str]] = {}
    for entry in roster:
        role = identity_role(entry)
        if role not in ("source", "variant"):
            continue
        if entry.eligibility == "excluded":
            blocking[entry.source_id] = ["excluded"]
            continue
        missing = admission_requirements(entry)
        if missing:
            blocking[entry.source_id] = missing
        else:
            admitted.append(entry.source_id)
    return {"admitted": sorted(admitted), "blocking": blocking}


def write_admission(roster: list[RosterEntry], path=None) -> dict:
    """Persist the admission contract's admitted set into the evidence JSON.

    For each identity the written ``eligibility`` becomes ``"admitted"`` when the
    contract passes, ``"candidate"`` when it was previously ``"admitted"`` but the
    contract no longer passes, and is otherwise left unchanged. Returns the
    contract dict; it never admits an identity the contract refuses.
    """
    import json as _json
    contract = admission_contract(roster)
    admitted = set(contract["admitted"])
    # Keep the one-time user-authorized admitted-by-flag entries (directive 007)
    # marked admitted rather than letting the contract demote them to candidate.
    by_source = {entry.source_id: entry for entry in roster}
    for source_id in USER_AUTHORIZED_ADMITTED_BY_FLAG:
        if source_id in by_source:
            admitted.add(source_id)
    target = Path(path) if path is not None else EVIDENCE_PATH
    if target.is_file():
        # Merge: only update eligibility on rows that already exist, never add
        # a placeholder row for an identity that has no overlay entry.
        doc = _json.loads(target.read_text(encoding="utf-8"))
        entries = doc.setdefault("entries", {})
        for key in list(entries.keys()):
            try:
                source_id = int(key)
            except ValueError:
                continue
            entry = by_source.get(source_id)
            if entry is None:
                continue
            if source_id in admitted:
                entries[key]["eligibility"] = "admitted"
            elif entry.eligibility == "admitted":
                entries[key]["eligibility"] = "candidate"
                entries[key]["eligibility_reason"] = (
                    "admission contract no longer satisfied: "
                    + ", ".join(contract["blocking"].get(source_id, ["unknown"])))
    else:
        # Fresh path: synthesize a full overlay from the roster for each entry.
        doc = {"schema": f"{SCHEMA}-evidence",
               "note": "Eligibility overlay for the canonical P2 roster. Written by "
                       "write_admission; see docs/PIKMIN2_ENEMY_ROSTER.md.",
               "fields": EVIDENCE_FIELDS,
               "entries": {}}
        entries = doc["entries"]
        for entry in roster:
            if entry.source_id in admitted:
                new_elig, reason = "admitted", entry.eligibility_reason
            elif entry.eligibility == "admitted":
                new_elig, reason = "candidate", (
                    "admission contract no longer satisfied: "
                    + ", ".join(contract["blocking"].get(entry.source_id, ["unknown"])))
            else:
                new_elig, reason = entry.eligibility, entry.eligibility_reason
            entries[str(entry.source_id)] = {
                "native_module": entry.native_module,
                "owner_lane": entry.owner_lane,
                "eligibility": new_elig,
                "eligibility_reason": reason,
                "gates": entry.gates,
                "delivery_receipt": entry.delivery_receipt,
                "source": list(entry.source),
                "notes": list(entry.notes),
            }
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(_json.dumps(doc, indent=2) + "\n", encoding="utf-8")
    return contract


def build_entries(enum_records: dict[str, dict], table_records: dict[str, dict]) -> list[dict]:
    """Merge enum identity data with gEnemyInfo facts into roster records."""
    by_enum = {r["enum_name"]: r for r in table_records.values()}
    merged: list[dict] = []
    for enum_name, enum in enum_records.items():
        if enum_name == "NULL" or enum["source_id"] < 0:
            continue
        facts = by_enum.get(enum_name, {})
        parent_name = facts.get("parent_name")
        child_name = facts.get("child_name")
        entry = {
            "source_id": enum["source_id"],
            "enum_name": enum_name,
            "source_name": facts.get("source_name"),
            "common_name": enum["common_name"],
            "classification": classify(enum_name, facts),
            "parent_name": parent_name,
            "members": facts.get("members", 1),
            "spawnable": facts.get("spawnable", False),
            "use_own_id": facts.get("use_own_id", False),
            "has_no_info": facts.get("has_no_info", False),
            "day_end_max": facts.get("day_end_max"),
            "drop_type": facts.get("drop_type"),
            "child_name": child_name,
            "child_count": facts.get("child_count", 0),
            "assets": facts.get("assets", {}),
            "in_info_table": bool(facts),
        }
        merged.append(entry)
    merged.sort(key=lambda item: item["source_id"])
    return merged


def resolve_ids(entries: list[dict]) -> list[dict]:
    by_enum = {e["enum_name"]: e for e in entries}
    for entry in entries:
        parent = entry.get("parent_name")
        entry["parent_id"] = by_enum[parent]["source_id"] if parent in by_enum else None
        child = entry.get("child_name")
        entry["child_id"] = by_enum[child]["source_id"] if child in by_enum else None
    return entries


def snapshot_payload(entries: list[dict], source_revision: str | None = None) -> dict:
    cleaned = []
    for entry in entries:
        item = dict(entry)
        item.pop("classification", None)
        cleaned.append(item)
    return {
        "schema": SCHEMA,
        "source": "projectPiki/pikmin2 include/Game/enemyInfo.h + src/plugProjectYamashitaU/enemyInfo.cpp",
        "source_revision": source_revision,
        "note": "Generated by scripts/generate_pikmin2_enemy_roster.py; do not hand-edit.",
        "entry_count": len(cleaned),
        "entries": cleaned,
    }


def load_snapshot() -> list[dict]:
    payload = json.loads(ROSTER_PATH.read_text(encoding="utf-8"))
    if payload.get("schema") != SCHEMA:
        raise RosterError(f"unsupported roster schema: {payload.get('schema')!r}")
    return payload["entries"]


def _load_evidence() -> dict:
    if not EVIDENCE_PATH.is_file():
        return {}
    payload = json.loads(EVIDENCE_PATH.read_text(encoding="utf-8"))
    if payload.get("schema") != f"{SCHEMA}-evidence":
        raise RosterError(f"unsupported evidence schema: {payload.get('schema')!r}")
    return payload.get("entries", {})


def load_roster() -> list[RosterEntry]:
    payload = json.loads(ROSTER_PATH.read_text(encoding="utf-8"))
    if payload.get("schema") != SCHEMA:
        raise RosterError(f"unsupported roster schema: {payload.get('schema')!r}")
    return entries_from_payload(payload, _load_evidence())


def entries_from_payload(payload: dict, evidence: dict | None = None) -> list[RosterEntry]:
    if payload.get("schema") != SCHEMA:
        raise RosterError(f"unsupported roster schema: {payload.get('schema')!r}")
    evidence = evidence or {}
    entries = resolve_ids(payload["entries"])
    roster: list[RosterEntry] = []
    for entry in entries:
        overlay = evidence.get(str(entry["source_id"]), {})
        gates = {gate: overlay["gates"][gate] for gate in GATE_IDS if gate in overlay.get("gates", {})}
        roster.append(RosterEntry(
            source_id=entry["source_id"],
            enum_name=entry["enum_name"],
            source_name=entry.get("source_name"),
            common_name=entry["common_name"],
            classification=classify(entry["enum_name"], entry),
            parent_id=entry.get("parent_id"),
            parent_name=entry.get("parent_name"),
            members=entry.get("members", 1),
            spawnable=entry.get("spawnable", False),
            use_own_id=entry.get("use_own_id", False),
            has_no_info=entry.get("has_no_info", False),
            day_end_max=entry.get("day_end_max"),
            drop_type=entry.get("drop_type"),
            child_id=entry.get("child_id"),
            child_name=entry.get("child_name"),
            child_count=entry.get("child_count", 0),
            assets=entry.get("assets", {}),
            in_info_table=entry.get("in_info_table", True),
            native_module=overlay.get("native_module"),
            owner_lane=overlay.get("owner_lane"),
            gates=gates,
            delivery_receipt=overlay.get("delivery_receipt"),
            eligibility=overlay.get("eligibility", "denied"),
            eligibility_reason=overlay.get("eligibility_reason", "no accepted evidence; defaults denied"),
            source=tuple(overlay.get("source", [])),
            notes=tuple(overlay.get("notes", [])),
        ))
    return roster


def validate_roster(roster: list[RosterEntry]) -> None:
    ids = [entry.source_id for entry in roster]
    if len(ids) != len(set(ids)):
        raise RosterError("duplicate source IDs in roster")
    enums = [entry.enum_name for entry in roster]
    if len(enums) != len(set(enums)):
        raise RosterError("duplicate enum names in roster")
    by_id = {entry.source_id: entry for entry in roster}
    for entry in roster:
        if entry.classification not in CLASSIFICATIONS:
            raise RosterError(f"unknown classification {entry.classification!r} for {entry.enum_name}")
        if entry.parent_id is not None and entry.parent_id not in by_id:
            raise RosterError(f"{entry.enum_name} references missing parent {entry.parent_id}")
        if entry.child_id is not None and entry.child_id not in by_id:
            raise RosterError(f"{entry.enum_name} references missing child {entry.child_id}")
        for gate in entry.gates:
            if gate not in GATE_IDS:
                raise RosterError(f"{entry.enum_name} has unknown gate {gate!r}")
            if entry.gates[gate] not in GATE_STATUS:
                raise RosterError(f"{entry.enum_name} gate {gate} has bad status {entry.gates[gate]!r}")
        if entry.eligibility not in ELIGIBILITY:
            raise RosterError(f"{entry.enum_name} has unknown eligibility {entry.eligibility!r}")
        if entry.eligibility == "admitted":
            if identity_role(entry) not in ("source", "variant"):
                raise RosterError(f"{entry.enum_name} is admitted but its role {identity_role(entry)!r} is not seedable")
            if entry.source_id not in USER_AUTHORIZED_ADMITTED_BY_FLAG:
                missing = admission_requirements(entry)
                if missing:
                    raise RosterError(f"{entry.enum_name} admitted without the admission contract: {missing}")


def load_and_validate() -> list[RosterEntry]:
    roster = load_roster()
    validate_roster(roster)
    return roster


def by_id(roster: list[RosterEntry]) -> dict[int, RosterEntry]:
    return {entry.source_id: entry for entry in roster}


def resolve_alias(token: str, roster: list[RosterEntry]) -> tuple[str, RosterEntry | None]:
    """Resolve a content-inventory token to ``(kind, identity)``.

    ``kind`` is ``exact`` (an enum name), ``generator_variant`` (a ``$N``-prefixed
    generator token), ``treasure_carrier`` (an ``Enum_suffix`` carrier alias) or
    ``unknown``. This lets 03/05 distinguish real identities from the alias
    tokens the content inventory mixes into ``enemy_ids`` instead of inventing a
    source ID for an alias.
    """
    lowered = {entry.enum_name.lower(): entry for entry in roster}
    if token in {entry.enum_name for entry in roster}:
        return "exact", lowered[token.lower()]
    stripped = token.lstrip("$")
    while stripped and stripped[0].isdigit():
        stripped = stripped[1:]
    if stripped.lower() in lowered:
        return "generator_variant", lowered[stripped.lower()]
    entry = lowered.get(stripped.split("_", 1)[0].lower())
    if entry is None:
        return "unknown", None
    return "treasure_carrier", entry


def inventory_encounters(payload: dict, roster: list[RosterEntry]) -> dict[str, list[dict]]:
    """Map each identity's enum name to its source-backable cave-floor appearances.

    Reads ``docs/PIKMIN2_CONTENT_INVENTORY.json`` ``story_caves[].floors[].enemy_ids``
    tokens and resolves them through :func:`resolve_alias`, so treasure-carrier and
    ``$N`` generator aliases are attributed to their real identity instead of being
    invented as new source IDs. This is inventory evidence, not placement approval
    (lane 04 owns legal slots).
    """
    encounters: dict[str, list[dict]] = {}
    for cave in payload.get("story_caves", []):
        cave_id = cave.get("id")
        for floor in cave.get("floors", []):
            row = {"cave": cave_id, "first": floor.get("first"), "last": floor.get("last")}
            for token in floor.get("enemy_ids", []):
                _, entry = resolve_alias(token, roster)
                if entry is None:
                    continue
                rows = encounters.setdefault(entry.enum_name, [])
                if row not in rows:
                    rows.append(row)
    return encounters


def candidate_review(roster: list[RosterEntry], encounters: dict | None = None) -> list[dict]:
    """Per-candidate readiness rows: role, owner, native module and missing gates."""
    encounters = encounters or {}
    rows = []
    for entry in sorted(roster, key=lambda item: item.source_id):
        if not entry.is_randomizable_candidate:
            continue
        rows.append({
            "source_id": entry.source_id,
            "enum_name": entry.enum_name,
            "common_name": entry.common_name,
            "classification": entry.classification,
            "role": identity_role(entry),
            "owner_lane": entry.owner_lane,
            "native_module": entry.native_module,
            "gates": dict(entry.gates),
            "missing_gates": [g for g in GATE_IDS if entry.gates.get(g) not in ("PASS", "N/A")],
            "eligibility": entry.eligibility,
            "encounters": encounters.get(entry.enum_name, []),
        })
    return rows


@dataclass(frozen=True)
class AdmissionSet:
    """The explicit, deny-by-default seedable identity set for this roster."""

    admitted: tuple[int, ...]
    candidates: tuple[int, ...]
    excluded: tuple[int, ...]
    denied: tuple[int, ...]
    by_role: dict[str, int]

    def __contains__(self, source_id: object) -> bool:
        return source_id in self.admitted

    def is_admitted(self, source_id: int) -> bool:
        return source_id in self.admitted


def admission_set(roster: list[RosterEntry]) -> AdmissionSet:
    """Build the seedable admission set from the admission contract.

    The ``admitted`` tuple is derived from :func:`admission_contract` — a
    seedable identity earns it only with a natural PASS on each :data:`ADMISSION_GATES`
    gate plus a cited delivery receipt for ``transport_reward``. ``candidates``,
    ``excluded`` and ``denied`` categorize the remainder by their overlay
    eligibility. Source facts, taxonomy membership or a native module presence
    never imply admission.
    """
    contract = admission_contract(roster)
    admitted = list(contract["admitted"])
    # One-time user-authorized admitted-by-flag identities (directive 007): Snow 45
    # is admitted on the Codex line without a receipt and must not fail closed here.
    present = {entry.source_id for entry in roster}
    for source_id in USER_AUTHORIZED_ADMITTED_BY_FLAG:
        if source_id in present and source_id not in admitted:
            admitted.append(source_id)
    admitted.sort()
    admitted_set = set(admitted)
    candidates: list[int] = []
    excluded: list[int] = []
    denied: list[int] = []
    for entry in sorted(roster, key=lambda item: item.source_id):
        if entry.eligibility == "admitted" and entry.source_id not in admitted_set:
            # Fail closed: an overlay flag of ``admitted`` must be backed by a
            # satisfied contract (write_admission keeps them in sync).
            raise RosterError(
                f"{entry.enum_name} is admitted but its contract is not satisfied: "
                f"{contract['blocking'].get(entry.source_id, 'unknown')}")
        if entry.source_id in admitted_set:
            continue
        if entry.eligibility == "candidate":
            candidates.append(entry.source_id)
        elif entry.eligibility == "excluded":
            excluded.append(entry.source_id)
        else:
            denied.append(entry.source_id)
    by_role: dict[str, int] = {}
    for entry in roster:
        role = identity_role(entry)
        by_role[role] = by_role.get(role, 0) + 1
    return AdmissionSet(tuple(admitted), tuple(candidates), tuple(excluded), tuple(denied), by_role)


# One-time USER-AUTHORIZED admitted-by-flag identities (directive 007, 2026-09-15).
# Snow (YellowKochappy, 45) was admitted on the Codex line by an eligibility flag
# with no delivery_receipt; the user explicitly authorized unioning it into this
# reconciled line. The wave deny-by-default guarantee is unchanged for every other
# identity: six natural gates plus a receipt-shaped delivery_receipt.
USER_AUTHORIZED_ADMITTED_BY_FLAG: tuple[int, ...] = (45,)


def admitted_ids(roster: list[RosterEntry]) -> list[int]:
    """Ordered source IDs a consumer may seed; empty while nothing is admitted.

    Derived from :func:`admission_contract` (five natural PASSes plus a
    receipt-shaped delivery_receipt), plus the one-time user-authorized
    admitted-by-flag identities. A candidate-scope override is honoured only when
    the process is explicitly marked by the private diagnostic CLI, so a stray
    PIKMIN_P2_ADMITTED_IDS value can never broaden the product (default-deny) set.
    """
    ids = list(admission_contract(roster)["admitted"])
    present = {entry.source_id for entry in roster}
    for source_id in USER_AUTHORIZED_ADMITTED_BY_FLAG:
        if source_id in present and source_id not in ids:
            ids.append(source_id)
    ids.sort()
    if os.environ.get("PIKMIN_P2_CANDIDATE_SCOPE") and os.environ.get("PIKMIN_P2_ADMITTED_IDS"):
        for part in os.environ["PIKMIN_P2_ADMITTED_IDS"].split(","):
            part = part.strip()
            if not part:
                continue
            source_id = int(part)
            if source_id not in ids:
                ids.append(source_id)
        ids.sort()
    return ids


def require_admitted(roster: list[RosterEntry], source_id: int) -> RosterEntry:
    entry = by_id(roster).get(source_id)
    if entry is None:
        raise RosterError(f"unknown P2 source id {source_id}")
    role = identity_role(entry)
    if entry.source_id in USER_AUTHORIZED_ADMITTED_BY_FLAG and role in ("source", "variant"):
        return entry
    missing = admission_requirements(entry) if role in ("source", "variant") else ["role"]
    if role not in ("source", "variant") or entry.eligibility == "excluded" or missing:
        why = ["excluded"] if entry.eligibility == "excluded" else (missing or ["not seedable"])
        raise RosterError(f"{entry.enum_name} ({source_id}) is not an admitted seedable identity: {', '.join(why)}")
    return entry


def require_opt_in(roster: list[RosterEntry], source_id: int) -> RosterEntry:
    """Fail-closed check for a *private* opt-in candidate validation run.

    Unlike :func:`require_admitted`, this does not require the identity to be in
    the global admission set (which stays empty until lane 01 accepts a generated
    session). It only accepts identities that are explicitly reviewed
    (``candidate`` or ``admitted``) and have a seedable role
    (``source``/``variant``). A denied, excluded, unknown, helper, plant,
    hazard, projectile, nest or manager-base identity is rejected, so the
    validation path can never opt a previously un-reviewed identity into a run.
    """
    entry = by_id(roster).get(source_id)
    if entry is None:
        raise RosterError(f"unknown P2 source id {source_id}")
    if entry.eligibility not in ("candidate", "admitted"):
        raise RosterError(
            f"{entry.enum_name} ({source_id}) has no reviewed eligibility "
            f"({entry.eligibility}); refusing opt-in validation"
        )
    role = identity_role(entry)
    if role not in ("source", "variant"):
        raise RosterError(f"{entry.enum_name} ({source_id}) is a {role}, not an opt-in seedable identity")
    return entry


def opt_in_validation_cohort(roster: list[RosterEntry], source_ids) -> list[int]:
    """Ordered allowlist for a *private* opt-in candidate validation run.

    This is the fail-closed candidate-validation path required by the next-wave
    guide: a caller (e.g. the Snow/Dwarf Orange cohort) may exercise the full
    generated-session chain against explicitly reviewed candidates without those
    identities being admitted by the global :func:`admission_set`. The global
    pool stays deny-by-default, so :func:`admitted_ids` remains empty and normal
    seed generation is unaffected. Returns the validated ordered source IDs; it
    never mutates the roster or the admission set.
    """
    ids = list(source_ids)
    if not ids:
        raise RosterError("opt-in validation cohort is empty")
    if any(type(source_id) is not int for source_id in ids):
        raise RosterError("opt-in validation source ids must be integers")
    if len(ids) != len(set(ids)):
        raise RosterError("opt-in validation cohort contains duplicate source ids")
    for source_id in ids:
        require_opt_in(roster, source_id)
    return [int(source_id) for source_id in ids]


def summarize(roster: list[RosterEntry]) -> dict:
    counts: dict[str, int] = {}
    for entry in roster:
        counts[entry.classification] = counts.get(entry.classification, 0) + 1
    eligible = [e.enum_name for e in roster if e.eligibility in ("candidate", "admitted")]
    admission = admission_set(roster)
    return {
        "entry_count": len(roster),
        "classification_counts": dict(sorted(counts.items())),
        "role_counts": dict(sorted(admission.by_role.items())),
        "randomizable_candidates": sum(e.is_randomizable_candidate for e in roster),
        "eligible_identities": eligible,
        "admitted_ids": list(admission.admitted),
        "admitted_count": len(admission.admitted),
        "in_info_table": sum(1 for e in roster if getattr(e, "in_info_table", True)),
    }
