"""Canonical Pikmin 2 source-ID roster and eligibility ledger (lane 02, #438).

Source of truth
---------------
The numeric identities and per-enemy facts come from the projectPiki/pikmin2
decompilation (``include/Game/enemyInfo.h`` ``EnemyTypeID`` and
``src/plugProjectYamashitaU/enemyInfo.cpp`` ``gEnemyInfo``), inspected read-only.
The committed snapshot at ``docs/PIKMIN2_ENEMY_ROSTER.json`` is generated by
``scripts/generate_pikmin2_enemy_roster.py``; regenerate it, never hand-edit it.

Design contract (agreed input to lanes 03/04/05)
------------------------------------------------
* One record per concrete source ID, including aliases/helpers and non-spawnable
  bases, so consumers never have to special-case a species by name.
* Classification separates randomizable enemies from plants, hazards,
  projectiles, nests, manager bases and non-spawnable aliases.
* ``eligibility`` defaults to ``"denied"``. Only a reviewed overlay in
  ``docs/PIKMIN2_ENEMY_ROSTER_EVIDENCE.json`` may raise it, and only when the
  required six-gate evidence is present. Source facts do not imply gameplay PASS.
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

SCHEMA = "p2-enemy-roster-1"

REPO_ROOT = Path(__file__).resolve().parents[1]
ROSTER_PATH = REPO_ROOT / "docs" / "PIKMIN2_ENEMY_ROSTER.json"
EVIDENCE_PATH = REPO_ROOT / "docs" / "PIKMIN2_ENEMY_ROSTER_EVIDENCE.json"

# Six arena gates every admitted identity must eventually report.
GATE_IDS = (
    "identity_spawn",
    "movement_animation",
    "attacks_receivers",
    "death_corpse",
    "transport_reward",
    "cleanup_reentry",
)
GATE_STATUS = ("PASS", "FAIL", "BLOCKED", "UNTESTED", "N/A")

CLASSIFICATIONS = (
    "enemy",
    "boss",
    "boss_helper",
    "plant",
    "hazard",
    "projectile",
    "nest",
    "manager_base",
    "non_spawnable",
)
ELIGIBILITY = ("denied", "candidate", "admitted", "excluded")

# Source-backed classification sets, keyed by decomp enum name. Lane 02 decision,
# reviewable by lanes 03/04/05; the audit flags any identity left unclassified.
PLANTS = frozenset({
    "Pelplant", "BluePom", "RedPom", "YellowPom", "BlackPom", "WhitePom", "RandPom",
    "Tanpopo", "Clover", "HikariKinoko", "Ooinu_s", "Ooinu_l", "Wakame_s", "Wakame_l",
    "Tukushi", "Watage", "DaiodoRed", "DaiodoGreen", "Magaret", "Nekojarashi",
    "Chiyogami", "Zenmai", "KareOoinu_s", "KareOoinu_l",
})
HAZARDS = frozenset({"Hiba", "GasHiba", "ElecHiba"})
PROJECTILES = frozenset({"Rock", "Stone", "Bomb", "Egg"})
NESTS = frozenset({"PanHouse", "PanModokiNest", "JigumoNest"})
MANAGER_BASES = frozenset({"Pom", "UmiMushiBase"})
BOSS_HELPERS = frozenset({"Baby", "Tyre"})
# IS_ENEMY_BOSS in enemyInfo.h; audited against the source each generation.
BOSSES = frozenset({
    "Queen", "SnakeCrow", "KingChappy", "Damagumo", "OoPanModoki", "Houdai",
    "UmiMushiBlind", "BlackMan", "DangoMushi", "BigFoot", "SnakeWhole",
    "UmiMushi", "BigTreasure",
})

# Macros used in gEnemyInfo child counts.
CHILD_COUNT_MACROS = {
    "SHIJIMICHOU_GROUP_COUNT": 25,
    "TAMAGOMUSHI_GROUP_COUNT": 30,
}


class RosterError(ValueError):
    """Raised when the roster snapshot or evidence overlay is inconsistent."""


@dataclass(frozen=True)
class RosterEntry:
    source_id: int
    enum_name: str
    source_name: str | None
    common_name: str
    classification: str
    parent_id: int | None = None
    parent_name: str | None = None
    members: int = 1
    spawnable: bool = False
    use_own_id: bool = False
    has_no_info: bool = False
    day_end_max: int | None = None
    drop_type: str | None = None
    child_id: int | None = None
    child_name: str | None = None
    child_count: int = 0
    assets: dict[str, str] = field(default_factory=dict)
    in_info_table: bool = True
    native_module: str | None = None
    owner_lane: str | None = None
    gates: dict[str, str] = field(default_factory=dict)
    eligibility: str = "denied"
    eligibility_reason: str = "no accepted evidence; defaults denied"
    notes: tuple[str, ...] = ()

    @property
    def is_randomizable_candidate(self) -> bool:
        return self.classification in ("enemy", "boss")

    def gate_report(self) -> str:
        if not self.gates:
            return "UNTESTED"
        return "/".join(self.gates.get(g, "UNTESTED") for g in GATE_IDS)


# ---------------------------------------------------------------------------
# Source parsing. Kept independent of the research checkout so tests can feed
# synthetic text; the generator supplies the real decompilation files.
# ---------------------------------------------------------------------------

def _split_top_level(text: str) -> list[str]:
    """Split ``text`` on commas outside quoted strings and parentheses."""
    fields: list[str] = []
    current: list[str] = []
    depth = 0
    in_string = False
    escaped = False
    for char in text:
        if in_string:
            current.append(char)
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == '"':
                in_string = False
            continue
        if char == '"':
            in_string = True
            current.append(char)
        elif char == "(":
            depth += 1
            current.append(char)
        elif char == ")":
            depth -= 1
            current.append(char)
        elif char == "," and depth == 0:
            fields.append("".join(current).strip())
            current = []
        else:
            current.append(char)
    tail = "".join(current).strip()
    if tail:
        fields.append(tail)
    return fields


def parse_enum_header(text: str) -> dict[str, dict]:
    import re
    pattern = re.compile(r"^\s*EnemyID_(\w+)\s*=\s*(-?\d+)\s*,\s*//\s*(.*?)\s*$")
    records: dict[str, dict] = {}
    for line in text.splitlines():
        match = pattern.match(line)
        if not match:
            continue
        enum_name, numeric, comment = match.groups()
        records[enum_name] = {
            "source_id": int(numeric),
            "common_name": comment.rstrip(",").strip(),
        }
    return records


def _enum_ref(field_text: str) -> str | None:
    field_text = field_text.strip()
    if field_text in ("-1", ""):
        return None
    if "EnemyID_" in field_text:
        return field_text.rsplit("EnemyID_", 1)[1].strip()
    raise RosterError(f"unexpected enum reference: {field_text!r}")


def _unquote(field_text: str) -> str:
    field_text = field_text.strip()
    if len(field_text) >= 2 and field_text[0] == '"' and field_text[-1] == '"':
        return field_text[1:-1]
    raise RosterError(f"expected string literal, got {field_text!r}")


def parse_info_table(text: str) -> dict[str, dict]:
    start = text.index("gEnemyInfo[]")
    start = text.index("{", start)
    end = text.index("};", start)
    body = text[start + 1:end]
    records: dict[str, dict] = {}
    for raw_line in body.splitlines():
        line = raw_line.strip()
        if not line.startswith("{") or "#" in line:
            continue
        line = line.rstrip(",")
        fields = _split_top_level(line[1:-1])
        if len(fields) < 15:
            continue
        name = _unquote(fields[0])
        enum_name = _enum_ref(fields[1])
        if enum_name is None:
            continue
        parent = _enum_ref(fields[2])
        members = int(fields[3])
        flags_text = fields[4]
        assets = {
            "model": _unquote(fields[5]),
            "anim": _unquote(fields[6]),
            "anim_mgr": _unquote(fields[7]),
            "texture": _unquote(fields[8]),
            "param": _unquote(fields[9]),
            "collision": _unquote(fields[10]),
            "stone": _unquote(fields[11]),
        }
        child = _enum_ref(fields[12])
        child_count = fields[13].strip()
        if child_count in CHILD_COUNT_MACROS:
            child_count = CHILD_COUNT_MACROS[child_count]
        drop_type = fields[14].strip()
        day_end_max = None
        for flag, value in (("EFlag_DayEndMax1", 1), ("EFlag_DayEndMax2", 2), ("EFlag_DayEndMax4", 4)):
            if flag in flags_text:
                day_end_max = value
        records[name] = {
            "enum_name": enum_name,
            "source_name": name,
            "parent_name": parent,
            "members": members,
            "spawnable": "EFlag_CanBeSpawned" in flags_text,
            "use_own_id": "EFlag_UseOwnID" in flags_text,
            "has_no_info": "EFlag_HasNoInfo" in flags_text,
            "day_end_max": day_end_max,
            "drop_type": drop_type,
            "child_name": child,
            "child_count": int(child_count),
            "assets": assets,
        }
    return records


# ---------------------------------------------------------------------------
# Classification and roster assembly.
# ---------------------------------------------------------------------------

def classify(enum_name: str, facts: dict) -> str:
    if enum_name in MANAGER_BASES:
        return "manager_base"
    if enum_name in BOSSES:
        return "boss"
    if enum_name in BOSS_HELPERS:
        return "boss_helper"
    if enum_name in NESTS:
        return "nest"
    if enum_name in PLANTS:
        return "plant"
    if enum_name in HAZARDS:
        return "hazard"
    if enum_name in PROJECTILES:
        return "projectile"
    if not facts.get("spawnable", False):
        return "non_spawnable"
    if str(facts.get("drop_type", "")) in ("BDT_Boss", "BDT_FinalBoss"):
        return "boss"
    return "enemy"


def build_entries(enum_records: dict[str, dict], table_records: dict[str, dict]) -> list[dict]:
    """Merge enum identity data with gEnemyInfo facts into roster records."""
    by_enum = {r["enum_name"]: r for r in table_records.values()}
    merged: list[dict] = []
    for enum_name, enum in enum_records.items():
        if enum_name == "NULL" or enum["source_id"] < 0:
            continue
        facts = by_enum.get(enum_name, {})
        parent_name = facts.get("parent_name")
        child_name = facts.get("child_name")
        entry = {
            "source_id": enum["source_id"],
            "enum_name": enum_name,
            "source_name": facts.get("source_name"),
            "common_name": enum["common_name"],
            "classification": classify(enum_name, facts),
            "parent_name": parent_name,
            "members": facts.get("members", 1),
            "spawnable": facts.get("spawnable", False),
            "use_own_id": facts.get("use_own_id", False),
            "has_no_info": facts.get("has_no_info", False),
            "day_end_max": facts.get("day_end_max"),
            "drop_type": facts.get("drop_type"),
            "child_name": child_name,
            "child_count": facts.get("child_count", 0),
            "assets": facts.get("assets", {}),
            "in_info_table": bool(facts),
        }
        merged.append(entry)
    merged.sort(key=lambda item: item["source_id"])
    return merged


def resolve_ids(entries: list[dict]) -> list[dict]:
    by_enum = {e["enum_name"]: e for e in entries}
    for entry in entries:
        parent = entry.get("parent_name")
        entry["parent_id"] = by_enum[parent]["source_id"] if parent in by_enum else None
        child = entry.get("child_name")
        entry["child_id"] = by_enum[child]["source_id"] if child in by_enum else None
    return entries


def snapshot_payload(entries: list[dict], source_revision: str | None = None) -> dict:
    cleaned = []
    for entry in entries:
        item = dict(entry)
        item.pop("classification", None)
        cleaned.append(item)
    return {
        "schema": SCHEMA,
        "source": "projectPiki/pikmin2 include/Game/enemyInfo.h + src/plugProjectYamashitaU/enemyInfo.cpp",
        "source_revision": source_revision,
        "note": "Generated by scripts/generate_pikmin2_enemy_roster.py; do not hand-edit.",
        "entry_count": len(cleaned),
        "entries": cleaned,
    }


def load_snapshot() -> list[dict]:
    payload = json.loads(ROSTER_PATH.read_text(encoding="utf-8"))
    if payload.get("schema") != SCHEMA:
        raise RosterError(f"unsupported roster schema: {payload.get('schema')!r}")
    return payload["entries"]


def _load_evidence() -> dict:
    if not EVIDENCE_PATH.is_file():
        return {}
    payload = json.loads(EVIDENCE_PATH.read_text(encoding="utf-8"))
    if payload.get("schema") != f"{SCHEMA}-evidence":
        raise RosterError(f"unsupported evidence schema: {payload.get('schema')!r}")
    return payload.get("entries", {})


def load_roster() -> list[RosterEntry]:
    payload = json.loads(ROSTER_PATH.read_text(encoding="utf-8"))
    if payload.get("schema") != SCHEMA:
        raise RosterError(f"unsupported roster schema: {payload.get('schema')!r}")
    return entries_from_payload(payload, _load_evidence())


def entries_from_payload(payload: dict, evidence: dict | None = None) -> list[RosterEntry]:
    if payload.get("schema") != SCHEMA:
        raise RosterError(f"unsupported roster schema: {payload.get('schema')!r}")
    evidence = evidence or {}
    entries = resolve_ids(payload["entries"])
    roster: list[RosterEntry] = []
    for entry in entries:
        overlay = evidence.get(str(entry["source_id"]), {})
        gates = {gate: overlay["gates"][gate] for gate in GATE_IDS if gate in overlay.get("gates", {})}
        roster.append(RosterEntry(
            source_id=entry["source_id"],
            enum_name=entry["enum_name"],
            source_name=entry.get("source_name"),
            common_name=entry["common_name"],
            classification=classify(entry["enum_name"], entry),
            parent_id=entry.get("parent_id"),
            parent_name=entry.get("parent_name"),
            members=entry.get("members", 1),
            spawnable=entry.get("spawnable", False),
            use_own_id=entry.get("use_own_id", False),
            has_no_info=entry.get("has_no_info", False),
            day_end_max=entry.get("day_end_max"),
            drop_type=entry.get("drop_type"),
            child_id=entry.get("child_id"),
            child_name=entry.get("child_name"),
            child_count=entry.get("child_count", 0),
            assets=entry.get("assets", {}),
            in_info_table=entry.get("in_info_table", True),
            native_module=overlay.get("native_module"),
            owner_lane=overlay.get("owner_lane"),
            gates=gates,
            eligibility=overlay.get("eligibility", "denied"),
            eligibility_reason=overlay.get("eligibility_reason", "no accepted evidence; defaults denied"),
            notes=tuple(overlay.get("notes", [])),
        ))
    return roster


def validate_roster(roster: list[RosterEntry]) -> None:
    ids = [entry.source_id for entry in roster]
    if len(ids) != len(set(ids)):
        raise RosterError("duplicate source IDs in roster")
    enums = [entry.enum_name for entry in roster]
    if len(enums) != len(set(enums)):
        raise RosterError("duplicate enum names in roster")
    by_id = {entry.source_id: entry for entry in roster}
    for entry in roster:
        if entry.classification not in CLASSIFICATIONS:
            raise RosterError(f"unknown classification {entry.classification!r} for {entry.enum_name}")
        if entry.parent_id is not None and entry.parent_id not in by_id:
            raise RosterError(f"{entry.enum_name} references missing parent {entry.parent_id}")
        if entry.child_id is not None and entry.child_id not in by_id:
            raise RosterError(f"{entry.enum_name} references missing child {entry.child_id}")
        for gate in entry.gates:
            if gate not in GATE_IDS:
                raise RosterError(f"{entry.enum_name} has unknown gate {gate!r}")
            if entry.gates[gate] not in GATE_STATUS:
                raise RosterError(f"{entry.enum_name} gate {gate} has bad status {entry.gates[gate]!r}")
        if entry.eligibility not in ELIGIBILITY:
            raise RosterError(f"{entry.enum_name} has unknown eligibility {entry.eligibility!r}")
        if entry.eligibility == "admitted":
            missing = [g for g in GATE_IDS if entry.gates.get(g) not in ("PASS", "N/A")]
            if missing:
                raise RosterError(f"{entry.enum_name} admitted without complete gates: {missing}")


def load_and_validate() -> list[RosterEntry]:
    roster = load_roster()
    validate_roster(roster)
    return roster


def by_id(roster: list[RosterEntry]) -> dict[int, RosterEntry]:
    return {entry.source_id: entry for entry in roster}


def summarize(roster: list[RosterEntry]) -> dict:
    counts: dict[str, int] = {}
    for entry in roster:
        counts[entry.classification] = counts.get(entry.classification, 0) + 1
    eligible = [e.enum_name for e in roster if e.eligibility in ("candidate", "admitted")]
    return {
        "entry_count": len(roster),
        "classification_counts": dict(sorted(counts.items())),
        "randomizable_candidates": sum(e.is_randomizable_candidate for e in roster),
        "eligible_identities": eligible,
        "in_info_table": sum(1 for e in roster if getattr(e, "in_info_table", True)),
    }
