// Family-owned ground-invertebrate source behavior for the batch-2 Chappy
// placement vehicle: Cloaking Burrow-nit (Armor, EnemyID 15). Implements the
// source ArmorState.cpp combat FSM: Stay (buried) -> Appear -> Move/GoHome ->
// Attack2 -> Eat/Fail -> Dead, plus Flick. Bridge states (Attack1, MoveSide/
// Centre/Top) are source-backed N/A because the arena has no ItemBridge.
// Source revision 632af93787b9c95b63f0c13be32b161375ce3a96; retail parms from
// experimental/pikmin2_ground_inverts_assets.py (GPVE01 rev 0).
//
// Source truth for the collision and the bite (#1014; decomp citations in pc_p2_armor_policy.h):
//   * Collision tree: the retail armor/enemycoll.txt tree is bound as the actor's own CollInfo (buildColl):
//     root r40 on kosijnt (`____`), `dmg1` r17.5 on headjnt (`st__`) and the shell r22.5 on kourajnt (`_t__`).
//     Only `dmg1` is stickable (CollPart::isStickable, collinfo.cpp:806) and only `dmg1` passes
//     Armor::damageCallBack (Armor.cpp:117-128), so a Pikmin can latch and hurt the head only; the shell
//     (kourajnt) and the body are invincible. The parts are posed every tick from per-frame tables
//     generated by scripts/p2_armor_tables.py (pc_p2_armor_tables.h). The retail ids of root and shell are
//     both `none`; the port names them root/shll so each can be found (nothing keys on them).
//   * Mouth slot: Obj::attackPikmin (Armor.cpp:232-261) runs once per source frame 17 < f < 27 of attack2
//     (ArmorState.cpp:586-589) and stabs every Pikmin whose 3D distance to the kamujnt joint is below 25
//     (there is no facing test). The joint is taken from the tables at that frame: it rears up and then
//     lunges ~150 units ahead of the body. A stabbed Pikmin is stuck to the actor's own 'slot'/'kam1' part,
//     which follows kamujnt, so it rides the drawn jaw through the eat clip; the eat source event (frame 60)
//     runs killSlotPiki = swallowPikmin(fp01 = 300) on Pikmin still held. Attack2 END goes to Eat only while
//     a Pikmin is held (getSlotPikiNum). Death and teardown release the mouth; the port's own flick sweep
//     spares held Pikmin. Eat/flick timing comes from the authoritative sampled clock (#431).
//   * Attack start: isTargetAttackable / getNearestPikminOrNavi with the retail fp20 75 range and fp21 15
//     degree angle (ArmorState.cpp:231, :470); the turn toward the target follows the source law (10% of the
//     angle error per source frame, capped at 10 degrees: fp08 / fp28). attack2 frame 22 runs attackNavi
//     (fp22 75, fp23 15, fp24 10 damage).
//   * Damage paths: a latched Pikmin attack carries the stuck part, so only `dmg1` takes it; a partless
//     Pikmin punch is refused; a captain punch is accepted only when the hand reaches the head sphere
//     (NaviPunchState::hitCallback delivers the part the hand touched); a bomb takes the base
//     EnemyBase::bombCallBack (addDamage on any part, the Armor does not override it). The source
//     hipdropCallBack (purple) follows the same `dmg1` rule; the port has no part-carrying hipdrop.
//
// Port adaptations (recorded, not retail-faithful):
//   * The tree is swapped onto the P1 Chappy host (like the Bloyster and the Emperor); the host tree comes
//     back at death (carcass/centre seated on the body) and at stage teardown. PIKMIN_P2_ARMOR_OWN_COLL=0
//     keeps the host tree for A/B evidence (the receiver then falls back to the legacy weakpoint rule).
//   * `EB_Bittered` has no P1 host equivalent; pc_p2_armor_set_bittered is the
//     explicit host/fixture input for the bittered leg of the same rule.
//   * `doStartStoneState` flick is implemented, but the P1 host has no
//     petrification lifecycle. pc_p2_armor_update fires it on the rising edge
//     of TEKIOPT_Pressed (the host's flattened/incapacitated analogue) and the
//     port records `P2_ARMOR_STONE_NOTE host_lifecycle=absent port_analogue=pressed`.
//   * View angle is a full hemisphere (fp13 absent from the Armor general block);
//     the flick radius is a documented port adaptation.
// No other lane's module is modified; every hook is a no-op for unregistered actors.
#include "pc_p2_armor.h"
#include "pc_p2_armor_events.h"
#include "pc_p2_armor_receiver_policy.h"
#include "pc_p2_armor_policy.h"
#include "pc_p2_skewer.h"
#include "pc_p2_skewer_cam.h"
#include "CreatureCollPart.h"
#include "PikiState.h"
#include "gl/pc_gfx.h"
#include "pc_p2_captor_host.h"
#include "pc_p2_campaign_actor.h"
#include "pc_randomizer.h"
#include "pc_bbft.h"
#include "teki.h"
#include "Interactions.h"
#include "Collision.h"
#include "ID32.h"
#include "Piki.h"
#include "PikiMgr.h"
#include "Navi.h"
#include "NaviMgr.h"
#include "pc_p2_navi_select.h"
#include "Generator.h"
#include "gameflow.h"
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <map>
#include <set>
#include <string>
#include <vector>

extern Matrix4f invCamMat;  // collInfo.cpp: camera inverse used by CollPart::getMatrix

namespace {
enum State {
    ARMOR_INVALID = -1,
    ARMOR_DEAD = 0,
    ARMOR_STAY = 1,
    ARMOR_APPEAR = 2,
    ARMOR_DIVE = 3,
    ARMOR_MOVE = 4,
    ARMOR_GOHOME = 8,
    ARMOR_ATTACK2 = 10,
    ARMOR_EAT = 11,
    ARMOR_FLICK = 12,
    ARMOR_FAIL = 13,
};

const char* stateName(State s) {
    switch (s) {
    case ARMOR_DEAD: return "dead";
    case ARMOR_STAY: return "stay";
    case ARMOR_APPEAR: return "appear";
    case ARMOR_DIVE: return "dive";
    case ARMOR_MOVE: return "move";
    case ARMOR_GOHOME: return "gohome";
    case ARMOR_ATTACK2: return "attack2";
    case ARMOR_EAT: return "eat";
    case ARMOR_FLICK: return "flick";
    case ARMOR_FAIL: return "fail";
    default: return "null";
    }
}

// Source enemyparm.txt values (ground_inverts manifest general).
constexpr float LIFE = 300.0f;
constexpr float MOVE_SPEED = 50.0f;
constexpr float SIGHT = 200.0f;
constexpr float TERRITORY = 400.0f;
constexpr float HOME_RADIUS = 30.0f;
// Source turn law (EnemyBase::turnToTarget, retail fp08 0.1 / fp28 10 deg per source frame): the angle
// error closes by 10% per frame, capped at 10 degrees, scaled to the port tick.
constexpr float TURN_SPEED = 0.1f;
constexpr float TURN_MAX = 10.0f * 3.14159265f / 180.0f;
constexpr float FLICK_RADIUS = 25.0f;     // port adaptation
constexpr float SHAKE_RANGE = 100.0f;
constexpr float SHAKE_KNOCKBACK = 120.0f;

struct Clip {
    std::string name;
    float duration = 1.0f;
    bool loop = false;
    std::vector<std::pair<int, int>> events;
    p2sampled::Clip sampled;
};

struct Armor {
    State state = ARMOR_STAY;
    float stateTime = 0.0f;
    float heading = 0.0f;
    Vector3f home;
    p2captor::Held<Piki> held; // Pikmin in the kamujnt slot (validated against the host stick)
    bool mouthLogged = false;
    p2armorevents::Receiver events;
    std::string clip = "appear";
    float phase = 0.0f;
    bool biteLogged = false;
    bool deadLogged = false;bool escaped=false;
    float logTimer = 0.0f;
    // Per-frame health tracker for natural-combat observability: an incremental,
    // still-positive decrease is real receiver damage (see pc_p2_armor_update).
    float lastHealth = LIFE;
    // Damage-receiver / stone-flick port state (see pc_p2_armor.h).
    bool bittered = false;
    bool stone = false;
    bool dmg1Present = false;
    bool weakpointActive = false;
    unsigned weakpointId = 0;
    unsigned token = 0;
    float scale = 1.0f;
    struct Coll {
        CollInfo* own = nullptr;
        CollInfo* host = nullptr;
        CollPart* node[p2armortables::kNodeCount] = {};
        CollPart* slot = nullptr;
        CollPart* kam = nullptr;
        bool released = false;
    } coll;
    int latchLogged = -1;
    int recvLogged = 0;
    bool holdShot = false, biteShot = false, headShot = false;
    int holdLogs = 0;
    int holdLoggedFrame = -100;
    // TEST-ONLY probe (PIKMIN_P2_ARMOR_PROBE), never active in a normal run.
    float probeTime = 0.0f;
    bool probeCaptain = false, probeFreezeInit = false, probeDone = false, probeSawAttack = false;
    float idleT = 0.0f;
    int idleStage = 0;
    int probeCycle = 0, probePinN = 0;
    float probeCycleAt = 0.0f;
    Piki* probePin[4] = {};
    Vector3f probePinPos[4];
    const char* probePinName[4] = {};
    float probePinLx[4] = {}, probePinLz[4] = {};
    int probeRecvStage = 0;
    float probeRecvHealth = 0.0f;
    float probeNoPikiLog = 0.0f;
    int probeThrows = 0;
    float probeNextThrow = 0.0f;
    Piki* probeThrown[8] = {};
    float probeThrownAt[8] = {};
    bool probeLanded[8] = {};
    Piki* probeUsed[24] = {};
    int probeUsedN = 0;
};

std::map<PelletView*, Armor> actors;
std::map<std::string, Clip> clips;
std::set<PelletView*> drawn, drawnCorpse;
bool ready = false;

float wrapPi(float a) {
    while (a > 3.14159265f) a -= 6.28318531f;
    while (a < -3.14159265f) a += 6.28318531f;
    return a;
}
float distXZ(const Vector3f& a, const Vector3f& b) {
    const float dx = a.x - b.x, dz = a.z - b.z;
    return std::sqrt(dx * dx + dz * dz);
}
float clipDuration(const std::string& name) {
    auto it = clips.find(name);
    return it == clips.end() ? 1.0f : it->second.duration;
}
bool clipLoops(const std::string& name) {
    auto it = clips.find(name);
    return it != clips.end() && it->second.loop;
}
std::string fourCCString(unsigned id) {
    char buf[5];
    buf[0] = char((id >> 24) & 0xffu);
    buf[1] = char((id >> 16) & 0xffu);
    buf[2] = char((id >> 8) & 0xffu);
    buf[3] = char(id & 0xffu);
    buf[4] = '\0';
    for (int i = 0; i < 4; ++i) {
        if (buf[i] < 32 || buf[i] > 126) buf[i] = '?';
    }
    return std::string(buf);
}
// Resolve the damage-receiver weakpoint from the host collision and log it.
// The source `dmg1` part wins when the host actually loaded it; otherwise the
// first collision part (bounding sphere) is the documented port approximation.
void resolveReceiverPart(Creature* actor, Armor& s) {
    const unsigned tok = s.token ? s.token : (actor->mGenerator ? actor->mGenerator->_70 : 0u);
    s.dmg1Present = false;
    s.weakpointActive = false;
    s.weakpointId = 0;
    CollPart* dmg1 = nullptr;
    CollPart* bound = nullptr;
    if (actor->mCollInfo) {
        dmg1 = actor->mCollInfo->getSphere(p2armorreceiver::DamagePartID);
        bound = actor->mCollInfo->getBoundingSphere();
    }
    if (dmg1) {
        s.dmg1Present = true;
        s.weakpointActive = true;
        s.weakpointId = dmg1->getID().mId;
    } else if (bound) {
        s.weakpointActive = true;
        s.weakpointId = bound->getID().mId;
    } else if (actor->mCollInfo) {
        // Bridge host may not expose a bounding sphere yet; fall back to the
        // body part (the bot's most common stick part) so the armor stays
        // killable. Documented port approximation when the sphere is absent.
        CollPart* head = actor->mCollInfo->getSphere('body');
        if (head) {
            s.weakpointActive = true;
            s.weakpointId = head->getID().mId;
        } else {
            s.weakpointActive = true;
            s.weakpointId = p2armorreceiver::fourCC('b','o','d','y');
        }
    } else {
        // No collision at all (early setup/bridge); still designate body so
        // the armor is killable once hits arrive. Retry in update will refine
        // to a real part when collision exists.
        s.weakpointActive = true;
        s.weakpointId = p2armorreceiver::fourCC('b','o','d','y');
    }
    const char* mode = s.dmg1Present ? "source_dmg1"
        : (s.weakpointActive ? "port_bounding_sphere" : "reject_all");
    std::printf("P2_ARMOR_RECEIVER_PART generator=%u dmg1=%s weakpoint=%s mode=%s\n",
                tok,
                s.dmg1Present ? "present" : "absent",
                s.weakpointActive ? fourCCString(s.weakpointId).c_str() : "none", mode);
    // The P1 host has no petrification lifecycle; record the wired analogue.
    std::printf("P2_ARMOR_STONE_NOTE generator=%u host_lifecycle=absent port_analogue=pressed\n",
                tok);
    std::fflush(stdout);
}

Creature* nearestTarget(const Vector3f& pos) {
    Creature* best = nullptr;
    float bestSq = SIGHT * SIGHT;
    if (naviMgr) {
        for (Navi* n : pc_p2_navis()) {
            if (!n->isAlive()) continue;
            const Vector3f p = n->getPosition();
            const float dx = p.x - pos.x, dz = p.z - pos.z;
            const float d = dx * dx + dz * dz;
            if (d < bestSq) { bestSq = d; best = n; }
        }
    }
    if (pikiMgr) {
        Iterator it(pikiMgr);
        CI_LOOP(it) {
            Piki* p = static_cast<Piki*>(*it);
            if (!p || !p->isAlive()) continue;
            const Vector3f q = p->getPosition();
            const float dx = q.x - pos.x, dz = q.z - pos.z;
            const float d = dx * dx + dz * dz;
            if (d < bestSq) { bestSq = d; best = p; }
        }
    }
    return best;
}
// Flick-trigger proxy only; a Pikmin held in a mouth is not a trigger (#886).
Piki* nearestPiki(const Vector3f& pos, float radius) {
    Piki* best = nullptr;
    float bestSq = radius * radius;
    if (pikiMgr) {
        Iterator it(pikiMgr);
        CI_LOOP(it) {
            Piki* p = static_cast<Piki*>(*it);
            if (!p || !p->isAlive() || p->isStickToMouth()) continue;
            const Vector3f q = p->getPosition();
            const float dx = q.x - pos.x, dz = q.z - pos.z;
            const float d = dx * dx + dz * dz;
            if (d < bestSq) { bestSq = d; best = p; }
        }
    }
    return best;
}
bool shouldFlick(BTeki* a) {
    const Vector3f pos = a->getPosition();
    return nearestPiki(pos, FLICK_RADIUS) != nullptr;
}
void doFlick(BTeki* a, Armor& s) {
    if (!pikiMgr) return;
    const Vector3f pos = a->getPosition();
    Iterator it(pikiMgr);
    CI_LOOP(it) {
        Piki* p = static_cast<Piki*>(*it);
        if (p && p->isAlive() && distXZ(p->getPosition(), pos) < SHAKE_RANGE
                && !p2captorhost::heldBy(a, p)) {
            p->stimulate(InteractFlick(a, SHAKE_KNOCKBACK, 0.0f, a->getDirection()));
        }
    }
    (void)s;
}
const p2captor::Geometry& mouthGeometry() { return *p2captor::geometryFor(15); }
int holding(BTeki* a, Armor& s) {
    bool occupied[p2captor::MaxSlots] = {};
    return p2captorhost::validate(a, s.held, mouthGeometry().slots, occupied);
}
float drawFrame(const Armor& s);
void shot(const char* what, int frames = 4);
p2armor::Vec3 sourceMouth(BTeki* a, const Armor& s, float frame);
// One source Obj::attackPikmin pass (default eat condition; the stabbed
// swallow maps to the P1 receiver's Esa motion).
int attackPikmin(BTeki* a, Armor& s, unsigned generator, int frame) {
    // The bite sphere is the source mouth joint (kamujnt, r25) where the drawn jaw is at source frame `frame`
    // of attack2: it rears up, then lunges ahead of the body (Armor.cpp:232-261). No facing test.
    float mouthLocal[1][3] = {{0.0f, 0.0f, 0.0f}};
    p2armor::mouthCentre(p2armor::clipIndex("attack2"), float(frame), mouthLocal[0]);
    for (int k = 0; k < 3; ++k) mouthLocal[0][k] *= s.scale;
    const p2captor::Geometry g{15u, 1, p2armor::MouthRadius, p2armor::PoisonDamage, mouthLocal};
    if (!s.mouthLogged) {
        s.mouthLogged = true;
        std::printf("P2_ARMOR_MOUTH generator=%u slots=%d radius=%.1f source=kamujnt_tables scale=%.2f "
                    "host_slots=%d\n", generator, g.slots, g.radius, double(s.scale), p2captorhost::hostSlotCount(a));
        std::fflush(stdout);
    }
    bool occupied[p2captor::MaxSlots] = {};
    p2captorhost::validate(a, s.held, g.slots, occupied);
    p2captorhost::Scene scene = p2captorhost::snapshot(a);
    const p2captor::Vec3 apos = p2captorhost::vec(a->getPosition());
    int refused = 0;
    const int caught = p2captor::eat(g, apos, s.heading, scene.prey.data(), (int)scene.prey.size(), occupied,
                                     p2captor::defaultEligible, [&](int n, int slot) {
        // motion 1 = Fall (limp): the source stab plays SUWARERU, not the eaten ESA (interactPiki.cpp:675-678)
        if (!p2captorhost::swallowInto(a, scene, n, slot, s.held, 1, &refused)) return false;
        const p2captor::Vec3 l = p2captor::toLocal(apos, s.heading, scene.prey[n].pos);
        const p2armor::Polar pl = p2armor::polar(apos, a->getDirection(), scene.prey[n].pos);
        const float df = drawFrame(s);
        const p2armor::Vec3 src = sourceMouth(a, s, df);
        std::printf("P2_ARMOR_BITE generator=%u frame=%d pikmin=1 slot=%d local_x=%.1f local_y=%.1f local_z=%.1f "
                    "angle_deg=%.1f dist_xz=%.1f draw_frame=%.1f source_mouth_dist=%.1f heading=%.3f direction=%.3f\n",
                    generator, frame, slot, l.x, l.y, l.z, double(pl.angleDeg), double(pl.distXZ), double(df),
                    double(p2chappymouth::distance(src, scene.prey[n].pos)), double(s.heading),
                    double(a->getDirection()));
        std::fflush(stdout);
        if (!s.biteShot) { s.biteShot = true; shot("bite"); }
        return true;
    });
    if (refused > 0) {
        std::printf("P2_ARMOR_EAT_REFUSED generator=%u reason=no_host_slot count=%d\n", generator, refused);
        std::fflush(stdout);
    }
    return caught;
}
void enter(Armor& s, State state, const char* clip) {
    s.state = state;
    s.stateTime = 0.0f;
    s.biteLogged = false;
    if (clip) s.clip = clip;
    auto it = clips.find(s.clip);
    if (it != clips.end()) {
        s.events.start(it->second.sampled, it->second.name);
    } else {
        s.events.cancel();
    }
}
void walkTo(BTeki* a, Armor& s, const Vector3f& target, float dt) {
    const Vector3f pos = a->getPosition();
    const float desired = std::atan2(target.x - pos.x, target.z - pos.z);
    const float frames = dt * 30.0f;  // source frames this tick
    float diff = wrapPi(desired - s.heading) * TURN_SPEED * frames;
    const float maxTurn = TURN_MAX * frames;
    if (diff > maxTurn) diff = maxTurn;
    if (diff < -maxTurn) diff = -maxTurn;
    s.heading = wrapPi(s.heading + diff);
    a->setDirection(s.heading);
    const Vector3f drive(std::sin(s.heading) * MOVE_SPEED, 0.0f,
                         std::cos(s.heading) * MOVE_SPEED);
    a->inputDrive(drive);
    a->mVelocity.set(drive);
}
void stop(BTeki* a) {
    a->inputDrive(Vector3f(0.0f, 0.0f, 0.0f));
    a->mVelocity.x = 0.0f;
    a->mVelocity.y = 0.0f;
    a->mVelocity.z = 0.0f;
}

void setPhase(Armor& s) {
    if (s.state == ARMOR_STAY) { s.phase = 0.0f; return; }
    const float duration = clipDuration(s.clip);
    const float len = duration > 0.0f ? duration : 1.0f;
    if (clipLoops(s.clip)) {
        s.phase = s.stateTime / len;
        s.phase -= std::floor(s.phase);
    } else {
        s.phase = s.stateTime / len;
        if (s.phase > 1.0f) s.phase = 1.0f;
    }
}
// ---- Evidence logs and the TEST-ONLY probe (#1014) ---------------------------------------------
using p2armor::Vec3;
Vec3 vec3(const Vector3f& v) { return Vec3{v.x, v.y, v.z}; }
// Source frame of the drawn clip: the same phase * (frames - 1) the pose draw uses.
float drawFrame(const Armor& s) {
    const int frames = p2armor::clipFrames(p2armor::clipIndex(s.clip.c_str()));
    return frames > 1 ? s.phase * float(frames - 1) : 0.0f;
}
// World position of the source mouth joint (kamujnt, Armor.cpp:205-213) at a frame of the current clip.
Vec3 sourceMouth(BTeki* a, const Armor& s, float frame) {
    float local[3] = {0.0f, 0.0f, 0.0f};
    p2armor::mouthCentre(p2armor::clipIndex(s.clip.c_str()), frame, local);
    return p2armor::toWorld(vec3(a->getPosition()), a->getDirection(), s.scale, local);
}
// World centre of a retail collision node (0 root, 1 dmg1 head, 2 shell) at a frame of the current clip.
Vec3 sourceNode(BTeki* a, const Armor& s, float frame, int node) {
    float local[3] = {0.0f, 0.0f, 0.0f};
    p2armor::nodeCentre(p2armor::clipIndex(s.clip.c_str()), frame, node, local);
    return p2armor::toWorld(vec3(a->getPosition()), a->getDirection(), s.scale, local);
}

// ---- Own collision tree (#1014) --------------------------------------------------------------------
// The P1 Chappy host's tree neither matches the drawn Armor nor the source parts (the old shared body fit
// made every point of the body stickable). The bound Armor wears the retail armor/enemycoll.txt tree
// instead: root r40 on kosijnt (`____`), `dmg1` r17.5 on headjnt (`st__`, the only stickable and
// damageable part) and the shell r22.5 on kourajnt (`_t__`), posed through the current clip from the tables
// generated by scripts/p2_armor_tables.py, plus a 'slot' mouth part with one 'kam1' child that follows
// kamujnt for the swallow. The retail ids of root and shell are both `none`; the port names them
// root/shll so each part can be found (nothing keys on those ids). Same host-swap pattern as the Bloyster
// and the Emperor. PIKMIN_P2_ARMOR_OWN_COLL=0 keeps the host tree (A/B evidence).
bool ownCollEnabled() {
    static const bool on = [] {
        const char* e = std::getenv("PIKMIN_P2_ARMOR_OWN_COLL");
        return !(e && e[0] == '0');
    }();
    return on;
}
u32 fourcc(const char* id) {
    u32 v = 0;
    for (int i = 0; i < 4; ++i) v = (v << 8) | u32(static_cast<unsigned char>(id[i] ? id[i] : '_'));
    return v;
}
void buildColl(BTeki* actor, Armor& s, unsigned generator) {
    if (!ownCollEnabled() || s.coll.own || s.coll.released || !actor->mCollInfo) return;
    namespace T = p2armortables;
    std::vector<ObjCollInfo*> nodes;
    auto make = [&](const char* id, const char* code, float radius) {
        auto* n = new ObjCollInfo();
        n->mId.setID(fourcc(id));
        n->mCode.setID(fourcc(code));
        n->mRadius = radius;
        n->mCentrePosition.set(0.0f, 0.0f, 0.0f);
        n->mJointIndex = 0;
        nodes.push_back(n);
        return n;
    };
    static const char* const ids[T::kNodeCount] = {"root", "dmg1", "shll"};
    for (int i = 0; i < T::kNodeCount; ++i) make(ids[i], T::kNodes[i].code, T::kNodes[i].radius * s.scale);
    for (int i = 1; i < T::kNodeCount; ++i) nodes[size_t(T::kNodes[i].parent)]->add(nodes[size_t(i)]);
    ObjCollInfo* slot = make("slot", "____", 1.0f);
    nodes[0]->add(slot);
    slot->add(make("kam1", "____", p2armor::MouthRadius));
    Armor::Coll c;
    c.own = new CollInfo(int(nodes.size()) + 14);
    c.own->initInfoTree(nodes[0]);
    auto prepare = [](CollPart* part) {
        if (!part) return;
        part->mIsUpdateActive = false;  // no parent shape: updateColl owns centre/radius
        part->mJointMatrix = Matrix4f::ident;
    };
    for (int i = 0; i < T::kNodeCount; ++i) {
        c.node[i] = c.own->getSphere(fourcc(ids[i]));
        prepare(c.node[i]);
    }
    c.slot = c.own->getSphere(fourcc("slot"));
    prepare(c.slot);
    c.kam = c.own->getSphere(fourcc("kam1"));
    prepare(c.kam);
    c.host = actor->mCollInfo;
    actor->mCollInfo = c.own;
    // The host's model platforms would report contacts whose part this tree cannot resolve.
    actor->mPlatMgr.release();
    s.coll = c;
    s.dmg1Present = true;
    s.weakpointActive = false;
    std::printf("P2_ARMOR_COLL_BIND generator=%u source_id=15 nodes=%zu stickable=%d root_radius=%.1f "
                "dmg1_radius=%.1f shell_radius=%.1f scale=%.2f host_parts_replaced=1\n", generator, nodes.size(),
                p2armor::stickableCount(), double(T::kNodes[0].radius * s.scale), double(T::kNodes[1].radius * s.scale),
                double(T::kNodes[2].radius * s.scale), double(s.scale));
    std::fflush(stdout);
}
// Poses every part at the actor position / heading for the current clip frame.
void updateColl(BTeki* actor, Armor& s) {
    if (!s.coll.own || s.coll.released) return;
    namespace T = p2armortables;
    Matrix4f yaw, camRot, camYaw;
    yaw.makeSRT(Vector3f(1.0f, 1.0f, 1.0f), Vector3f(0.0f, actor->getDirection(), 0.0f), Vector3f(0.0f, 0.0f, 0.0f));
    camRot.makeIdentity();
    for (int r = 0; r < 3; ++r)
        for (int c = 0; c < 3; ++c) camRot.mMtx[r][c] = invCamMat.mMtx[c][r];
    camRot.multiplyTo(yaw, camYaw);
    const int clip = p2armor::clipIndex(s.clip.c_str());
    const float frame = drawFrame(s);
    const p2armor::Vec3 apos = vec3(actor->getPosition());
    for (int i = 0; i < T::kNodeCount; ++i) {
        CollPart* part = s.coll.node[i];
        if (!part) continue;
        float c[3] = {0.0f, 0.0f, 0.0f};
        p2armor::nodeCentre(clip, frame, i, c);
        const p2armor::Vec3 w = p2armor::toWorld(apos, actor->getDirection(), s.scale, c);
        part->mCentre.set(w.x, w.y, w.z);
        part->mRadius = T::kNodes[i].radius * s.scale;
        part->mJointMatrix = camYaw;
    }
    float mouth[3] = {0.0f, 0.0f, 0.0f};
    p2armor::mouthCentre(clip, frame, mouth);
    const p2armor::Vec3 mw = p2armor::toWorld(apos, actor->getDirection(), s.scale, mouth);
    if (s.coll.slot) {
        s.coll.slot->mCentre.set(mw.x, mw.y, mw.z);
        s.coll.slot->mRadius = 1.0f;
        s.coll.slot->mJointMatrix = camYaw;
    }
    if (s.coll.kam) {
        s.coll.kam->mCentre.set(mw.x, mw.y, mw.z);
        s.coll.kam->mRadius = p2armor::MouthRadius;
        // #1020: a stabbed Pikmin is skewered on the jaw tip, laid along the nose (root -> kamujnt).
        float rootC[3] = {0.0f, 0.0f, 0.0f};
        p2armor::nodeCentre(clip, frame, 0, rootC);
        const p2armor::Vec3 rw = p2armor::toWorld(apos, actor->getDirection(), s.scale, rootC);
        const float nose[3] = {mw.x - rw.x, mw.y - rw.y, mw.z - rw.z};
        float seated[3] = {mw.x, mw.y, mw.z};
        p2skewer::seat(seated, nose, s.scale);
        s.coll.kam->mCentre.set(seated[0], seated[1], seated[2]);
        // P2 poses the held Pikmin with the kamujnt matrix itself (Creature::updateStick); use the real joint
        // rotation, falling back to the nose direction for an untabled clip.
        float rot[9];
        if (p2skewer::armorRotation(s.clip.c_str(), frame, rot))
            p2skewer::jointMatrixBasis(s.coll.kam->mJointMatrix, camRot, p2skewer::fromRotation(rot, actor->getDirection()));
        else
            p2skewer::jointMatrix(s.coll.kam->mJointMatrix, camRot, nose, actor->getDirection());
    }
}
// Gives the actor its host CollInfo back (the own tree is never freed: stuck Pikmin may still hold its
// CollPart pointers) and, for a death, seats the host carcass/centre on the body so the corpse pellet is
// born where the Armor died.
void restoreColl(BTeki* actor, Armor& s, bool dead) {
    if (!s.coll.own || s.coll.released) return;
    s.coll.released = true;
    if (!s.coll.host) return;
    if (actor->mCollInfo == s.coll.own) actor->mCollInfo = s.coll.host;
    const Vector3f p = actor->getPosition();
    if (dead && actor->mCollInfo) {
        if (CollPart* carcass = actor->mCollInfo->getSphere('carc')) carcass->mCentre.set(p.x, p.y, p.z);
        if (actor->mCollInfo->hasInfo()) {
            if (CollPart* bound = actor->mCollInfo->getBoundingSphere()) bound->mCentre.set(p.x, p.y, p.z);
            if (CollPart* cent = actor->mCollInfo->getSphere('cent')) cent->mCentre.set(p.x, p.y, p.z);
        }
    }
    s.coll.host = nullptr;
}
// Source StateAttack2::exec KEYEVENT_3 (frame 22): EnemyFunc::attackNavi(fp22 range, fp23 angle, fp24 damage).
void attackNavi(BTeki* a, Armor& s, unsigned generator) {
    (void)s;
    const p2captor::Vec3 apos = p2captorhost::vec(a->getPosition());
    for (Navi* n : pc_p2_navis()) {
        if (!n->isAlive()) continue;
        const p2captor::Vec3 np = p2captorhost::vec(n->getPosition());
        if (!p2armor::naviHit(apos, a->getDirection(), np)) continue;
        n->stimulate(InteractAttack(a, nullptr, p2armor::HitDamage, false));
        const p2armor::Polar pl = p2armor::polar(apos, a->getDirection(), np);
        std::printf("P2_ARMOR_HIT generator=%u kind=navi angle_deg=%.1f dist_xz=%.1f\n", generator,
                    double(pl.angleDeg), double(pl.distXZ));
        std::fflush(stdout);
    }
}
// Source motion frame of the drawn clip at `t` seconds into the state (phase * (frames - 1), as the draw).
float clipFrameAt(const Armor& s, float t) {
    const int frames = p2armor::clipFrames(p2armor::clipIndex(s.clip.c_str()));
    if (frames <= 1) return 0.0f;
    const float len = clipDuration(s.clip);
    float phase = len > 0.0f ? t / len : 0.0f;
    phase = phase < 0.0f ? 0.0f : (phase > 1.0f ? 1.0f : phase);
    return phase * float(frames - 1);
}
// Probe screenshot (PIKMIN_P2_PROXY_SHOT=<dir>, one BMP per key, taken a few presented frames later).
void shot(const char* what, int frames) {
    char key[64];
    std::snprintf(key, sizeof(key), "x|armor_%s", what);
    pc_gfx_proxy_shot_notify_after(key, frames);
}
// One line per held Pikmin every 3 source frames while the mouth holds: where it sits relative to the
// body facing and to the source mouth joint.
void logHold(BTeki* a, Armor& s, unsigned generator) {
    if (s.holdLogs >= 80 || (s.state != ARMOR_ATTACK2 && s.state != ARMOR_EAT)) return;
    const float frame = drawFrame(s);
    if (int(frame) / 3 == s.holdLoggedFrame) return;
    const Vec3 apos = vec3(a->getPosition());
    const Vec3 mouth = sourceMouth(a, s, frame);
    bool first = true;
    for (Creature* c = a->mStickListHead; c; c = c->mNextSticker) {
        if (!c->isPiki() || !c->isStickToMouth()) continue;
        if (first) { s.holdLoggedFrame = int(frame) / 3; first = false; if (!s.holdShot) { s.holdShot = true; shot("hold", 40); } }
        const Vec3 q = vec3(c->getPosition());
        const p2armor::Polar pl = p2armor::polar(apos, a->getDirection(), q);
        std::printf("P2_ARMOR_HOLD generator=%u state=%s frame=%.1f angle_deg=%.1f dist_xz=%.1f y=%.1f "
                    "mouth_dist=%.1f\n", generator, stateName(s.state), double(frame), double(pl.angleDeg),
                    double(pl.distXZ), double(q.y - apos.y), double(p2chappymouth::distance(mouth, q)));
        ++s.holdLogs;
    }
    std::fflush(stdout);
}
// Latched-Pikmin census (not the mouth): logs when the count stuck to the body changes.
void logLatch(BTeki* a, Armor& s, unsigned generator) {
    int total = 0;
    for (Creature* c = a->mStickListHead; c; c = c->mNextSticker)
        if (c->isPiki() && !c->isStickToMouth()) ++total;
    if (total == s.latchLogged) return;
    s.latchLogged = total;
    const float frame = drawFrame(s);
    const Vec3 apos = vec3(a->getPosition());
    const Vec3 head = sourceNode(a, s, frame, p2armor::NodeDmg1), shell = sourceNode(a, s, frame, p2armor::NodeShell);
    std::printf("P2_ARMOR_LATCH generator=%u stuck=%d health=%.1f", generator, total, double(a->mHealth));
    for (Creature* c = a->mStickListHead; c; c = c->mNextSticker) {
        if (!c->isPiki() || c->isStickToMouth()) continue;
        const Vec3 q = vec3(c->getPosition());
        const p2armor::Polar pl = p2armor::polar(apos, a->getDirection(), q);
        std::printf(" [part=%s angle_deg=%.1f dist_xz=%.1f to_head=%.1f to_shell=%.1f]",
                    c->mStickPart ? fourCCString(c->mStickPart->getID().mId).c_str() : "none", double(pl.angleDeg),
                    double(pl.distXZ), double(p2chappymouth::distance(head, q)), double(p2chappymouth::distance(shell, q)));
    }
    std::printf("\n");
    std::fflush(stdout);
    if (!s.headShot) {
        for (Creature* c = a->mStickListHead; c; c = c->mNextSticker) {
            if (c->isPiki() && !c->isStickToMouth() && c->mStickPart
                    && c->mStickPart->getID().mId == p2armorreceiver::DamagePartID) {
                s.headShot = true;
                shot("latch_head");
                break;
            }
        }
    }
}

// TEST-ONLY evidence probe (PIKMIN_P2_ARMOR_PROBE=1), never active in a normal run. Headless runs have
// no player, so the skewer and the latch rules are exercised by moving Pikmin into the scene and
// throwing them through the REAL Navi::throwPiki / PikiFlyingState path:
//   * 0.5 s: the captain is stood 230 units "behind" the Armor along the camera forward axis;
//   * 2 s: Pikmin pinned around the body start two bite cycles: beneath the rearing head, both sides and
//     behind (cycle 1), then 70 units straight ahead (cycle 2), so the log shows which ones the bite
//     really skewers;
//   * 16 s: the Armor is forced to its walk pose and held still (health restored); a bomb and two captain
//     punches (head reach / tail side) are sent to the receiver, then four Pikmin are thrown at the shell
//     from behind and four at the head from the front (aim scaled 1.0 .. 1.3 so the real collision decides).
BTeki* probeOwner = nullptr;
bool probeEnabled() {
    static const bool on = [] {
        const char* e = std::getenv("PIKMIN_P2_ARMOR_PROBE");
        return e && *e && *e != '0';
    }();
    return on;
}
constexpr float PROBE_FREEZE_BEGIN = 16.0f;
constexpr float PROBE_FREEZE_END = 28.0f;
bool probeFrozen(const BTeki* a, const Armor& s) {
    return probeEnabled() && probeOwner == a && s.probeTime >= PROBE_FREEZE_BEGIN && s.probeTime < PROBE_FREEZE_END;
}
Piki* probeFreePiki(Armor& s) {
    if (!pikiMgr) return nullptr;
    Piki* spare = nullptr;
    Iterator it(pikiMgr);
    CI_LOOP(it) {
        Piki* p = static_cast<Piki*>(*it);
        if (!p || !p->isAlive() || p->isStickTo() || p->isStickToMouth() || p->isBuried() || !p->isVisible()
                || p->getState() == 14) continue;  // 14 = PIKISTATE_Flying: never reuse a Pikmin still in the air
        bool used = false;
        for (int i = 0; i < s.probeUsedN; ++i) used = used || s.probeUsed[i] == p;
        if (used) { if (!spare) spare = p; continue; }  // only ten Pikmin are on the field: reuse a free one when needed
        if (s.probeUsedN < 24) s.probeUsed[s.probeUsedN++] = p;
        return p;
    }
    return spare;
}
Vector3f probeGround(float x, float y, float z) {
    return Vector3f(x, mapMgr ? mapMgr->getMinY(x, z, true) : y, z);
}
Vector3f probeLocalToWorld(BTeki* a, float lx, float lz) {
    const float h = a->getDirection();
    const Vector3f ap = a->getPosition();
    const float wx = ap.x + lx * std::cos(h) + lz * std::sin(h), wz = ap.z - lx * std::sin(h) + lz * std::cos(h);
    return probeGround(wx, ap.y, wz);
}
Piki* probePlace(BTeki* a, Armor& s, const char* what, float lx, float lz) {
    Piki* p = probeFreePiki(s);
    if (!p) return nullptr;
    p->mSRT.t = probeLocalToWorld(a, lx, lz);
    p->mVelocity.set(0.0f, 0.0f, 0.0f);
    std::printf("P2_ARMOR_PROBE kind=place what=%s local_x=%.1f local_z=%.1f x=%.1f y=%.1f z=%.1f\n", what,
                double(lx), double(lz), double(p->mSRT.t.x), double(p->mSRT.t.y), double(p->mSRT.t.z));
    std::fflush(stdout);
    return p;
}
void probeHeal(BTeki* a, Armor& s) {
    a->mHealth = LIFE;
    s.lastHealth = LIFE;
}
// TEST-ONLY idle probe (PIKMIN_P2_ARMOR_PROBE_IDLE=1, #1063), independent of the bite probe: at 2 s a Pikmin is put 120
// units ahead so the Armor surfaces and chases it; at 12 s every Pikmin and the captain are moved 900 units away, so the
// Armor is truly idle and the source Move -> GoHome -> Dive -> Stay sequence shows in the P2_ARMOR_STATE log; at 25 s a
// Pikmin is put back 150 units ahead to show it resurfaces.
void runIdleProbe(BTeki* actor, Armor& s, unsigned generator, float dt) {
    static const bool on = [] {
        const char* e = std::getenv("PIKMIN_P2_ARMOR_PROBE_IDLE");
        return e && *e && *e != '0';
    }();
    if (!on || s.state == ARMOR_DEAD) return;
    static BTeki* owner = nullptr;
    if (!owner) owner = actor;
    if (owner != actor) return;
    s.idleT += dt;
    const Vector3f ap = actor->getPosition();
    if (s.idleStage == 0 && s.idleT >= 2.0f) {
        s.idleStage = 1;
        probePlace(actor, s, "idle_wake", 0.0f, 120.0f);
    } else if (s.idleStage == 1 && s.idleT >= 12.0f) {
        s.idleStage = 2;
        const Vector3f far(ap.x + 900.0f, ap.y, ap.z);
        if (pikiMgr) {
            Iterator it(pikiMgr);
            CI_LOOP(it) {
                Piki* p = static_cast<Piki*>(*it);
                if (p && p->isAlive() && !p->isStickToMouth()) p->mSRT.t = far;
            }
        }
        for (Navi* n : pc_p2_navis()) n->mSRT.t = far;
        std::printf("P2_ARMOR_PROBE kind=idle generator=%u t=%.1f state=%s\n", generator, double(s.idleT), stateName(s.state));
        std::fflush(stdout);
    } else if (s.idleStage == 2 && s.idleT >= 25.0f) {
        s.idleStage = 3;
        std::printf("P2_ARMOR_PROBE kind=resurface_bait generator=%u t=%.1f state=%s\n", generator, double(s.idleT),
                    stateName(s.state));
        std::fflush(stdout);
        probePlace(actor, s, "resurface_bait", 0.0f, 150.0f);
    }
}
void runProbe(BTeki* actor, Armor& s, unsigned generator, float dt) {
    if (!probeEnabled() || s.state == ARMOR_DEAD) return;
    if (!probeOwner) probeOwner = actor;  // the probe drives exactly one Armor (the first to tick)
    if (probeOwner != actor) return;
    s.probeTime += dt;
    const Vector3f ap = actor->getPosition();
    if (s.probeTime >= 0.5f && !s.probeCaptain) {
        if (Navi* navi = naviMgr ? naviMgr->getActiveNavi() : nullptr) {
            s.probeCaptain = true;
            float fx = 0.0f, fz = 1.0f;
            if (Camera* cam = navi->controlCamera()) {
                fx = -cam->mLookAtMtx.mMtx[2][0];
                fz = -cam->mLookAtMtx.mMtx[2][2];
                const float len = std::sqrt(fx * fx + fz * fz);
                if (len > 1.0e-4f) { fx /= len; fz /= len; }
            }
            const float cx = ap.x - fx * 230.0f, cz = ap.z - fz * 230.0f;
            navi->mSRT.t = probeGround(cx, ap.y, cz);
            navi->mFaceDirection = std::atan2(fx, fz);
            std::printf("P2_ARMOR_PROBE kind=captain generator=%u x=%.1f y=%.1f z=%.1f\n", generator, double(cx),
                        double(navi->mSRT.t.y), double(cz));
            std::fflush(stdout);
        }
    }
    // Two bite cycles with Pikmin pinned in place (their AI would walk them away). Cycle 1: a bait beneath the
    // rearing head (the old fixed slot skewered it) plus one on each side and one behind. Cycle 2: a bait 70
    // units straight ahead, where the jaw visibly lands. The log lists which ones the real bite skewers.
    if (s.probeCycle == 0 && s.probeTime >= 2.0f) {
        s.probeCycle = 1;
        struct Spec { const char* name; float x, z; };
        static const Spec spec[4] = {{"under_head", 0.0f, 40.0f}, {"side_right", 50.0f, 5.0f}, {"side_left", -50.0f, 5.0f},
                                     {"behind", 0.0f, -45.0f}};
        for (int i = 0; i < 4; ++i) {
            s.probePin[i] = probePlace(actor, s, spec[i].name, spec[i].x, spec[i].z);
            s.probePinName[i] = spec[i].name;
            s.probePinLx[i] = spec[i].x;
            s.probePinLz[i] = spec[i].z;
            if (s.probePin[i]) s.probePinPos[i] = s.probePin[i]->mSRT.t;
        }
        s.probePinN = 4;
    }
    if (s.probeCycle == 2 && s.state == ARMOR_MOVE && s.probeTime >= s.probeCycleAt + 0.5f) {
        s.probeCycle = 3;
        s.probePin[0] = probePlace(actor, s, "ahead_70", 0.0f, 70.0f);
        s.probePinName[0] = "ahead_70";
        s.probePinLx[0] = 0.0f;
        s.probePinLz[0] = 70.0f;
        if (s.probePin[0]) s.probePinPos[0] = s.probePin[0]->mSRT.t;
        s.probePinN = 1;
    }
    if (s.probeCycle == 1 || s.probeCycle == 3) {
        if (s.state == ARMOR_ATTACK2) s.probeSawAttack = true;
        if (s.probeSawAttack && s.state != ARMOR_ATTACK2) {
            s.probeSawAttack = false;
            for (int i = 0; i < s.probePinN; ++i) {
                Piki* p = s.probePin[i];
                if (!p) continue;
                std::printf("P2_ARMOR_PROBE kind=decoy cycle=%d what=%s placed_local_x=%.1f placed_local_z=%.1f skewered=%d "
                            "alive=%d\n", s.probeCycle == 1 ? 1 : 2, s.probePinName[i], double(s.probePinLx[i]),
                            double(s.probePinLz[i]), int(p->isStickToMouth() && p->getStickObject() == actor),
                            int(p->isAlive()));
                s.probePin[i] = nullptr;
            }
            std::fflush(stdout);
            s.probePinN = 0;
            s.probeCycle = s.probeCycle == 1 ? 2 : 4;
            s.probeCycleAt = s.probeTime;
        } else {
            for (int i = 0; i < s.probePinN; ++i) {
                Piki* p = s.probePin[i];
                if (!p || p->isStickToMouth() || !p->isAlive()) continue;
                p->mSRT.t = s.probePinPos[i];
                p->mVelocity.set(0.0f, 0.0f, 0.0f);
            }
        }
    }
    if (s.probeTime >= PROBE_FREEZE_BEGIN && !s.probeFreezeInit) {
        s.probeFreezeInit = true;
        p2captorhost::release(actor, s.held);
        enter(s, ARMOR_MOVE, "move");
        s.stateTime = 0.3f;  // a mid-walk pose, then held still
        setPhase(s);
        probeHeal(actor, s);
        std::printf("P2_ARMOR_PROBE kind=freeze generator=%u frame=%.1f\n", generator, double(drawFrame(s)));
        std::fflush(stdout);
    }
    const bool inWindow = s.probeFreezeInit && s.probeTime < PROBE_FREEZE_END;
    if (inWindow && actor->mHealth < 100.0f) probeHeal(actor, s);  // keep the subject alive for the later tests
    // Receiver paths, one every 0.4 s, health restored before each: a bomb (no part) and two captain punches
    // (no part): in front of the head and behind the shell. Each result is read one interval later.
    if (inWindow && s.probeRecvStage < 4 && s.probeTime >= PROBE_FREEZE_BEGIN + 0.2f + 0.4f * float(s.probeRecvStage)) {
        Navi* navi = naviMgr ? naviMgr->getActiveNavi() : nullptr;
        static const char* const name[3] = {"bomb", "punch_head_front", "punch_tail_behind"};
        if (s.probeRecvStage >= 1)
            std::printf("P2_ARMOR_PROBE kind=recv_result test=%s health_before=%.1f health_after=%.1f\n",
                        name[s.probeRecvStage - 1], double(s.probeRecvHealth), double(actor->mHealth));
        if (s.probeRecvStage < 3) {
            probeHeal(actor, s);
            s.probeRecvHealth = actor->mHealth;
            const float frame = drawFrame(s);
            const p2armor::Vec3 head = sourceNode(actor, s, frame, p2armor::NodeDmg1);
            const float h = actor->getDirection();
            bool ok = false;
            if (s.probeRecvStage == 0) {
                ok = actor->stimulate(InteractBomb(nullptr, 5.0f, nullptr)) != 0;
            } else if (navi) {
                const Vector3f saved = navi->mSRT.t;
                const float savedFace = navi->mFaceDirection;
                const float side = s.probeRecvStage == 1 ? 1.0f : -1.0f;  // in front of the head / behind the shell
                const float reach = s.probeRecvStage == 1 ? 30.0f : 60.0f;
                navi->mSRT.t = probeGround(head.x + std::sin(h) * reach * side, ap.y, head.z + std::cos(h) * reach * side);
                navi->mFaceDirection = h + (s.probeRecvStage == 1 ? 3.14159265f : 0.0f);  // facing the body
                ok = actor->stimulate(InteractAttack(navi, nullptr, 10.0f, false)) != 0;
                navi->mSRT.t = saved;
                navi->mFaceDirection = savedFace;
            }
            std::printf("P2_ARMOR_PROBE kind=recv test=%s accepted=%d\n", name[s.probeRecvStage], int(ok));
            std::fflush(stdout);
        }
        ++s.probeRecvStage;
    }
    for (int i = 0; i < s.probeThrows; ++i) {
        if (s.probeLanded[i] || s.probeTime < s.probeThrownAt[i] + 1.8f) continue;
        s.probeLanded[i] = true;
        Piki* t = s.probeThrown[i];
        if (!t) continue;
        std::printf("P2_ARMOR_PROBE kind=landing n=%d target=%s stuck=%d part=%s alive=%d health=%.1f\n", i,
                    i < 4 ? "shell" : "head", int(t->isStickTo() && t->getStickObject() == actor),
                    t->mStickPart ? fourCCString(t->mStickPart->getID().mId).c_str() : "none", int(t->isAlive()),
                    double(actor->mHealth));
        std::fflush(stdout);
    }
    if (inWindow && s.probeRecvStage >= 4 && s.probeThrows < 8 && s.probeTime >= s.probeNextThrow) {
        Navi* navi = naviMgr ? naviMgr->getActiveNavi() : nullptr;
        Piki* p = probeFreePiki(s);
        if (!navi || !p) {
            if (s.probeTime >= s.probeNoPikiLog) {
                s.probeNoPikiLog = s.probeTime + 2.0f;
                std::printf("P2_ARMOR_PROBE kind=throw_blocked navi=%d piki=%d used=%d\n", int(navi != nullptr),
                            int(p != nullptr), s.probeUsedN);
                std::fflush(stdout);
            }
        } else {
            const bool head = s.probeThrows >= 4;
            const float frame = drawFrame(s);
            const p2armor::Vec3 t = sourceNode(actor, s, frame, head ? p2armor::NodeDmg1 : p2armor::NodeShell);
            const float h = actor->getDirection();
            const float dirx = std::sin(h) * (head ? 1.0f : -1.0f), dirz = std::cos(h) * (head ? 1.0f : -1.0f);
            const float lx = t.x + dirx * 120.0f, lz = t.z + dirz * 120.0f;  // 120 units out on the approach side
            const Vector3f launch = probeGround(lx, ap.y, lz);
            static const float scan[4] = {1.0f, 1.1f, 1.2f, 1.3f};
            const float k = scan[s.probeThrows & 3];
            const Vector3f aim(launch.x + (t.x - launch.x) * k, t.y, launch.z + (t.z - launch.z) * k);
            const Vector3f saved = navi->mSRT.t;
            navi->mSRT.t = launch;
            p->mFSM->transit(p, 14);  // PIKISTATE_Flying, exactly as NaviThrowState key action 0
            navi->throwPiki(p, aim);
            navi->mSRT.t = saved;
            s.probeThrown[s.probeThrows] = p;
            s.probeThrownAt[s.probeThrows] = s.probeTime;
            std::printf("P2_ARMOR_PROBE kind=throw n=%d target=%s k=%.2f launch=(%.1f,%.1f,%.1f) target_pos=(%.1f,%.1f,%.1f)\n",
                        s.probeThrows, head ? "head" : "shell", double(k), double(launch.x), double(launch.y),
                        double(launch.z), double(t.x), double(t.y), double(t.z));
            std::fflush(stdout);
            if (s.probeThrows == 0) shot("shell_throw", 40);
            ++s.probeThrows;
            s.probeNextThrow = s.probeTime + 0.6f;
        }
    }
    if (s.probeTime >= 29.0f && !s.probeDone) {
        s.probeDone = true;
        std::printf("P2_ARMOR_PROBE kind=done generator=%u health=%.1f\n", generator, double(actor->mHealth));
        std::fflush(stdout);
    }
}
}

void pc_p2_armor_reset() {
    for (auto& e : actors) {
        BTeki* actor = static_cast<BTeki*>(e.first);
        if (actor && e.second.coll.own && !e.second.coll.released && e.second.coll.host
                && actor->mCollInfo == e.second.coll.own)
            actor->mCollInfo = e.second.coll.host;  // stage boundary: hand every Armor its host tree back
    }
    actors.clear();
    clips.clear();
    drawn.clear();
    drawnCorpse.clear();
    ready = false;
}
void pc_p2_armor_forget_piki(Piki* piki) {
    for (auto& entry : actors) entry.second.held.forget(piki);
}

void pc_p2_armor_forget(BTeki* actor) {
    auto* v = static_cast<PelletView*>(actor);
    pc_randomizer_p2_forget_source(v);
    auto it = actors.find(v);
    if (it != actors.end()) {
        p2captorhost::release(actor, it->second.held); // teardown frees the mouth
        restoreColl(actor, it->second, false);
    }
    actors.erase(v);
    drawn.erase(v);
    drawnCorpse.erase(v);
}
bool pc_p2_armor_suppress_ai(const BTeki* actor){return ready&&actors.count(static_cast<PelletView*>(const_cast<BTeki*>(actor)))!=0;}

unsigned long pc_p2_armor_count() { return (unsigned long)actors.size(); }
bool pc_p2_armor_registered(BTeki* actor) { return actors.count(static_cast<PelletView*>(actor)) != 0; }
bool pc_p2_armor_receiver_rejects(Teki* teki, const InteractAttack* attack) {
    if (!ready || !teki) return false;
    auto it = actors.find(static_cast<PelletView*>(teki));
    if (it == actors.end()) return false;
    Armor& s = it->second;
    const unsigned tok = s.token ? s.token : (teki->mGenerator ? teki->mGenerator->_70 : 0u);

    if (s.coll.own && !s.coll.released) {
        // Source Armor::damageCallBack on the retail tree: only `dmg1` (or Bittered) takes damage. A hit that
        // carries a part is a latched Pikmin (the stuck part is its hit part); the shell and the body
        // cannot be stuck to, so they never reach here with a part. A partless hit is refused, except a
        // captain punch whose hand reaches the head sphere (NaviPunchState::hitCallback delivers the part the
        // hand touched; the port punch carries none, so the head reach stands in for it).
        const bool hasPart = attack && attack->mCollPart;
        const unsigned partId = hasPart ? attack->mCollPart->getID().mId : 0u;
        bool accept = p2armor::partAccepts(s.bittered, partId) && (hasPart || s.bittered);
        const char* reason = accept ? (s.bittered ? "bittered" : "dmg1") : "reject";
        const bool navi = attack && attack->mOwner && attack->mOwner->mObjType == OBJTYPE_Navi;
        CollPart* head = s.coll.node[p2armor::NodeDmg1];
        if (!accept && !hasPart && navi && head) {
            Navi* n = static_cast<Navi*>(attack->mOwner);
            const float reach = C_NAVI_PARM(n, mPunchRadius) + n->getCentreSize();
            if (p2armor::punchReachesHead(p2captorhost::vec(n->getPosition()), n->mFaceDirection,
                                          p2captorhost::vec(head->mCentre), head->mRadius, reach)) {
                accept = true;
                reason = "punch_head";
            }
        }
        // Bounded: the first 40 decisions, then every 25th (a latched Pikmin attacks every few frames).
        const int n = ++s.recvLogged;
        if (n <= 40 || n % 25 == 0) {
            std::printf("P2_ARMOR_RECEIVER generator=%u decision=%s reason=%s part=%s navi=%d n=%d\n", tok,
                        accept ? "accept" : "reject", reason,
                        hasPart ? fourCCString(partId).c_str() : "none", int(navi), n);
            std::fflush(stdout);
        }
        return !accept;
    }

    p2armorreceiver::Inputs in;
    in.bittered = s.bittered;
    in.has_part = attack && attack->mCollPart;
    in.part_id = in.has_part ? attack->mCollPart->getID().mId : 0u;
    // Host tree only (PIKMIN_P2_ARMOR_OWN_COLL=0): the port weakpoint substitutes for the missing source
    // `dmg1` part; the exact source rule already covers `dmg1` when present.
    in.weakpoint_active = s.weakpointActive && !s.dmg1Present;
    in.weakpoint_id = s.weakpointId;

    const p2armorreceiver::Decision decision = p2armorreceiver::decide(in);
    const bool reject = decision == p2armorreceiver::Decision::Reject;
    std::printf("P2_ARMOR_RECEIVER generator=%u decision=%s reason=%s part=%s bittered=%d "
                "weakpoint=%s\n",
                tok, reject ? "reject" : "accept",
                p2armorreceiver::decisionName(decision),
                in.has_part ? fourCCString(in.part_id).c_str() : "none", int(in.bittered),
                s.weakpointActive ? fourCCString(s.weakpointId).c_str() : "none");
    std::fflush(stdout);
    return reject;
}
// Source EnemyBase::bombCallBack (enemyBase.cpp:2908) is an unconditional addDamage(damage, 1.0f) and the
// Armor does not override it, so a bomb hurts the Armor on any part. Observer only.
void pc_p2_armor_bombed(Teki* teki, float damage) {
    if (!ready || !teki) return;
    auto it = actors.find(static_cast<PelletView*>(teki));
    if (it == actors.end()) return;
    std::printf("P2_ARMOR_RECEIVER generator=%u decision=accept reason=base_bomb part=none damage=%.1f\n",
                it->second.token, double(damage));
    std::fflush(stdout);
}

void pc_p2_armor_set_bittered(BTeki* actor, bool value) {
    if (!ready || !actor) return;
    auto it = actors.find(static_cast<PelletView*>(actor));
    if (it == actors.end()) return;
    it->second.bittered = value;
    std::printf("P2_ARMOR_BITTERED generator=%u value=%d\n",
                actor->mGenerator ? actor->mGenerator->_70 : 0u, int(value));
    std::fflush(stdout);
}

void pc_p2_armor_start_stone(BTeki* actor) {
    if (!ready || !actor) return;
    auto it = actors.find(static_cast<PelletView*>(actor));
    if (it == actors.end()) return;
    Armor& s = it->second;
    if (s.stone) return;
    s.stone = true;

    // Source Obj::doStartStoneState iterates Stickers(this); InteractFlick's
    // actCommon detaches the sticker, so snapshot the list before flicking.
    std::vector<Creature*> mouths;
    for (Creature* c = actor->mStickListHead; c; c = c->mNextSticker) {
        if (c->isStickToMouth()) mouths.push_back(c);
    }
    int flicked = 0;
    for (Creature* c : mouths) {
        if (c->isAlive()
                && c->stimulate(InteractFlick(actor, 0.0f, 0.0f, FLICK_BACKWARDS_ANGLE))) {
            ++flicked;
        }
    }
    // The mouth holds are among the stickers flicked above (#886).
    s.held.clear();
    std::printf("P2_ARMOR_STONE generator=%u event=enter stuck=%zu flicked=%d\n",
                actor->mGenerator ? actor->mGenerator->_70 : 0u, mouths.size(), flicked);
    std::fflush(stdout);
}

void pc_p2_armor_finish_stone(BTeki* actor) {
    if (!ready || !actor) return;
    auto it = actors.find(static_cast<PelletView*>(actor));
    if (it == actors.end()) return;
    Armor& s = it->second;
    if (!s.stone) return;
    s.stone = false;
    // Preserve consumed sampled events across the pressed-state exit; replaying
    // them would duplicate bite/eat effects. Clip transitions reset the clock.
    std::printf("P2_ARMOR_STONE generator=%u event=exit\n",
                actor->mGenerator ? actor->mGenerator->_70 : 0u);
    std::fflush(stdout);
}

float pc_p2_armor_param_f(const BTeki* actor, int idx, float fallback) {
    if (!ready || !actors.count(static_cast<PelletView*>(const_cast<BTeki*>(actor)))) return fallback;
    if (idx == TPF_Life) return LIFE;
    if (idx == TPF_LifeRecoverRate) return 0.0f;
    switch (idx) {
    case TPF_VisibleRange:
    case TPF_VisibleAngle:
    case TPF_AttackableRange:
    case TPF_AttackableAngle:
    case TPF_AttackRange:
    case TPF_AttackHitRange:
    case TPF_AttackPower:
    case TPF_DangerTerritoryRange:
    case TPF_SafetyTerritoryRange:
        return 0.0f;
    default:
        return fallback;
    }
}

bool pc_p2_armor_clip(const BTeki* actor, const char*& name, float& phase) {
    if (!ready) return false;
    auto* view=static_cast<PelletView*>(const_cast<BTeki*>(actor));
    auto it = actors.find(view);
    if (it == actors.end()) return false;
    name = it->second.clip.c_str();
    phase = it->second.phase;
    if(drawn.insert(view).second){
        const unsigned tok=it->second.token ? it->second.token : (actor->mGenerator?actor->mGenerator->_70:0u);
        std::printf("P2_ARMOR_DRAW generator=%u source_id=15 species=Armor corpse=0\n",tok);
        std::fflush(stdout);
    }
    return true;
}

void pc_p2_armor_setup() {
    pc_p2_armor_reset();
    if (!tekiMgr) return;

    std::ifstream bank("p2-ground-bank.txt");
    if (bank) {
        std::string token;
        if (bank >> token && token == "P2_GROUND_BANK_1") {
            while (bank >> token) {
                if (token == "species") {
                    std::string species, id;
                    bank >> species >> id;
                } else if (token == "clip") {
                    std::string species, name, events, marker, status;
                    long long frames = 0;
                    int poses = 0;
                    bank >> species >> name >> frames >> events >> marker >> poses >> status;
                    if (species == "Armor") {
                        Clip clip;
                        clip.name = name;
                        clip.duration = frames > 0 ? float(frames) / 30.0f : 1.0f;
                        clip.loop = (name == "move");
                        p2armorevents::Row row;
                        row.name = name;
                        row.sourceFrames = frames > 0 ? int(frames) : 0;
                        row.poseCount = poses;
                        row.loop = clip.loop;
                        if (events != "-") {
                            size_t start = 0;
                            while (start < events.size()) {
                                const size_t comma = events.find(',', start);
                                const std::string pair = events.substr(start, comma - start);
                                const size_t colon = pair.find(':');
                                if (colon != std::string::npos) {
                                    const int eventFrame = std::atoi(pair.substr(0, colon).c_str());
                                    const std::string key = pair.substr(colon + 1);
                                    clip.events.emplace_back(eventFrame, std::atoi(key.c_str()));
                                    row.events.push_back(p2sampled::Event{eventFrame, key});
                                }
                                if (comma == std::string::npos) break;
                                start = comma + 1;
                            }
                        }
                        clip.sampled = p2armorevents::makeClip(row);
                        clips[name] = clip;
                    }
                } else if (token == "frames") {
                    // P2_BANK_FRAMES_1 trailer (#895): per-pose source frames,
                    // consumed by the batch draw paths; skip its list token here.
                    std::string framesList;
                    bank >> framesList;
                } else {
                    break;
                }
            }
        }
    }

    std::ifstream in("p2-ground-actors.txt");
    if (!in) return;
    std::string header;
    int count = 0;
    if (!(in >> header >> count) || header != "P2_GROUND_ACTORS_1" || count < 1) return;
    std::map<unsigned, std::string> wanted;
    for (int i = 0; i < count; ++i) {
        unsigned long long generator = 0;
        std::string species;
        if (!(in >> generator >> species)) return;
        if (species == "Armor") wanted[unsigned(generator)] = species;
    }
    const bool bridge = pc_randomizer_p2_bridge() && !pc_pikipelago_room_preview();
    if (bridge) {
        wanted.clear();
        for (unsigned id : pc_p2_campaign_ids(15)) wanted[id] = "Armor";
    }
    if (wanted.empty()) return;

    std::set<unsigned> found;
    Iterator it(tekiMgr);
    CI_LOOP(it) {
        Teki* actor = static_cast<Teki*>(*it);
        if (!actor || !actor->mGenerator) continue;
        const unsigned token = bridge ? pc_p2_campaign_token(actor) : actor->mGenerator->_70;
        auto match = wanted.find(token);
        if (match == wanted.end()) continue;
        if (actor->mTekiType != TEKI_Chappy) {
            std::printf("P2_ARMOR_ERROR native_type generator=%u\n", token);
            std::abort();
        }
        Armor& s = actors[static_cast<PelletView*>(actor)];
        s = Armor();  // reject stale clock/capture state on actor-address reuse
        s.home = actor->getPosition();
        s.heading = actor->getDirection();
        s.token = token;
        actor->mHealth = LIFE;
        s.lastHealth = LIFE;
        resolveReceiverPart(actor, s);
        s.weakpointActive=true; s.weakpointId=p2armorreceiver::fourCC('b','o','d','y');
        enter(s, ARMOR_STAY, "appear");
        if (bridge) {
            pc_randomizer_p2_bind_source(static_cast<PelletView*>(actor), 15, token);
            std::printf("P2_ARMOR_DELIVERY_BIND generator=%u source_id=15\n", token);
        }
        std::printf("P2_ARMOR_BIND generator=%u source_id=15 visual_only=0\n", token);
        const Vector3f pos = actor->getPosition();
        std::printf("P2_ENEMY_READY species=Armor native_family=Chappy generator=%u "
                    "x=%.7f y=%.7f z=%.7f health=%.1f max_health=%.1f behavior=native "
                    "source_FSM=implemented attack=animation_event\n",
                    token, pos.x, pos.y, pos.z, actor->mHealth, LIFE);
        found.insert(token);
    }
    if (found.size() != wanted.size()) {
        std::printf("P2_ARMOR_ERROR missing_actor wanted=%zu found=%zu\n", wanted.size(), found.size());
        std::abort();
    }
    ready = true;
}

void pc_p2_armor_update(BTeki* actor) {
    if (!ready) return;
    auto it = actors.find(static_cast<PelletView*>(actor));
    if (it == actors.end()) return;
    Armor& s = it->second;
    const float dt = gsys->getFrameTime();
    if (dt <= 0.0f || dt > 0.5f) return;
    s.scale = actor->mSRT.s.x > 0.01f && actor->mSRT.s.x < 100.0f ? actor->mSRT.s.x : 1.0f;
    {
        const unsigned probeGen = s.token ? s.token : (actor->mGenerator ? pc_p2_campaign_token(actor) : 0u);
        if (actor->mHealth > 0.0f && s.state != ARMOR_DEAD) buildColl(actor, s, probeGen);
        runProbe(actor, s, probeGen, dt);
        runIdleProbe(actor, s, probeGen, dt);
    }
    const bool probeHold = probeFrozen(actor, s);
    // Port stone analogue: the P1 host has no petrified lifecycle, so the
    // source doStartStoneState flick fires on the rising edge of the host
    // TEKIOPT_Pressed state (see pc_p2_armor.h / P2_ARMOR_RECEIVER.md).
    const bool pressed = actor->getTekiOption(TEKIOPT_Pressed);
    if (pressed && !s.stone) {
        pc_p2_armor_start_stone(actor);
    } else if (!pressed && s.stone) {
        pc_p2_armor_finish_stone(actor);
    }
    const Vector3f pos = actor->getPosition();
    const unsigned live = actor->mGenerator ? pc_p2_campaign_token(actor) : 0u;
    if (live) s.token = live;
    const unsigned generator = s.token ? s.token : live;
    // Collision may not exist at setup time; retry weakpoint resolve until it
    // sticks so the armor is killable (otherwise all damage rejects).
    if (!s.weakpointActive && !s.coll.own){resolveReceiverPart(actor, s); s.weakpointActive=true; s.weakpointId=p2armorreceiver::fourCC('b','o','d','y');}
    if (actor->mStoredDamage > 0.0f) actor->makeDamaged();

    // Natural-combat observability (#165/#407): an incremental, still-positive
    // health decrease is real receiver damage (a Pikmin attack accepted by the
    // source dmg1/weakpoint rule). The death marker records prior_health (the
    // value one update before <=0) so a single fixture-injected jump to 0 is
    // distinguishable from a combat-culminated death by its larger prior_health.
    const float previousHealth = s.lastHealth;
    if (actor->mHealth < s.lastHealth && actor->mHealth > 0.0f) {
        std::printf("P2_ARMOR_DAMAGE generator=%u source_id=15 health=%.1f\n",
                    generator, actor->mHealth);
        std::fflush(stdout);
    }
    s.lastHealth = actor->mHealth;

    if (actor->mHealth <= 0.0f && s.state != ARMOR_DEAD) {
        if (!s.deadLogged) {
            std::printf("P2_ARMOR_DEAD generator=%u source_id=15 health=0 prior_health=%.1f\n",
                        generator, previousHealth);
            std::fflush(stdout);
            s.deadLogged = true;
        }
        const int freed = p2captorhost::release(actor, s.held);
        if (freed > 0) {
            std::printf("P2_ARMOR_RELEASE generator=%u reason=death pikmin=%d\n", generator, freed);
            std::fflush(stdout);
        }
        restoreColl(actor, s, true);
        enter(s, ARMOR_DEAD, "dead");
        if (drawnCorpse.insert(static_cast<PelletView*>(actor)).second) {
            std::printf("P2_ARMOR_CORPSE_DRAW generator=%u source_id=15 species=Armor\n", generator);
            std::fflush(stdout);
        }
    }

    if (probeHold) stop(actor); else s.stateTime += dt;
    switch (probeHold ? ARMOR_INVALID : s.state) {
    case ARMOR_STAY:
        stop(actor);
        s.clip = "appear";
        if (nearestTarget(pos)) {
            std::printf("P2_ARMOR_STATE generator=%u state=appear\n", generator);
            enter(s, ARMOR_APPEAR, "appear");
        }
        break;
    case ARMOR_APPEAR:
        stop(actor);
        if (s.stateTime >= clipDuration("appear")) {
            std::printf("P2_ARMOR_STATE generator=%u state=move\n", generator);
            enter(s, ARMOR_MOVE, "move");
        }
        break;
    case ARMOR_MOVE:
    case ARMOR_GOHOME: {
        Creature* target = nearestTarget(pos);
        // Decomp StateGoHome::exec (ArmorState.cpp:470-473): GoHome attacks a
        // Pikmin inside attack range/angle instead of walking past it, so the
        // attack gate applies in both MOVE and GOHOME; only the walk
        // destination differs (target vs home).
        if (target) {
            // isTargetAttackable / getNearestPikminOrNavi(fp21 15 deg, fp20 75): |angle| <= 15 and XZ < 75.
            if (p2armor::attackable(p2captorhost::vec(pos), s.heading, p2captorhost::vec(target->getPosition()))) {
                std::printf("P2_ARMOR_STATE generator=%u state=attack2\n", generator);
                enter(s, ARMOR_ATTACK2, "attack2");
                break;
            }
        }
        if (s.state == ARMOR_MOVE && target) {
            walkTo(actor, s, target->getPosition(), dt);
        } else {
            walkTo(actor, s, s.home, dt);
        }
        // #1063: source Move/GoHome decisions (ArmorState.cpp:220-274, 461-500). An idle Move (nothing in view)
        // goes GoHome at the move clip's end; GoHome dives once inside the home radius.
        if (s.state == ARMOR_MOVE) {
            const bool clipEnd = s.stateTime >= clipDuration("move");
            const p2armor::Next next = p2armor::moveNext(target != nullptr, false, false, distXZ(pos, s.home), TERRITORY);
            if (next == p2armor::ToGoHome && (target != nullptr || clipEnd)) {
                std::printf("P2_ARMOR_STATE generator=%u state=gohome reason=%s dist_home=%.1f t=%.2f\n", generator,
                            target ? "territory" : "idle", double(distXZ(pos, s.home)), double(s.stateTime));
                enter(s, ARMOR_GOHOME, "move");
                break;
            }
        } else if (p2armor::goHomeNext(false, distXZ(pos, s.home), HOME_RADIUS) == p2armor::ToDive) {
            std::printf("P2_ARMOR_STATE generator=%u state=dive dist_home=%.1f\n", generator, double(distXZ(pos, s.home)));
            enter(s, ARMOR_DIVE, "dive");
            break;
        }
        if (shouldFlick(actor)) {
            std::printf("P2_ARMOR_STATE generator=%u state=flick\n", generator);
            enter(s, ARMOR_FLICK, "flick");
        }
        break;
    }
    case ARMOR_ATTACK2: {
        stop(actor);
        s.events.advance(dt); // attack2's type-2 event is visual here; the bite is the frame window
        {
            // Source StateAttack2::exec runs attackPikmin once per source frame k with 17 < k < 27, with
            // the mouth where the drawn jaw is at that frame (the jaw moves ~60 units a frame on the lunge,
            // so the sampling is part of the behaviour), and attackNavi at the frame-22 key. Every integer
            // frame crossed this tick runs once, so a slow frame cannot skip the bite.
            const int frames = p2armor::clipFrames(p2armor::clipIndex("attack2"));
            const float nowF = clipFrameAt(s, s.stateTime), prevF = clipFrameAt(s, s.stateTime - dt);
            for (int k = int(prevF) + 1; k <= int(nowF) && k < frames; ++k) {
                if (p2armor::inBiteWindow(float(k))) attackPikmin(actor, s, generator, k);
                if (k == 22) attackNavi(actor, s, generator);
            }
        }
        if (s.stateTime >= clipDuration("attack2")) {
            if (holding(actor, s) > 0) {
                std::printf("P2_ARMOR_STATE generator=%u state=eat\n", generator);
                enter(s, ARMOR_EAT, "eat");
            } else {
                std::printf("P2_ARMOR_STATE generator=%u state=fail\n", generator);
                enter(s, ARMOR_FAIL, "attack_fail");
            }
        }
        break;
    }
    case ARMOR_EAT: {
        stop(actor);
        for (const p2armorevents::Dispatched& event : s.events.advance(dt)) {
            if (event.action == p2armorevents::Action::Eat) {
                // Source killSlotPiki: swallowPikmin(proper fp01) on held Pikmin only.
                int white = 0;
                const int killed = p2captorhost::swallow(actor, s.held, mouthGeometry().slots,
                                                         mouthGeometry().poison, &white);
                std::printf("P2_ARMOR_EAT generator=%u pikmin=%d white=%d\n", generator, killed, white);
                std::fflush(stdout);
            }
        }
        if (s.stateTime >= clipDuration("eat")) {
            p2captorhost::release(actor, s.held); // nothing may stay held past Eat
            // inst3-frogs carryability fix (#871): resume homing directly when
            // past TERRITORY instead of spending one MOVE cycle first; the net
            // route matches the decomp (Move goes GoHome when far, :236-238).
            if (distXZ(pos, s.home) > TERRITORY) {
                std::printf("P2_ARMOR_STATE generator=%u state=gohome\n", generator);
                enter(s, ARMOR_GOHOME, "move");
            } else {
                std::printf("P2_ARMOR_STATE generator=%u state=move\n", generator);
                enter(s, ARMOR_MOVE, "move");
            }
        }
        break;
    }
    case ARMOR_FLICK: {
        stop(actor);
        for (const p2armorevents::Dispatched& event : s.events.advance(dt)) {
            if (event.action == p2armorevents::Action::Flick) {
                doFlick(actor, s);
                std::printf("P2_ARMOR_FLICK generator=%u frame=%d\n", generator, event.frame);
                std::fflush(stdout);
            }
        }
        if (s.stateTime >= clipDuration("flick")) {
            // Same homing-preserving completion as EAT above (decomp Flick
            // goes to Move at :739 and Move re-homes when far at :236-238).
            if (distXZ(pos, s.home) > TERRITORY) {
                std::printf("P2_ARMOR_STATE generator=%u state=gohome\n", generator);
                enter(s, ARMOR_GOHOME, "move");
            } else {
                std::printf("P2_ARMOR_STATE generator=%u state=move\n", generator);
                enter(s, ARMOR_MOVE, "move");
            }
        }
        break;
    }
    case ARMOR_FAIL:
        stop(actor);
        if (s.stateTime >= clipDuration("attack_fail")) {
            // Same homing-preserving completion (decomp Fail goes to Move at
            // :702 with the same Move re-homing rule).
            if (distXZ(pos, s.home) > TERRITORY) {
                std::printf("P2_ARMOR_STATE generator=%u state=gohome\n", generator);
                enter(s, ARMOR_GOHOME, "move");
            } else {
                std::printf("P2_ARMOR_STATE generator=%u state=move\n", generator);
                enter(s, ARMOR_MOVE, "move");
            }
        }
        break;
    case ARMOR_DIVE:
        stop(actor);
        if (s.stateTime >= clipDuration("dive")) {
            std::printf("P2_ARMOR_STATE generator=%u state=stay\n", generator);
            enter(s, ARMOR_STAY, "appear");
        }
        break;
    case ARMOR_DEAD:
        stop(actor);
        // Host doAI is suppressed for registered Armor, so dieSoon() never runs
        // there; pcEscapeNow() finalizes the corpse outside doAI, fired exactly
        // once when the dead animation completes (like Frog/Tank/Kabuto).
        if(!s.escaped&&s.stateTime>=clipDuration("dead")){s.escaped=true;actor->pcEscapeNow();}
        break;
    default:
        break;
    }
    setPhase(s);
    updateColl(actor, s);
    pc_p2_skewer_cam_follow(actor, actor->getDirection(), "armor");
    logHold(actor, s, generator);
    logLatch(actor, s, generator);
    s.logTimer += dt;
    if (s.logTimer >= 1.0f) {
        s.logTimer = 0.0f;
        std::printf("P2_ARMOR_POS generator=%u state=%s clip=%s phase=%.2f x=%.2f z=%.2f\n",
                    generator, stateName(s.state), s.clip.c_str(), s.phase, pos.x, pos.z);
        std::fflush(stdout);
    }
}
