#include "pc_p2_original_honey_save.h"
#include <cassert>
#include <iostream>
#include <limits>
using namespace p2originalresource;using namespace p2originalresource::honey;
struct Fake:Engine {unsigned draws=0;bool birth=true;float randFloat()noexcept override{++draws;return .25f;}int randInt(int)noexcept override{return 0;}bool sprayMade(HoneyKind)noexcept override{return true;}bool mititeManagerAvailable()noexcept override{return false;}bool birthPellet(const ChildOutcome&)noexcept override{return false;}bool birthHoney(HoneyKind,const ChildOutcome&)noexcept override{return birth;}bool birthMititeGroup(const ChildOutcome&)noexcept override{return false;}};
int main(){std::string campaign(64,'c'),source(64,'a'),bank(64,'b'),error;std::array<ReceiverClip,7> clips;float durations[]={30,20,8,40,40,60,50};for(unsigned i=0;i<7;++i)clips[i].duration=durations[i];clips[4].loopStart=0;clips[4].loopEnd=39;clips[4].keys={{0,0},{39,1}};
 EggContents contents;Fake engine;P2EggConfig cfg;cfg.forcedDropType=3;ContentsRecord record;SourceIdentity id{source,17,4,0,1};assert(contents.generate(id,cfg,{},engine,record,error));Snapshot row;row.identity=record.children[0].identity;row.position={1.23456789f,-0.0f,3};row.velocity={-25,250,.0000001f};row.phase=Phase::Wait;row.jiggling=true;row.animation="P2OHA1 "+bank+" 4 1 1 0";
 std::string bytes="unchanged";assert(encodeSnapshots({row},campaign,bank,clips,contents,bytes,error));std::vector<Snapshot> restored;unsigned before=engine.draws;assert(decodeSnapshots(bytes,campaign,bank,clips,contents,restored,error));assert(engine.draws==before&&restored.size()==1&&restored[0].jiggling&&restored[0].position.x==row.position.x&&restored[0].velocity.z==row.velocity.z&&restored[0].animation==row.animation);
 std::string again;assert(encodeSnapshots(restored,campaign,bank,clips,contents,again,error)&&again==bytes);
 assert(restored[0].identity.source.fingerprint==source&&source!=campaign);assert(!decodeSnapshots(bytes,source,bank,clips,contents,restored,error));
 auto extreme=row;extreme.position={std::numeric_limits<float>::denorm_min(),std::numeric_limits<float>::max(),-0.0f};extreme.velocity={-std::numeric_limits<float>::denorm_min(),-std::numeric_limits<float>::max(),0.0f};std::string edge;
 assert(encodeSnapshots({extreme},campaign,bank,clips,contents,edge,error));std::vector<Snapshot> edgeRows;assert(decodeSnapshots(edge,campaign,bank,clips,contents,edgeRows,error));assert(edgeRows[0].position.x==extreme.position.x&&edgeRows[0].position.y==extreme.position.y&&std::signbit(edgeRows[0].position.z)&&edgeRows[0].velocity.x==extreme.velocity.x&&edgeRows[0].velocity.y==extreme.velocity.y&&!std::signbit(edgeRows[0].velocity.z));
 auto invalid=row;invalid.kind=HoneyKind::Spicy;again="unchanged";assert(!encodeSnapshots({invalid},campaign,bank,clips,contents,again,error)&&again=="unchanged");assert(!encodeSnapshots({},campaign,bank,clips,contents,again,error));
 invalid=row;invalid.animation="P2OHA1 "+bank+" 4 1 0 0";assert(!encodeSnapshots({invalid},campaign,bank,clips,contents,again,error));assert(!encodeSnapshots({row,row},campaign,bank,clips,contents,again,error));
 restored={row};assert(!decodeSnapshots(bytes+" garbage",campaign,bank,clips,contents,restored,error)&&restored.size()==1&&restored[0].jiggling);assert(!decodeSnapshots(std::string(1048577,'x'),campaign,bank,clips,contents,restored,error));assert(!decodeSnapshots(bytes,campaign,std::string(64,'c'),clips,contents,restored,error));
 std::string malformed=bytes;auto at=malformed.find("17 4 0 1");assert(at!=std::string::npos);malformed.replace(at,2,"017");assert(!decodeSnapshots(malformed,campaign,bank,clips,contents,restored,error));
 assert(contents.consume(row.identity,error));row.firstConsumption=true;row.phase=Phase::Shrink;row.animation="P2OHA1 "+bank+" 6 10 0 0";assert(encodeSnapshots({row},campaign,bank,clips,contents,bytes,error));assert(decodeSnapshots(bytes,campaign,bank,clips,contents,restored,error)&&restored[0].firstConsumption);row.phase=Phase::Dead;assert(!encodeSnapshots({row},campaign,bank,clips,contents,again,error));row.animation.clear();assert(encodeSnapshots({row},campaign,bank,clips,contents,bytes,error));assert(decodeSnapshots(bytes,campaign,bank,clips,contents,restored,error)&&restored[0].phase==Phase::Dead);
 std::vector<Snapshot> huge(4097,row);assert(!encodeSnapshots(huge,campaign,bank,clips,contents,again,error));
 EggContents crowded;std::vector<Snapshot> live;for(unsigned i=0;i<25;++i){id.ordinal=i;assert(crowded.generate(id,cfg,{},engine,record,error));Snapshot s;s.identity=record.children[0].identity;s.animation="P2OHA1 "+bank+" 0 0 0 0";live.push_back(s);}assert(!encodeSnapshots(live,campaign,bank,clips,crowded,again,error));
 invalid=restored[0];invalid.position.x=std::numeric_limits<float>::infinity();assert(!encodeSnapshots({invalid},campaign,bank,clips,contents,again,error));
 std::cout<<"P2_ORIGINAL_HONEY_SAVE_PASS\n";
}
