#pragma once
// #892 Gatling Groink (MiniHoudai 78 / FminiHoudai 97) collision policy. Engine-free.
//
// Source: the retail minihoudai/enemycoll.txt tree (pc_p2_groink_coll_tables.h,
// generated by scripts/p2_groink_coll_tables.py). Exactly one part is stickable:
//   body                    st__   (joint kosi)
// every other part is touch-only (`_t__`):
//   asiL asiR (feet)  cov1 cov2 cov3 (head joint: the front armour cover)  coll
// CollPart::isStickable matches the code against `s***` (collinfo.cpp:806-809), and a
// thrown Pikmin that lands on a non-stickable teki part does not latch: it gets the
// instick puff instead of startStick (PikiFlyingState::collisionCallback,
// pikiState.cpp:2336-2345; ActAttack::collisionCallback, aiAttack.cpp:285-290). Since
// damage from a Pikmin only ever arrives through the part it is stuck to
// (InteractAttack carries mCollPart), a Pikmin cannot hurt a Groink through the face
// cover: it bounces off. MiniHoudai::Obj::damageCallBack (MiniHoudai.cpp:162-171)
// applies full damage when the attacker supplies a part and a quarter when it does not.
// The captain's punch always supplies the part it touched (naviState.cpp:1590-1640),
// so the punch is NOT blocked on the cover.

#include "pc_p2_groink_coll_tables.h"

#include <cmath>
#include <cstring>

namespace p2groinkcoll {

// CollPart::isStickable for a non-platform sphere: the code's first character is 's'.
inline bool codeStickable(const char* code) { return code && code[0] == 's'; }

inline int nodeIndex(const char* id)
{
    for (int i = 0; i < kCollNodeCount; ++i)
        if (!std::strncmp(kCollNodes[i].id, id, 4)) return i;
    return -1;
}

inline bool stickable(int node) { return node >= 0 && node < kCollNodeCount && codeStickable(kCollNodes[node].code); }

// The head-joint spheres of the front armour cover.
inline bool frontCover(int node)
{
    return node >= 0 && node < kCollNodeCount && !std::strncmp(kCollNodes[node].id, "cov", 3);
}

enum class Contact { Latch, Bounce };
// What a thrown or jumping Pikmin does on touching `node`.
inline Contact contact(int node) { return stickable(node) ? Contact::Latch : Contact::Bounce; }

// MiniHoudai::Obj::damageCallBack: full with a part, a quarter without.
inline float damageScale(bool hasPart) { return hasPart ? 1.0f : 0.25f; }

// Damage a Pikmin attack deals through the part it is stuck to. A Pikmin can only be
// stuck to a stickable part; a non-stickable part is refused outright (defence in depth
// for a host that reports a stuck Pikmin on a touch-only part).
inline float pikminDamage(int node, float damage) { return stickable(node) ? damage * damageScale(true) : 0.0f; }

// Pikmin-origin InteractAttack verdict. P2's only such source is ActStickAttack with the part the
// Pikmin is stuck to (aiPrimitives.cpp:3920); P1's unlatched ground melee (aiAttack.cpp:695) sends
// no part and has no P2 counterpart. `stickNode` is the tree node the Pikmin is stuck to, or -1.
enum class PikminHit { Accept, RefuseUnlatched, RefuseNonStickable };
inline PikminHit pikminHit(bool stuck, int stickNode)
{
    if (!stuck) return PikminHit::RefuseUnlatched;
    return stickable(stickNode) ? PikminHit::Accept : PikminHit::RefuseNonStickable;
}

inline int clipIndex(const char* stem)
{
    for (int i = 0; i < kCollClipCount; ++i)
        if (!std::strcmp(kCollClips[i].stem, stem)) return i;
    return -1;
}

// AnimID order of MiniHoudai.h == table clip order.
inline int clipForAnim(int anim) { return anim >= 0 && anim < kCollClipCount ? anim : 0; }

// Model-space centre of `node` at clip frame `frame` (linear between samples).
inline bool centre(int clip, float frame, int node, float out[3])
{
    if (clip < 0 || clip >= kCollClipCount || node < 0 || node >= kCollNodeCount) return false;
    const float last = float(kCollClips[clip].frames > 1 ? kCollClips[clip].frames - 1 : 1);
    const float u = !(frame > 0.0f) ? 0.0f : (frame >= last ? 1.0f : frame / last);
    const float t = u * float(kCollSamples - 1);
    int i0 = int(t);
    if (i0 >= kCollSamples - 1) i0 = kCollSamples - 2;
    const float f = t - float(i0);
    const float* a = kCollClips[clip].centre[i0][node];
    const float* b = kCollClips[clip].centre[i0 + 1][node];
    for (int k = 0; k < 3; ++k) out[k] = a[k] + (b[k] - a[k]) * f;
    return true;
}

// world = actor + R_y(heading) * local; +z is the facing direction (same rotation as
// the FSM's muzzle: pc_p2_groink_fsm.cpp rotY).
inline void toWorld(const float pos[3], float heading, const float local[3], float out[3])
{
    const float s = std::sin(heading), c = std::cos(heading);
    out[0] = pos[0] + local[0] * c + local[2] * s;
    out[1] = pos[1] + local[1];
    out[2] = pos[2] - local[0] * s + local[2] * c;
}

} // namespace p2groinkcoll
