#pragma once
class BTeki;
class Creature;

// Family-owned aquatic source behavior for the batch-3 Chappy placement
// vehicle: the shared UmiMushi::Mgr FSM for the Ranging Bloyster (EnemyID 71)
// and the Toady/Blind Bloyster (EnemyID 101) on the P1 TEKI_Chappy (3) host
// (#167/#374/#407). Both source IDs run the same FSM
// (UmiMushiState.cpp, registered at umiMushiState.cpp:18): Wait 0 -> Walk 1 ->
// Find 2 -> Search 3 -> Turn 4 -> Flick 5 -> Attack 6 -> Eat 7, Dead 8,
// Lost 9. Obj::onInit starts the FSM in Walk (umiMushi.cpp:141). Attack marks
// the tongue active at animation key event 3, eats Pikmin while active, then
// enters Eat and swallows (EnemyFunc::swallowPikmin) at the Eat animation end.
// Source revision 632af93787b9c95b63f0c13be32b161375ce3a96; retail parms from
// experimental/pikmin2_aquatic_assets.py (GPVE01 rev 0, UmiMushi DISC_PARMS).
//
// TONGUE AND COLLISION (#995, source-faithful): the seven mouth slots follow the real
// kamu_joint1..7 world positions of the attack1/eat1 clips (tables generated by
// scripts/p2_umimushi_tables.py into pc_p2_umimushi_tables.h) on an own collision tree
// (pc_p2_umimushi_policy.h): root r180 / head r80 / kuti r40 / ketu r25 unstickable and the
// `weak` tail bulb (r10 x 1.4, `st__`) as the only part a Pikmin can latch onto, plus a 'slot'
// mouth part with seven kam children that hold swallowed Pikmin on the tongue through the eat
// animation until the source swallow. Damage follows Obj::damageCallBack (stuck attacker on a part,
// or a low partless hit at proper fp01 = 0.03).
//
// BLIND (101) SHARED-BASE SPLIT (implemented): the actors config binds a
// source-101 actor with the `UmiMushiBlind` species. It reuses the shared FSM
// with the source Blind parameters: half scale (mSRT.s 0.5), proper fp12=800
// health, Parms::mBlindTurnRateReduction 0.3 scaling turnFunc's rotate speed
// and max, isChangeNavi false (no Navi retargeting) and the Walk move/wait
// frame cycle (fp14 move 200 / fp13 wait 200). Its sampled visual bank is the
// converted UmiMushi bank used as an explicit stand-in: the source import
// manifest has no converted Blind actor/model (no fabricated provenance).
//
// BOUNDED GAPS (recorded, not retail-faithful): no P2 water box (mWaterBox /
// Hamon sea height / dive/splash presentation), no UmiMushi::Mgr base (100)
// direct-spawn exclusion, no mid-boss BGM phase staging, and no eye/weak joint
// callbacks or material texture animation (umimusi_model1.btk). Target
// selection is a single active Navi; the two-player nearest-Navi branch, the
// source view-angle gate and the mouth-slot geometry test are port adaptations.
//
// Every hook is a no-op for unregistered actors; no other lane's module is
// modified.
void pc_p2_umimushi_setup();
void pc_p2_umimushi_reset();
void pc_p2_umimushi_forget(BTeki*);
// Death-/birth-time Piki forget hook (#886): drop a held-mouth registration
// for a Pikmin that died or whose pool slot is being reused.
void pc_p2_umimushi_forget_piki(class Piki*);
void pc_p2_umimushi_update(BTeki*);
bool pc_p2_umimushi_suppress_ai(const BTeki*);
// Engine-free suppression predicate shared by pc_p2_umimushi_suppress_ai
// and the focused gate test. The P2 FSM drives movement/targeting/attacks
// every tick for a registered bloyster (ordinary 71 or Blind 101), so the
// P1 Chappy host strategy (BTeki::doAI) must not run for it; unregistered
// actors are unaffected. Mirrors pc_p2_frog_suppress_ai.
inline bool pc_p2_umimushi_suppressed(bool registered) {
    return registered;
}
float pc_p2_umimushi_param_f(const BTeki*, int idx, float fallback);
bool pc_p2_umimushi_clip(const BTeki*, const char*& name, float& phase);
bool pc_p2_umimushi_receipt(class PelletView*, unsigned&);
// #995: source Obj::damageCallBack. < 0 = not a registered live Bloyster (host path), 0 = refused,
// otherwise the damage multiplier. pc_p2_umimushi_attacked adds the addDamage flickSpeed (1.0) for an
// accepted hit.
float pc_p2_umimushi_damage_rate(BTeki*, Creature* owner, class CollPart* part);
void pc_p2_umimushi_attacked(BTeki*, bool accepted);
// #995: lock-on aim. For a registered live Bloyster returns true and the XZ offset (from the captain) the
// throw cursor should be pinned at so a thrown Pikmin crosses the tail bulb; false for every other target.
// throwHeight/gravity/halfTime are the captain's current throw parameters.
bool pc_p2_umimushi_lock_aim(Creature* target, float naviX, float naviZ, float throwHeight, float gravity,
                             float halfTime, float& offsetX, float& offsetZ);
int pc_p2_umimushi_bound_count();
