static const char* const randomizerModernCollectionNames[] = {
    "Pikmin: Bowsprit",
    "Pikmin: Gluon Drive",
    "Pikmin: Anti-Dioxin Filter",
    "Pikmin: Eternal Fuel Dynamo",
    "Pikmin: Whimsical Radar",
    "Pikmin: Interstellar Radio",
    "Pikmin: Guard Satellite",
    "Pikmin: Chronos Reactor",
    "Pikmin: Radiation Canopy",
    "Pikmin: Geiger Counter",
    "Pikmin: Sagittarius",
    "Pikmin: Libra",
    "Pikmin: Omega Stabilizer",
    "Pikmin: Ionium Jet 1",
    "Pikmin: Ionium Jet 2",
    "Pikmin: Shock Absorber",
    "Pikmin: Gravity Jumper",
    "Pikmin: Pilot's Seat",
    "Pikmin: Nova Blaster",
    "Pikmin: Automatic Gear",
    "Pikmin: Zirconium Rotor",
    "Pikmin: Extraordinary Bolt",
    "Pikmin: Repair-type Bolt",
    "Pikmin: Space Float",
    "Pikmin: Massage Machine",
    "Pikmin: Secret Safe",
    "Pikmin: Analog Computer",
    "Pikmin: UV Lamp",
    "Pikmin: Yellow Onion Discovery",
    "Pikmin: Blue Onion Discovery",
    "Population: 20 total Pikmin",
    "Population: 40 total Pikmin",
    "Population: 60 total Pikmin",
    "Population: 80 total Pikmin",
    "Population: 100 total Pikmin",
    "Population: 150 total Pikmin",
    "Population: 200 total Pikmin",
    "Population: 300 total Pikmin",
    "Population: 500 total Pikmin",
    "Bestiary: Deliver Dwarf Bulborb",
    "Bestiary: Deliver Spotty Bulborb",
    "Bestiary: Deliver Female Sheargrub",
    "Bestiary: Deliver Male Sheargrub",
    "Bestiary: Deliver Shearwig",
    "Bestiary: Deliver Fiery Blowhog",
    "Bestiary: Deliver Water Dumple",
    "Bestiary: Deliver Wollywog",
    "Explore: The Forest of Hope - Land",
    "Explore: The Forest Navel - Land",
    "Explore: The Distant Spring - Land",
    "Explore: The Final Trial - Land",
    "Explore: The Impact Site - Land",
    "Pikmin: Positron Generator",
    "Bestiary: Deliver Dwarf Bulbear",
    "Bestiary: Deliver Wogpole",
    "Bestiary: Deliver Spotty Bulbear",
    "Bestiary: Deliver Yellow Wollywog",
    "Bestiary: Defeat Puffy Blowhog",
    "Bestiary: Deliver Swooping Snitchbug",
    "Bestiary: Deliver Breadbug",
    "Bestiary: Deliver Puffstool",
    "Bestiary: Deliver Armored Cannon Beetle",
    "Bestiary: Deliver Pearly Clamclamp Pearl",
    "Bestiary: Deliver Mamuta",
};
static const char* const randomizerModernPermanentNames[] = {
    "Pikmin: Bowsprit",
    "Pikmin: Gluon Drive",
    "Pikmin: Anti-Dioxin Filter",
    "Pikmin: Eternal Fuel Dynamo",
    "Pikmin: Whimsical Radar",
    "Pikmin: Interstellar Radio",
    "Pikmin: Guard Satellite",
    "Pikmin: Chronos Reactor",
    "Pikmin: Radiation Canopy",
    "Pikmin: Geiger Counter",
    "Pikmin: Sagittarius",
    "Pikmin: Libra",
    "Pikmin: Omega Stabilizer",
    "Pikmin: Ionium Jet 1",
    "Pikmin: Ionium Jet 2",
    "Pikmin: Shock Absorber",
    "Pikmin: Gravity Jumper",
    "Pikmin: Pilot's Seat",
    "Pikmin: Nova Blaster",
    "Pikmin: Automatic Gear",
    "Pikmin: Zirconium Rotor",
    "Pikmin: Extraordinary Bolt",
    "Pikmin: Repair-type Bolt",
    "Pikmin: Space Float",
    "Pikmin: Massage Machine",
    "Pikmin: Secret Safe",
    "Pikmin: Analog Computer",
    "Pikmin: UV Lamp",
    "Pikmin: Yellow Onion Discovery",
    "Pikmin: Blue Onion Discovery",
    "Population: 20 total Pikmin",
    "Population: 40 total Pikmin",
    "Population: 60 total Pikmin",
    "Population: 80 total Pikmin",
    "Population: 100 total Pikmin",
    "Population: 150 total Pikmin",
    "Population: 200 total Pikmin",
    "Population: 300 total Pikmin",
    "Population: 500 total Pikmin",
    "Bestiary: Deliver Dwarf Bulborb",
    "Bestiary: Deliver Spotty Bulborb",
    "Bestiary: Deliver Female Sheargrub",
    "Bestiary: Deliver Male Sheargrub",
    "Bestiary: Deliver Shearwig",
    "Bestiary: Deliver Fiery Blowhog",
    "Bestiary: Deliver Water Dumple",
    "Bestiary: Deliver Wollywog",
    "Explore: The Forest of Hope - Land",
    "Explore: The Forest Navel - Land",
    "Explore: The Distant Spring - Land",
    "Explore: The Final Trial - Land",
    "Explore: The Impact Site - Land",
    "Pikmin: Positron Generator",
    "Bestiary: Deliver Dwarf Bulbear",
    "Bestiary: Deliver Wogpole",
    "Bestiary: Deliver Spotty Bulbear",
    "Bestiary: Deliver Yellow Wollywog",
    "Bestiary: Defeat Puffy Blowhog",
    "Bestiary: Deliver Swooping Snitchbug",
    "Bestiary: Deliver Breadbug",
    "Bestiary: Deliver Puffstool",
    "Bestiary: Deliver Armored Cannon Beetle",
    "Bestiary: Deliver Pearly Clamclamp Pearl",
    "Bestiary: Deliver Mamuta",
    "Population: 30 total Pikmin",
    "Population: 50 total Pikmin",
    "Population: 70 total Pikmin",
    "Population: 90 total Pikmin",
    "Population: 125 total Pikmin",
    "Population: 175 total Pikmin",
    "Population: 250 total Pikmin",
    "Population: 350 total Pikmin",
    "Population: 400 total Pikmin",
    "Population: 450 total Pikmin",
    "Build: The Impact Site - Dirt Wall 01",
    "Build: The Impact Site - Bomb Wall 01",
    "Build: The Impact Site - Climbing Stick 01",
    "Build: The Impact Site - Pushable Box 01",
    "Build: The Forest of Hope - Dirt Wall 01",
    "Build: The Forest of Hope - Dirt Wall 02",
    "Build: The Forest of Hope - Dirt Wall 03",
    "Build: The Forest of Hope - Reinforced Dirt Wall 01",
    "Build: The Forest of Hope - Reinforced Dirt Wall 02",
    "Build: The Forest of Hope - Bomb Wall 01",
    "Build: The Forest of Hope - Bomb Wall 02",
    "Build: The Forest of Hope - Bomb Wall 03",
    "Build: The Forest of Hope - Reinforced Bomb Wall 01",
    "Build: The Forest of Hope - Bridge 01",
    "Build: The Forest of Hope - Bridge 02",
    "Build: The Forest of Hope - Pushable Box 01",
    "Build: The Forest Navel - Dirt Wall 01",
    "Build: The Forest Navel - Reinforced Dirt Wall 01",
    "Build: The Forest Navel - Reinforced Dirt Wall 02",
    "Build: The Forest Navel - Bomb Wall 01",
    "Build: The Forest Navel - Bomb Wall 02",
    "Build: The Forest Navel - Bomb Wall 03",
    "Build: The Forest Navel - Reinforced Bomb Wall 01",
    "Build: The Forest Navel - Reinforced Bomb Wall 02",
    "Build: The Forest Navel - Climbing Stick 01",
    "Build: The Forest Navel - Climbing Stick 02",
    "Build: The Forest Navel - Climbing Stick 03",
    "Build: The Forest Navel - Climbing Stick 04",
    "Build: The Forest Navel - Bridge 01",
    "Build: The Forest Navel - Bridge 02",
    "Build: The Forest Navel - Bridge 03",
    "Build: The Forest Navel - Bridge 04",
    "Build: The Forest Navel - Bridge 05",
    "Build: The Distant Spring - Dirt Wall 01",
    "Build: The Distant Spring - Dirt Wall 02",
    "Build: The Distant Spring - Reinforced Dirt Wall 01",
    "Build: The Distant Spring - Bomb Wall 01",
    "Build: The Distant Spring - Reinforced Bomb Wall 01",
    "Build: The Distant Spring - Climbing Stick 01",
    "Build: The Distant Spring - Climbing Stick 02",
    "Build: The Distant Spring - Climbing Stick 03",
    "Build: The Distant Spring - Bridge 01",
    "Build: The Distant Spring - Bridge 02",
    "Build: The Distant Spring - Bridge 03",
    "Build: The Distant Spring - Bridge 04",
    "Build: The Final Trial - Dirt Wall 01",
    "Build: The Final Trial - Dirt Wall 02",
    "Build: The Final Trial - Bomb Wall 01",
    "Build: The Final Trial - Bridge 01",
    "Build: The Final Trial - Bridge 02",
    "Build: The Final Trial - Pushable Box 01",
};
static const char* const randomizerNoExploreCollectionNames[] = {
    "Pikmin: Bowsprit",
    "Pikmin: Gluon Drive",
    "Pikmin: Anti-Dioxin Filter",
    "Pikmin: Eternal Fuel Dynamo",
    "Pikmin: Whimsical Radar",
    "Pikmin: Interstellar Radio",
    "Pikmin: Guard Satellite",
    "Pikmin: Chronos Reactor",
    "Pikmin: Radiation Canopy",
    "Pikmin: Geiger Counter",
    "Pikmin: Sagittarius",
    "Pikmin: Libra",
    "Pikmin: Omega Stabilizer",
    "Pikmin: Ionium Jet 1",
    "Pikmin: Ionium Jet 2",
    "Pikmin: Shock Absorber",
    "Pikmin: Gravity Jumper",
    "Pikmin: Pilot's Seat",
    "Pikmin: Nova Blaster",
    "Pikmin: Automatic Gear",
    "Pikmin: Zirconium Rotor",
    "Pikmin: Extraordinary Bolt",
    "Pikmin: Repair-type Bolt",
    "Pikmin: Space Float",
    "Pikmin: Massage Machine",
    "Pikmin: Secret Safe",
    "Pikmin: Analog Computer",
    "Pikmin: UV Lamp",
    "Pikmin: Yellow Onion Discovery",
    "Pikmin: Blue Onion Discovery",
    "Population: 20 total Pikmin",
    "Population: 40 total Pikmin",
    "Population: 60 total Pikmin",
    "Population: 80 total Pikmin",
    "Population: 100 total Pikmin",
    "Population: 150 total Pikmin",
    "Population: 200 total Pikmin",
    "Population: 300 total Pikmin",
    "Population: 500 total Pikmin",
    "Bestiary: Deliver Dwarf Bulborb",
    "Bestiary: Deliver Spotty Bulborb",
    "Bestiary: Deliver Female Sheargrub",
    "Bestiary: Deliver Male Sheargrub",
    "Bestiary: Deliver Shearwig",
    "Bestiary: Deliver Fiery Blowhog",
    "Bestiary: Deliver Water Dumple",
    "Bestiary: Deliver Wollywog",
    "Pikmin: Positron Generator",
    "Bestiary: Deliver Dwarf Bulbear",
    "Bestiary: Deliver Wogpole",
    "Bestiary: Deliver Spotty Bulbear",
    "Bestiary: Deliver Yellow Wollywog",
    "Bestiary: Defeat Puffy Blowhog",
    "Bestiary: Deliver Swooping Snitchbug",
    "Bestiary: Deliver Breadbug",
    "Bestiary: Deliver Puffstool",
    "Bestiary: Deliver Armored Cannon Beetle",
    "Bestiary: Deliver Pearly Clamclamp Pearl",
    "Bestiary: Deliver Mamuta",
};
static const char* const randomizerNoExplorePermanentNames[] = {
    "Pikmin: Bowsprit",
    "Pikmin: Gluon Drive",
    "Pikmin: Anti-Dioxin Filter",
    "Pikmin: Eternal Fuel Dynamo",
    "Pikmin: Whimsical Radar",
    "Pikmin: Interstellar Radio",
    "Pikmin: Guard Satellite",
    "Pikmin: Chronos Reactor",
    "Pikmin: Radiation Canopy",
    "Pikmin: Geiger Counter",
    "Pikmin: Sagittarius",
    "Pikmin: Libra",
    "Pikmin: Omega Stabilizer",
    "Pikmin: Ionium Jet 1",
    "Pikmin: Ionium Jet 2",
    "Pikmin: Shock Absorber",
    "Pikmin: Gravity Jumper",
    "Pikmin: Pilot's Seat",
    "Pikmin: Nova Blaster",
    "Pikmin: Automatic Gear",
    "Pikmin: Zirconium Rotor",
    "Pikmin: Extraordinary Bolt",
    "Pikmin: Repair-type Bolt",
    "Pikmin: Space Float",
    "Pikmin: Massage Machine",
    "Pikmin: Secret Safe",
    "Pikmin: Analog Computer",
    "Pikmin: UV Lamp",
    "Pikmin: Yellow Onion Discovery",
    "Pikmin: Blue Onion Discovery",
    "Population: 20 total Pikmin",
    "Population: 40 total Pikmin",
    "Population: 60 total Pikmin",
    "Population: 80 total Pikmin",
    "Population: 100 total Pikmin",
    "Population: 150 total Pikmin",
    "Population: 200 total Pikmin",
    "Population: 300 total Pikmin",
    "Population: 500 total Pikmin",
    "Bestiary: Deliver Dwarf Bulborb",
    "Bestiary: Deliver Spotty Bulborb",
    "Bestiary: Deliver Female Sheargrub",
    "Bestiary: Deliver Male Sheargrub",
    "Bestiary: Deliver Shearwig",
    "Bestiary: Deliver Fiery Blowhog",
    "Bestiary: Deliver Water Dumple",
    "Bestiary: Deliver Wollywog",
    "Pikmin: Positron Generator",
    "Bestiary: Deliver Dwarf Bulbear",
    "Bestiary: Deliver Wogpole",
    "Bestiary: Deliver Spotty Bulbear",
    "Bestiary: Deliver Yellow Wollywog",
    "Bestiary: Defeat Puffy Blowhog",
    "Bestiary: Deliver Swooping Snitchbug",
    "Bestiary: Deliver Breadbug",
    "Bestiary: Deliver Puffstool",
    "Bestiary: Deliver Armored Cannon Beetle",
    "Bestiary: Deliver Pearly Clamclamp Pearl",
    "Bestiary: Deliver Mamuta",
    "Population: 30 total Pikmin",
    "Population: 50 total Pikmin",
    "Population: 70 total Pikmin",
    "Population: 90 total Pikmin",
    "Population: 125 total Pikmin",
    "Population: 175 total Pikmin",
    "Population: 250 total Pikmin",
    "Population: 350 total Pikmin",
    "Population: 400 total Pikmin",
    "Population: 450 total Pikmin",
    "Build: The Impact Site - Dirt Wall 01",
    "Build: The Impact Site - Bomb Wall 01",
    "Build: The Impact Site - Climbing Stick 01",
    "Build: The Impact Site - Pushable Box 01",
    "Build: The Forest of Hope - Dirt Wall 01",
    "Build: The Forest of Hope - Dirt Wall 02",
    "Build: The Forest of Hope - Dirt Wall 03",
    "Build: The Forest of Hope - Reinforced Dirt Wall 01",
    "Build: The Forest of Hope - Reinforced Dirt Wall 02",
    "Build: The Forest of Hope - Bomb Wall 01",
    "Build: The Forest of Hope - Bomb Wall 02",
    "Build: The Forest of Hope - Bomb Wall 03",
    "Build: The Forest of Hope - Reinforced Bomb Wall 01",
    "Build: The Forest of Hope - Bridge 01",
    "Build: The Forest of Hope - Bridge 02",
    "Build: The Forest of Hope - Pushable Box 01",
    "Build: The Forest Navel - Dirt Wall 01",
    "Build: The Forest Navel - Reinforced Dirt Wall 01",
    "Build: The Forest Navel - Reinforced Dirt Wall 02",
    "Build: The Forest Navel - Bomb Wall 01",
    "Build: The Forest Navel - Bomb Wall 02",
    "Build: The Forest Navel - Bomb Wall 03",
    "Build: The Forest Navel - Reinforced Bomb Wall 01",
    "Build: The Forest Navel - Reinforced Bomb Wall 02",
    "Build: The Forest Navel - Climbing Stick 01",
    "Build: The Forest Navel - Climbing Stick 02",
    "Build: The Forest Navel - Climbing Stick 03",
    "Build: The Forest Navel - Climbing Stick 04",
    "Build: The Forest Navel - Bridge 01",
    "Build: The Forest Navel - Bridge 02",
    "Build: The Forest Navel - Bridge 03",
    "Build: The Forest Navel - Bridge 04",
    "Build: The Forest Navel - Bridge 05",
    "Build: The Distant Spring - Dirt Wall 01",
    "Build: The Distant Spring - Dirt Wall 02",
    "Build: The Distant Spring - Reinforced Dirt Wall 01",
    "Build: The Distant Spring - Bomb Wall 01",
    "Build: The Distant Spring - Reinforced Bomb Wall 01",
    "Build: The Distant Spring - Climbing Stick 01",
    "Build: The Distant Spring - Climbing Stick 02",
    "Build: The Distant Spring - Climbing Stick 03",
    "Build: The Distant Spring - Bridge 01",
    "Build: The Distant Spring - Bridge 02",
    "Build: The Distant Spring - Bridge 03",
    "Build: The Distant Spring - Bridge 04",
    "Build: The Final Trial - Dirt Wall 01",
    "Build: The Final Trial - Dirt Wall 02",
    "Build: The Final Trial - Bomb Wall 01",
    "Build: The Final Trial - Bridge 01",
    "Build: The Final Trial - Bridge 02",
    "Build: The Final Trial - Pushable Box 01",
};
struct RandomizerBestiary { const char* name; int type; };
static const RandomizerBestiary randomizerNewBestiary[] = {
    {"Bestiary: Deliver Dwarf Bulbear", 31},
    {"Bestiary: Deliver Wogpole", 25},
    {"Bestiary: Deliver Spotty Bulbear", 32},
    {"Bestiary: Deliver Yellow Wollywog", 0},
    {"Bestiary: Defeat Puffy Blowhog", 16},
    {"Bestiary: Deliver Swooping Snitchbug", 11},
    {"Bestiary: Deliver Breadbug", 8},
    {"Bestiary: Deliver Puffstool", 9},
    {"Bestiary: Deliver Armored Cannon Beetle", 17},
    {"Bestiary: Deliver Pearly Clamclamp Pearl", 13},
    {"Bestiary: Deliver Mamuta", 24},
};
static const char* const randomizerPermanentNames[] = {
    "Pikmin: Bowsprit",
    "Pikmin: Gluon Drive",
    "Pikmin: Anti-Dioxin Filter",
    "Pikmin: Eternal Fuel Dynamo",
    "Pikmin: Whimsical Radar",
    "Pikmin: Interstellar Radio",
    "Pikmin: Guard Satellite",
    "Pikmin: Chronos Reactor",
    "Pikmin: Radiation Canopy",
    "Pikmin: Geiger Counter",
    "Pikmin: Sagittarius",
    "Pikmin: Libra",
    "Pikmin: Omega Stabilizer",
    "Pikmin: Ionium Jet 1",
    "Pikmin: Ionium Jet 2",
    "Pikmin: Shock Absorber",
    "Pikmin: Gravity Jumper",
    "Pikmin: Pilot's Seat",
    "Pikmin: Nova Blaster",
    "Pikmin: Automatic Gear",
    "Pikmin: Zirconium Rotor",
    "Pikmin: Extraordinary Bolt",
    "Pikmin: Repair-type Bolt",
    "Pikmin: Space Float",
    "Pikmin: Massage Machine",
    "Pikmin: Secret Safe",
    "Pikmin: Analog Computer",
    "Pikmin: UV Lamp",
    "Pikmin: Yellow Onion Discovery",
    "Pikmin: Blue Onion Discovery",
    "Population: 20 total Pikmin",
    "Population: 40 total Pikmin",
    "Population: 60 total Pikmin",
    "Population: 80 total Pikmin",
    "Population: 100 total Pikmin",
    "Population: 150 total Pikmin",
    "Population: 200 total Pikmin",
    "Population: 300 total Pikmin",
    "Population: 500 total Pikmin",
    "Bestiary: Deliver Dwarf Bulborb",
    "Bestiary: Deliver Spotty Bulborb",
    "Bestiary: Deliver Female Sheargrub",
    "Bestiary: Deliver Male Sheargrub",
    "Bestiary: Deliver Shearwig",
    "Bestiary: Deliver Fiery Blowhog",
    "Bestiary: Deliver Water Dumple",
    "Bestiary: Deliver Wollywog",
    "Explore: The Forest of Hope - Land",
    "Explore: The Forest of Hope - Scout",
    "Explore: The Forest Navel - Land",
    "Explore: The Forest Navel - Scout",
    "Explore: The Distant Spring - Land",
    "Explore: The Distant Spring - Scout",
    "Explore: The Final Trial - Land",
    "Explore: The Final Trial - Scout",
    "Explore: The Impact Site - Land",
    "Explore: The Impact Site - Scout",
    "Pikmin: Positron Generator",
    "Population: 30 total Pikmin",
    "Population: 50 total Pikmin",
    "Population: 70 total Pikmin",
    "Population: 90 total Pikmin",
    "Population: 125 total Pikmin",
    "Population: 175 total Pikmin",
    "Population: 250 total Pikmin",
    "Population: 350 total Pikmin",
    "Population: 400 total Pikmin",
    "Population: 450 total Pikmin",
    "Build: The Impact Site - Dirt Wall 01",
    "Build: The Impact Site - Bomb Wall 01",
    "Build: The Impact Site - Climbing Stick 01",
    "Build: The Impact Site - Pushable Box 01",
    "Build: The Forest of Hope - Dirt Wall 01",
    "Build: The Forest of Hope - Dirt Wall 02",
    "Build: The Forest of Hope - Dirt Wall 03",
    "Build: The Forest of Hope - Reinforced Dirt Wall 01",
    "Build: The Forest of Hope - Reinforced Dirt Wall 02",
    "Build: The Forest of Hope - Bomb Wall 01",
    "Build: The Forest of Hope - Bomb Wall 02",
    "Build: The Forest of Hope - Bomb Wall 03",
    "Build: The Forest of Hope - Reinforced Bomb Wall 01",
    "Build: The Forest of Hope - Bridge 01",
    "Build: The Forest of Hope - Bridge 02",
    "Build: The Forest of Hope - Pushable Box 01",
    "Build: The Forest Navel - Dirt Wall 01",
    "Build: The Forest Navel - Reinforced Dirt Wall 01",
    "Build: The Forest Navel - Reinforced Dirt Wall 02",
    "Build: The Forest Navel - Bomb Wall 01",
    "Build: The Forest Navel - Bomb Wall 02",
    "Build: The Forest Navel - Bomb Wall 03",
    "Build: The Forest Navel - Reinforced Bomb Wall 01",
    "Build: The Forest Navel - Reinforced Bomb Wall 02",
    "Build: The Forest Navel - Climbing Stick 01",
    "Build: The Forest Navel - Climbing Stick 02",
    "Build: The Forest Navel - Climbing Stick 03",
    "Build: The Forest Navel - Climbing Stick 04",
    "Build: The Forest Navel - Bridge 01",
    "Build: The Forest Navel - Bridge 02",
    "Build: The Forest Navel - Bridge 03",
    "Build: The Forest Navel - Bridge 04",
    "Build: The Forest Navel - Bridge 05",
    "Build: The Distant Spring - Dirt Wall 01",
    "Build: The Distant Spring - Dirt Wall 02",
    "Build: The Distant Spring - Reinforced Dirt Wall 01",
    "Build: The Distant Spring - Bomb Wall 01",
    "Build: The Distant Spring - Reinforced Bomb Wall 01",
    "Build: The Distant Spring - Climbing Stick 01",
    "Build: The Distant Spring - Climbing Stick 02",
    "Build: The Distant Spring - Climbing Stick 03",
    "Build: The Distant Spring - Bridge 01",
    "Build: The Distant Spring - Bridge 02",
    "Build: The Distant Spring - Bridge 03",
    "Build: The Distant Spring - Bridge 04",
    "Build: The Final Trial - Dirt Wall 01",
    "Build: The Final Trial - Dirt Wall 02",
    "Build: The Final Trial - Bomb Wall 01",
    "Build: The Final Trial - Bridge 01",
    "Build: The Final Trial - Bridge 02",
    "Build: The Final Trial - Pushable Box 01",
};
static const int randomizerFinePopulation[] = {20, 30, 40, 50, 60, 70, 80, 90, 100, 125, 150, 175, 200, 250, 300, 350, 400, 450, 500};
struct RandomizerObstacle { const char* name; int stage, kind, x, z; };
static const RandomizerObstacle randomizerObstacles[] = {
    {"Build: The Impact Site - Dirt Wall 01", 0, 22, -1009, 1205},
    {"Build: The Impact Site - Bomb Wall 01", 0, 24, -1221, 730},
    {"Build: The Impact Site - Climbing Stick 01", 0, 100, -597, 1691},
    {"Build: The Impact Site - Pushable Box 01", 0, 102, -348, 987},
    {"Build: The Forest of Hope - Dirt Wall 01", 1, 22, -1044, 2375},
    {"Build: The Forest of Hope - Dirt Wall 02", 1, 22, -164, 768},
    {"Build: The Forest of Hope - Dirt Wall 03", 1, 22, -28, 2264},
    {"Build: The Forest of Hope - Reinforced Dirt Wall 01", 1, 23, -485, 1072},
    {"Build: The Forest of Hope - Reinforced Dirt Wall 02", 1, 23, -375, 390},
    {"Build: The Forest of Hope - Bomb Wall 01", 1, 24, -1444, 1761},
    {"Build: The Forest of Hope - Bomb Wall 02", 1, 24, -1353, 2800},
    {"Build: The Forest of Hope - Bomb Wall 03", 1, 24, -562, 1771},
    {"Build: The Forest of Hope - Reinforced Bomb Wall 01", 1, 25, -1498, 1008},
    {"Build: The Forest of Hope - Bridge 01", 1, 101, 376, 3784},
    {"Build: The Forest of Hope - Bridge 02", 1, 101, 549, 3044},
    {"Build: The Forest of Hope - Pushable Box 01", 1, 102, -1257, 3813},
    {"Build: The Forest Navel - Dirt Wall 01", 2, 22, 92, -418},
    {"Build: The Forest Navel - Reinforced Dirt Wall 01", 2, 23, -1307, 491},
    {"Build: The Forest Navel - Reinforced Dirt Wall 02", 2, 23, 923, 1090},
    {"Build: The Forest Navel - Bomb Wall 01", 2, 24, -313, 211},
    {"Build: The Forest Navel - Bomb Wall 02", 2, 24, 426, 660},
    {"Build: The Forest Navel - Bomb Wall 03", 2, 24, 1176, 1067},
    {"Build: The Forest Navel - Reinforced Bomb Wall 01", 2, 25, -522, 666},
    {"Build: The Forest Navel - Reinforced Bomb Wall 02", 2, 25, 783, 659},
    {"Build: The Forest Navel - Climbing Stick 01", 2, 100, -799, -633},
    {"Build: The Forest Navel - Climbing Stick 02", 2, 100, -695, 482},
    {"Build: The Forest Navel - Climbing Stick 03", 2, 100, 206, -1136},
    {"Build: The Forest Navel - Climbing Stick 04", 2, 100, 373, 337},
    {"Build: The Forest Navel - Bridge 01", 2, 101, -1205, -649},
    {"Build: The Forest Navel - Bridge 02", 2, 101, -448, 2673},
    {"Build: The Forest Navel - Bridge 03", 2, 101, -314, 2233},
    {"Build: The Forest Navel - Bridge 04", 2, 101, -2, 1180},
    {"Build: The Forest Navel - Bridge 05", 2, 101, 143, 798},
    {"Build: The Distant Spring - Dirt Wall 01", 3, 22, -1641, -1804},
    {"Build: The Distant Spring - Dirt Wall 02", 3, 22, -671, -1500},
    {"Build: The Distant Spring - Reinforced Dirt Wall 01", 3, 23, -1201, -1725},
    {"Build: The Distant Spring - Bomb Wall 01", 3, 24, -1445, -858},
    {"Build: The Distant Spring - Reinforced Bomb Wall 01", 3, 25, 340, -657},
    {"Build: The Distant Spring - Climbing Stick 01", 3, 100, -1243, -710},
    {"Build: The Distant Spring - Climbing Stick 02", 3, 100, 118, -516},
    {"Build: The Distant Spring - Climbing Stick 03", 3, 100, 993, -1023},
    {"Build: The Distant Spring - Bridge 01", 3, 101, -2158, -859},
    {"Build: The Distant Spring - Bridge 02", 3, 101, -1850, -415},
    {"Build: The Distant Spring - Bridge 03", 3, 101, -797, -1271},
    {"Build: The Distant Spring - Bridge 04", 3, 101, 1021, 1023},
    {"Build: The Final Trial - Dirt Wall 01", 4, 22, -219, 3079},
    {"Build: The Final Trial - Dirt Wall 02", 4, 22, 0, 2279},
    {"Build: The Final Trial - Bomb Wall 01", 4, 24, 0, 1280},
    {"Build: The Final Trial - Bridge 01", 4, 101, 0, 1100},
    {"Build: The Final Trial - Bridge 02", 4, 101, 0, 1465},
    {"Build: The Final Trial - Pushable Box 01", 4, 102, 0, 1913},
};
// Generated by scripts/generate_native_catalog.py; do not reorder IDs.
#pragma once
static const char* const randomizerCheckNames[] = {
    "Pikmin: Bowsprit",
    "Pikmin: Gluon Drive",
    "Pikmin: Anti-Dioxin Filter",
    "Pikmin: Eternal Fuel Dynamo",
    "Pikmin: Whimsical Radar",
    "Pikmin: Interstellar Radio",
    "Pikmin: Guard Satellite",
    "Pikmin: Chronos Reactor",
    "Pikmin: Radiation Canopy",
    "Pikmin: Geiger Counter",
    "Pikmin: Sagittarius",
    "Pikmin: Libra",
    "Pikmin: Omega Stabilizer",
    "Pikmin: Ionium Jet 1",
    "Pikmin: Ionium Jet 2",
    "Pikmin: Shock Absorber",
    "Pikmin: Gravity Jumper",
    "Pikmin: Pilot's Seat",
    "Pikmin: Nova Blaster",
    "Pikmin: Automatic Gear",
    "Pikmin: Zirconium Rotor",
    "Pikmin: Extraordinary Bolt",
    "Pikmin: Repair-type Bolt",
    "Pikmin: Space Float",
    "Pikmin: Massage Machine",
    "Pikmin: Secret Safe",
    "Pikmin: Analog Computer",
    "Pikmin: UV Lamp",
    "Pikmin: Yellow Onion Discovery",
    "Pikmin: Blue Onion Discovery",
    "Population: 20 Pikmin in the field",
    "Population: 30 Pikmin in the field",
    "Population: 40 Pikmin in the field",
    "Population: 50 Pikmin in the field",
    "Population: 60 Pikmin in the field",
    "Population: 70 Pikmin in the field",
    "Population: 80 Pikmin in the field",
    "Population: 90 Pikmin in the field",
    "Population: 100 Pikmin in the field",
    "Bestiary: Dwarf Bulborb",
    "Bestiary: Spotty Bulborb",
    "Bestiary: Female Sheargrub",
    "Bestiary: Male Sheargrub",
    "Bestiary: Shearwig",
    "Bestiary: Fiery Blowhog",
    "Bestiary: Water Dumple",
    "Bestiary: Wollywog",
    "Explore: The Forest of Hope - Land",
    "Explore: The Forest of Hope - Scout",
    "Explore: The Forest Navel - Land",
    "Explore: The Forest Navel - Scout",
    "Explore: The Distant Spring - Land",
    "Explore: The Distant Spring - Scout",
    "Explore: The Final Trial - Land",
    "Explore: The Final Trial - Scout",
    "Explore: The Impact Site - Land",
    "Explore: The Impact Site - Scout",
    "Pikmin: Positron Generator",
};
static const char* const randomizerCollectionNames[] = {
    "Pikmin: Bowsprit",
    "Pikmin: Gluon Drive",
    "Pikmin: Anti-Dioxin Filter",
    "Pikmin: Eternal Fuel Dynamo",
    "Pikmin: Whimsical Radar",
    "Pikmin: Interstellar Radio",
    "Pikmin: Guard Satellite",
    "Pikmin: Chronos Reactor",
    "Pikmin: Radiation Canopy",
    "Pikmin: Geiger Counter",
    "Pikmin: Sagittarius",
    "Pikmin: Libra",
    "Pikmin: Omega Stabilizer",
    "Pikmin: Ionium Jet 1",
    "Pikmin: Ionium Jet 2",
    "Pikmin: Shock Absorber",
    "Pikmin: Gravity Jumper",
    "Pikmin: Pilot's Seat",
    "Pikmin: Nova Blaster",
    "Pikmin: Automatic Gear",
    "Pikmin: Zirconium Rotor",
    "Pikmin: Extraordinary Bolt",
    "Pikmin: Repair-type Bolt",
    "Pikmin: Space Float",
    "Pikmin: Massage Machine",
    "Pikmin: Secret Safe",
    "Pikmin: Analog Computer",
    "Pikmin: UV Lamp",
    "Pikmin: Yellow Onion Discovery",
    "Pikmin: Blue Onion Discovery",
    "Population: 20 total Pikmin",
    "Population: 40 total Pikmin",
    "Population: 60 total Pikmin",
    "Population: 80 total Pikmin",
    "Population: 100 total Pikmin",
    "Population: 150 total Pikmin",
    "Population: 200 total Pikmin",
    "Population: 300 total Pikmin",
    "Population: 500 total Pikmin",
    "Bestiary: Deliver Dwarf Bulborb",
    "Bestiary: Deliver Spotty Bulborb",
    "Bestiary: Deliver Female Sheargrub",
    "Bestiary: Deliver Male Sheargrub",
    "Bestiary: Deliver Shearwig",
    "Bestiary: Deliver Fiery Blowhog",
    "Bestiary: Deliver Water Dumple",
    "Bestiary: Deliver Wollywog",
    "Explore: The Forest of Hope - Land",
    "Explore: The Forest of Hope - Scout",
    "Explore: The Forest Navel - Land",
    "Explore: The Forest Navel - Scout",
    "Explore: The Distant Spring - Land",
    "Explore: The Distant Spring - Scout",
    "Explore: The Final Trial - Land",
    "Explore: The Final Trial - Scout",
    "Explore: The Impact Site - Land",
    "Explore: The Impact Site - Scout",
    "Pikmin: Positron Generator",
};
static const int randomizerTotalPopulation[] = {20, 40, 60, 80, 100, 150, 200, 300, 500};
static const int randomizerEnemyTypes[] = {3, 4, 18, 19, 20, 15, 30, 33};
static const int randomizerPartWeights[] = {30, 50, 40, 40, 20, 20, 20, 20, 20, 30, 15, 20, 15, 30, 15, 15, 30, 25, 25, 30, 15, 30, 30, 20, 25, 30, 40, 20, 20, 10};
