// Generated by scripts/generate_pikmin2_roster_revision.py from
// docs/PIKMIN2_ENEMY_ROSTER.json; do not edit.
#pragma once

static const char* const randomizerP2RosterRevision = "a019a3ef5e1fc887c2574d464ac0e12a2ed7648cc8aba0524f223c18dddba902";
static const unsigned randomizerP2SourceIds[] = {1, 2, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 23, 24, 25, 26, 27, 28, 29, 30, 32, 33, 34, 35, 38, 40, 41, 42, 43, 44, 45, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 65, 66, 67, 68, 69, 70, 71, 72, 73, 75, 76, 77, 78, 79, 84, 93, 94, 95, 96, 97, 99, 101};
static inline bool randomizerP2IsBindable(unsigned id) {
    for (unsigned value : randomizerP2SourceIds) if (value == id) return true;
    return false;
}
