"""Generate owned spawn IDs and an audited initial allowlist from user assets."""
import argparse, hashlib, json, sys, zlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT))
from scripts.audit_enemy_slots import audit, STAGES

def generate(assets):
    facts=audit(assets); registry=[]; eligible=[]; labels={}
    for row in facts['slots']:
        uid=zlib.crc32(('pikrando-spawn/'+row['id']).encode())
        registry.append((uid,row['stage'],row['file'],row['offset'],row['kind'],row['species']))
        if not row['exclusions']:
            stage=row['stage'];labels[stage]=labels.get(stage,0)+1
            eligible.append(dict(uid=uid,label=f"{'hope' if stage==1 else 'spring'}_adult_{labels[stage]:02}",
                                 stage=stage,source=row['id'],original=row['species'],first_day=max(2,row['schedule']['first_day']),
                                 last_activation_day=row['schedule']['last_activation_day'],expires_after_day=row['schedule']['expires_after_day'],
                                 respawn_days=row['respawn_days'],position=row['position'],cache_position=row['cache_position']))
    if len({r[0] for r in registry})!=len(registry) or any(r[0]==0 for r in registry):raise ValueError('owned ID collision')
    if len(eligible)!=15 or any(r['original'] not in (4,32) for r in eligible):raise ValueError('allowlist changed; requires new audit/version')
    files={f"{STAGES[r['stage']]}/{r['file']}":r['sha256'] for r in facts['files']}
    files['stages.ini']=hashlib.sha256((assets/'dataDir/stages/stages.ini').read_bytes()).hexdigest()
    py='"""Generated source facts and stable owned IDs; no game asset payloads."""\n'
    py+='CATALOG_HASH = '+repr(facts['sha256'])+'\nSOURCE_FILES = '+repr(files)+'\n'
    py+='GENERATOR_SLOTS = (\n'+''.join('    '+repr(r)+',\n' for r in registry)+')\n'
    py+='ADULT_SLOTS = (\n'+''.join('    '+repr(r)+',\n' for r in eligible)+')\n'
    header='// Generated by scripts/generate_spawn_catalog.py; source IDs never depend on positions.\n#pragma once\n'
    header+='static const char* randomizerSpawnCatalogHash = '+json.dumps(facts['sha256'])+';\n'
    header+='struct RandomizerSpawnSlot { unsigned uid; int stage; const char* file; int offset; int species; };\n'
    header+='static const RandomizerSpawnSlot randomizerSpawnSlots[] = {\n'+''.join(f'    {{{uid}u, {stage}, "{file}", {offset}, {species}}},\n' for uid,stage,file,offset,kind,species in registry)+'};\n'
    header+='static const unsigned randomizerAdultSlots[] = {'+', '.join(str(r['uid'])+'u' for r in eligible)+'};\n'
    header+='static const char* randomizerAdultLabels[] = {'+', '.join(json.dumps(r['label']) for r in eligible)+'};\n'
    return py,header

if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('assets',type=Path);p.add_argument('--check',action='store_true');a=p.parse_args()
    py,header=generate(a.assets)
    engine='native' if (ROOT/'native/.git').exists() else 'engine'
    for path,text in ((ROOT/'randomizer/spawn_data.py',py),(ROOT/engine/'pc_port/pc_randomizer_spawn_catalog.h',header)):
        if a.check:
            assert path.read_text(encoding='utf-8')==text,path
        else:path.write_text(text,encoding='utf-8')
    print('Owned generator registry and 15-slot adult allowlist verified' if a.check else 'Generated owned generator registry and 15-slot adult allowlist')
