"""Generate native IDs from the same immutable-order catalog as solo/AP."""
import argparse
import json
from pathlib import Path
import sys
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from randomizer.catalog import EXPANDED_NAMES, BESTIARY, NATIVE_PART_WEIGHTS


def content():
    return ("// Generated by scripts/generate_native_catalog.py; do not reorder IDs.\n#pragma once\n"
            + "static const char* const randomizerCheckNames[] = {\n"
            + "".join("    " + json.dumps(name) + ",\n" for name in EXPANDED_NAMES)
            + "};\nstatic const int randomizerEnemyTypes[] = {"
            + ", ".join(str(value[0]) for value in BESTIARY.values()) + "};\n"
            + "static const int randomizerPartWeights[] = {"
            + ", ".join(str(NATIVE_PART_WEIGHTS[i]) for i in range(30)) + "};\n")

if __name__ == "__main__":
    p=argparse.ArgumentParser();p.add_argument("--check", action="store_true");args=p.parse_args()
    target=ROOT / "native/pc_port/pc_randomizer_catalog.h"
    if args.check:
        assert target.read_text(encoding="utf-8") == content(), "native catalog is stale"
    else:
        target.write_text(content(), encoding="utf-8")
