"""Generate the campaign-wide compatible Teki catalog; preserve legacy slot IDs."""
import argparse, hashlib, json, sys, zlib, pprint
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT))
from scripts.audit_enemy_slots import audit
POOLS={'ground':(4,32,15),'frog':(0,33),'flying':(11,16),'dwarf':(3,31),'grub':(18,19,20),'aquatic':(25,30)}
COHORT={species:name for name,values in POOLS.items() for species in values}
COHORT.update({17:'ground',24:'ground'})

def generate(assets):
    facts=audit(assets); slots=[]; sources=[]
    for r in facts['slots']:
        if r['kind']!='teki' or not r['activation_days']:continue
        uid=zlib.crc32(('pikrando-spawn/'+r['id']).encode())
        protected=r['personality']['pellet_id']!='none' or r['personality']['parameter0']!=0
        expiry=r['schedule']['expires_after_day']
        if expiry is None or expiry>=29:
            sources.append(dict(uid=uid,stage=r['stage'],original=r['species'],protected=protected,first_day=max(2,r['schedule']['first_day'])))
        if protected or r['species'] not in COHORT:continue
        if r['area'] not in ('pint','circ') or r['count_min']!=r['count_max'] or not 1<=r['count_max']<=4:
            raise ValueError('unsupported campaign distribution '+r['id'])
        pool=COHORT[r['species']]
        allowed=POOLS[pool] if r['species'] not in (17,24) else (r['species'],)
        full=POOLS[pool]+(9,17,24) if pool=='ground' else allowed
        slots.append(dict(uid=uid,label=('impact','hope','navel','spring','trial')[r['stage']]+'_'+r['id'].split('/',1)[1].replace('.gen@','_'),stage=r['stage'],source=r['id'],original=r['species'],cohort=pool,
            allowed=list(allowed),miniboss_allowed=list(full),count=r['count_max'],first_day=max(2,r['schedule']['first_day']),
            last_activation_day=r['schedule']['last_activation_day'],expires_after_day=expiry,respawn_days=r['respawn_days'],position=r['position']))
    if len(slots)!=72:raise ValueError('campaign catalog changed; audit/version required')
    digest=hashlib.sha256(json.dumps([slots,sources],sort_keys=True,separators=(',',':')).encode()).hexdigest()
    py='"""Generated campaign source facts; no raw asset payloads."""\nCAMPAIGN_HASH = '+repr(digest)+'\nCAMPAIGN_SLOTS = '+pprint.pformat(tuple(slots),width=120,sort_dicts=False)+'\nCAMPAIGN_SOURCES = '+pprint.pformat(tuple(sources),width=120,sort_dicts=False)+'\n'
    header='// Generated by scripts/generate_campaign_catalog.py\n#pragma once\n'
    header+='static const char* randomizerCampaignHash = '+json.dumps(digest)+';\n'
    header+='struct RandomizerCampaignSlot { unsigned uid; int stage; int original; unsigned long long allowed; unsigned long long minibossAllowed; };\n'
    header+='static const RandomizerCampaignSlot randomizerCampaignSlots[] = {\n'
    for r in slots:
        mask=lambda values:sum(1<<v for v in values)
        header+='    {%du, %d, %d, %dULL, %dULL},\n'%(r['uid'],r['stage'],r['original'],mask(r['allowed']),mask(r['miniboss_allowed']))
    header+='};\n'
    return py,header
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('assets',type=Path);p.add_argument('--check',action='store_true');a=p.parse_args()
    py,header=generate(a.assets)
    native='native' if (ROOT/'native/.git').exists() else 'engine'
    for path,text in ((ROOT/'randomizer/campaign_data.py',py),(ROOT/native/'pc_port/pc_randomizer_campaign_catalog.h',header)):
        if a.check:assert path.read_text(encoding='utf-8')==text
        else:path.write_text(text,encoding='utf-8')
    print('72 campaign slots across four ordinary-enemy areas; Final Trial special encounters pinned')
