"""Generate the native P2 roster revision constant and bindable-ID set.

Lane 02 owns the roster; lane 03's ``ENEMY_P2`` native parser compiles this header
so a seed whose roster revision differs fails closed natively. The revision
mirrors ``experimental.pikmin2_seed_bridge.roster_revision`` exactly.

    py -3.12 scripts/generate_pikmin2_roster_revision.py --check
    py -3.12 scripts/generate_pikmin2_roster_revision.py --output native/pc_port/pc_randomizer_p2_roster.h
"""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))


def content():
    from experimental.pikmin2_enemy_roster import load_and_validate
    from experimental.pikmin2_seed_bridge import roster_revision
    roster = load_and_validate()
    revision = roster_revision(roster)
    ids = sorted(entry.source_id for entry in roster if entry.is_randomizable_candidate)
    return (
        "// Generated by scripts/generate_pikmin2_roster_revision.py from\n"
        "// docs/PIKMIN2_ENEMY_ROSTER.json; do not edit.\n"
        "#pragma once\n\n"
        f"static const char* const randomizerP2RosterRevision = {json.dumps(revision)};\n"
        "static const unsigned randomizerP2SourceIds[] = {" + ", ".join(map(str, ids)) + "};\n"
        "static inline bool randomizerP2IsBindable(unsigned id) {\n"
        "    for (unsigned value : randomizerP2SourceIds) if (value == id) return true;\n"
        "    return false;\n"
        "}\n"
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output", type=Path, default=None)
    args = parser.parse_args()
    target = args.output or ((ROOT / "native" if (ROOT / "native/.git").exists() else ROOT / "engine")
                             / "pc_port/pc_randomizer_p2_roster.h")
    if args.check:
        assert target.read_text(encoding="utf-8") == content(), "native P2 roster revision is stale"
        print(f"native P2 roster revision matches: {target}")
    else:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content(), encoding="utf-8")
        print(f"wrote {target}")
