"""Generate the Cloaking Burrow-nit (Armor, P2 EnemyID 15) collision/mouth tables for native (#1014).

Read-only over the staged retail content. Evaluates joint world translations with the same J3D path
the pose banks use (experimental.pikmin2_rigid.joint_matrices + experimental.pikmin2_purple.bca_pose)
and writes ``pc_port/pc_p2_armor_tables.h`` in the native tree.

Tables
  kNodes   the retail armor/enemycoll.txt tree: root r40 (joint 6 kosijnt, ``____``, id none),
           ``dmg1`` r17.5 (joint 1 headjnt, ``st__``, offset 7.5,0,0) and the shell sphere r22.5
           (joint 7 kourajnt, ``_t__``, id none, offset 7.5,-5,0). Only ``dmg1`` has the stickable code
           (CollPart::isStickable matches ``s***``, collinfo.cpp:806) and only ``dmg1`` passes
           Armor::damageCallBack (Armor.cpp:117-128).
  kColl    per clip, the model-space centre of every node for EVERY source frame (joint translation plus
           the node offset rotated by the joint matrix).
  kMouth   per clip, the model-space world translation of the ``kamujnt`` joint (joint 2) for every
           frame: Obj::initMouthSlots (Armor.cpp:205-213) calls MouthSlots::setup(0, mModel, "kamujnt").

Model-space convention (same as pc_p2_chappy_mouth.h): +z is the facing direction, +y up from the
feet, world = actor + R_y(heading) * local * actor scale.

Usage:
  py -3.12 scripts/p2_armor_tables.py --content <dir with Armor/> --out <header>
"""
import argparse
import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from experimental.pikmin2_breadbug_assets import collision_nodes  # noqa: E402
from experimental.pikmin2_convert import blocks  # noqa: E402
from experimental.pikmin2_sheargrub_assets import joints  # noqa: E402
from experimental.pikmin2_purple import bca_pose  # noqa: E402
from experimental.pikmin2_rigid import joint_matrices  # noqa: E402

# Every clip the Armor FSM plays (Armor.h AnimID; the bank names them by stem).
CLIPS = ('appear', 'attack1', 'attack2', 'attack_fail', 'carry', 'dead', 'dive', 'eat', 'flick', 'move')
MOUTH_JOINT = 'kamujnt'
EXPECTED = (('none', '____', 40.0, 6), ('dmg1', 'st__', 17.5, 1), ('none', '_t__', 22.5, 7))


def sha(data):
    return hashlib.sha256(data).hexdigest()


def centre(m, joint, offset):
    row = m[joint]
    return [row[r][0] * offset[0] + row[r][1] * offset[1] + row[r][2] * offset[2] + row[r][3] for r in range(3)]


def build(content):
    base = Path(content) / 'Armor'
    if (base / 'Armor').is_dir():
        base = base / 'Armor'
    model = (base / 'enemy.bmd').read_bytes()
    names = joints(model)
    b = blocks(model)
    mouth = names.index(MOUTH_JOINT)
    coll_raw = (base / 'enemycoll.txt').read_bytes()
    nodes = collision_nodes(coll_raw, len(names))
    got = tuple((n['id'], n['code'], n['radius'], n['joint']) for n in nodes)
    if got != EXPECTED:
        raise SystemExit(f'unexpected Armor collision tree: {got}')
    stickable = [n['id'] for n in nodes if n['code'].startswith('s')]
    if stickable != ['dmg1']:
        raise SystemExit(f'expected only dmg1 to be stickable (st__), got {stickable}')
    clips, clip_sha = {}, {}
    for stem in CLIPS:
        raw = (base / f'{stem}.bca').read_bytes()
        clip_sha[stem] = sha(raw)
        duration = bca_pose(raw, 0, len(names), allow_scale=True)[0]
        coll, tongue = [], []
        for frame in range(duration):
            _, pose = bca_pose(raw, frame, len(names), allow_scale=True)
            m = joint_matrices(b, pose)
            coll.append([centre(m, n['joint'], n['offset']) for n in nodes])
            tongue.append([m[mouth][r][3] for r in range(3)])
        clips[stem] = (duration, coll, tongue)
    return sha(model), nodes, names, clips, sha(coll_raw), clip_sha


def render(model_sha, nodes, names, clips, coll_sha, clip_sha):
    out = ['#pragma once',
           '// GENERATED by scripts/p2_armor_tables.py - do not edit.',
           '// Cloaking Burrow-nit (Armor 15) tables. Source: Armor.cpp initMouthSlots (kamujnt) and the retail',
           '// armor/enemycoll.txt collision tree posed through every frame of every clip.',
           f'// model sha256 {model_sha}',
           f'// enemycoll sha256 {coll_sha}',
           'namespace p2armortables {',
           f'constexpr int kNodeCount = {len(nodes)};',
           f'constexpr int kClipCount = {len(CLIPS)};',
           'struct Node {',
           '    const char* id;    // FourCC part id ("none" for the unnamed parts)',
           '    const char* code;  // FourCC part code ("st__" stickable, "____" / "_t__" not)',
           '    float radius;      // model units (scale 1)',
           '    int joint;         // retail joint index',
           '    const char* jointName;',
           '    int parent;        // index into kNodes, -1 for the root',
           '};',
           'inline constexpr Node kNodes[kNodeCount] = {']
    for n in nodes:
        out.append('    {"%s", "%s", %.3ff, %d, "%s", %d},' % (
            n['id'], n['code'], n['radius'], n['joint'], names[n['joint']],
            -1 if n['parent'] is None else n['parent']))
    out += ['};', '',
            'struct Clip {',
            '    const char* stem;',
            '    int frames;       // clip length in source frames (one sample per frame)',
            '    int collOffset;   // first float of this clip in kColl (frames * kNodeCount * 3)',
            '    int mouthOffset;  // first float of this clip in kMouth (frames * 3)',
            '};']
    coll_flat, mouth_flat, rows = [], [], []
    for stem in CLIPS:
        duration, coll, tongue = clips[stem]
        rows.append('    {"%s", %d, %d, %d},  // %s' % (stem, duration, len(coll_flat), len(mouth_flat),
                                                      clip_sha[stem][:16]))
        for sample in coll:
            for c in sample:
                coll_flat.extend(c)
        for pos in tongue:
            mouth_flat.extend(pos)
    out.append('inline constexpr Clip kClips[kClipCount] = {')
    out += rows
    out.append('};')
    out.append('')

    def emit(name, flat):
        out.append('inline constexpr float %s[%d] = {' % (name, len(flat)))
        for i in range(0, len(flat), 9):
            out.append('    ' + ', '.join('%.2ff' % v for v in flat[i:i + 9]) + ',')
        out.append('};')
        out.append('')
    emit('kColl', coll_flat)
    emit('kMouth', mouth_flat)
    out += ['} // namespace p2armortables', '']
    return '\n'.join(out)


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument('--content', required=True)
    parser.add_argument('--out', required=True)
    args = parser.parse_args(argv)
    text = render(*build(args.content))
    Path(args.out).write_text(text, encoding='utf-8', newline='\n')
    print(f'wrote {args.out} ({len(text.splitlines())} lines)')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
