"""Generate the Raging Long Legs (BigFoot, 69) skeleton and collision tables for native (#1018).

Read-only over the retail disc. Writes ``pc_port/pc_p2_bigfoot_tables.h`` in the
native tree:

* the 15 joint names of ``enemy/data/BigFoot/model.szs:enemy.bmd`` and every
  joint's bind model-space 3x4 matrix;
* for each of the four disc clips (``anim.szs``: dead, landing, wait, flick, in
  BIGFOOTANIM order, BigFoot.h:240-244) the model-space 3x4 matrix of every
  joint at SAMPLES evenly spaced frames (the same J3D path the pose banks use);
* the retail ``bigfoot/enemycoll.txt`` collision tree (enemy/parm/enemyParms.szs):
  id, code, radius, joint, joint-frame offset and parent of every node.

The native BigFoot brain (pc_p2_bigfoot_fsm) poses the body and the collision
tree from these tables and hands the leg joints to the source IK
(pc_p2_long_legs_ik). Model-space convention: +z is the facing direction, +y up
from the feet; world = centre + R_y(face) * local.

Usage:
  py -3.12 scripts/p2_bigfoot_tables.py --iso <P2 US disc> --out <native>/pc_port/pc_p2_bigfoot_tables.h
"""
import argparse
import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from experimental.pikmin2_assets import archive_files, disc_files  # noqa: E402
from experimental.pikmin2_breadbug_assets import collision_nodes  # noqa: E402
from experimental.pikmin2_convert import blocks  # noqa: E402
from experimental.pikmin2_purple import bca_pose  # noqa: E402
from experimental.pikmin2_rigid import joint_matrices  # noqa: E402
from experimental.pikmin2_sheargrub_assets import joints  # noqa: E402

SAMPLES = 32
CLIPS = ('dead', 'landing', 'wait', 'flick')  # BIGFOOTANIM_Dead, Landing, Wait, Flick


def sha(data):
    return hashlib.sha256(data).hexdigest()


def read_disc(iso):
    iso = Path(iso)
    index = disc_files(iso)
    with iso.open('rb') as disc:
        def read(path):
            at, size = index[path]
            disc.seek(at)
            raw = disc.read(size)
            if len(raw) != size:
                raise ValueError(f'Truncated disc entry: {path}')
            return raw
        model = archive_files(read('enemy/data/BigFoot/model.szs'))['enemy.bmd']
        motions = archive_files(read('enemy/data/BigFoot/anim.szs'))
        params = archive_files(read('enemy/parm/enemyParms.szs'))
    return model, motions, params['bigfoot/enemycoll.txt']


def build(model, motions, coll_raw):
    names = joints(model)
    b = blocks(model)
    bind = joint_matrices(b)
    nodes = collision_nodes(coll_raw, len(names))
    clips = []
    for stem in CLIPS:
        raw = motions[stem + '.bca']
        duration = bca_pose(raw, 0, len(names), allow_scale=True)[0]
        samples = []
        for i in range(SAMPLES):
            frame = round(i * (duration - 1) / (SAMPLES - 1))
            _, pose = bca_pose(raw, frame, len(names), allow_scale=True)
            samples.append(joint_matrices(b, pose))
        clips.append((stem, duration, sha(raw), samples))
    return names, bind, nodes, clips


def mtx(m):
    return '{' + ', '.join('{' + ', '.join('%.4ff' % v for v in row) + '}' for row in m) + '}'


def render(model_sha, coll_sha, names, bind, nodes, clips):
    out = ['#pragma once',
           '// GENERATED by scripts/p2_bigfoot_tables.py - do not edit.',
           '// Raging Long Legs (BigFoot 69): retail skeleton, clips and enemycoll tree (#1018).',
           f'// model sha256 {model_sha}',
           f'// enemycoll sha256 {coll_sha}',
           'namespace p2bigfoot {',
           f'constexpr int kJointCount = {len(names)};',
           f'constexpr int kSamples = {SAMPLES};',
           f'constexpr int kClipCount = {len(clips)};',
           f'constexpr int kCollNodeCount = {len(nodes)};',
           'inline constexpr const char* kJointNames[kJointCount] = {'
           + ', '.join(f'"{n}"' for n in names) + '};',
           '// Bind model-space matrices (row-major 3x4, column 3 = translation).',
           'inline constexpr float kBind[kJointCount][3][4] = {']
    for m in bind:
        out.append('    ' + mtx(m) + ',')
    out += ['};',
            'struct Clip {',
            '    const char* stem;',
            '    int frames;  // clip length in source frames (30 fps)',
            '    float joint[kSamples][kJointCount][3][4];  // model-space joint matrices',
            '};',
            '// BIGFOOTANIM order (BigFoot.h:240-244): dead, landing, wait, flick.',
            'inline constexpr Clip kClips[kClipCount] = {']
    for stem, duration, clip_sha, samples in clips:
        out.append('    {"%s", %d, {   // %s' % (stem, duration, clip_sha[:16]))
        for sample in samples:
            out.append('        {' + ', '.join(mtx(m) for m in sample) + '},')
        out.append('    }},')
    out += ['};',
            'struct CollNode {',
            '    const char* id;     // FourCC part id',
            '    const char* code;   // FourCC code ("st__" stickable, "_t__" touch only)',
            '    float radius;',
            '    float offset[3];    // in the joint frame',
            '    int joint;',
            '    int parent;         // index into kColl, -1 for the root',
            '};',
            'inline constexpr CollNode kColl[kCollNodeCount] = {']
    for n in nodes:
        out.append('    {"%s", "%s", %.3ff, {%.3ff, %.3ff, %.3ff}, %d, %d},'
                   % (n['id'], n['code'], n['radius'], *n['offset'], n['joint'],
                      -1 if n['parent'] is None else n['parent']))
    out += ['};', '} // namespace p2bigfoot', '']
    return '\n'.join(out)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--iso', required=True, type=Path)
    parser.add_argument('--out', required=True, type=Path)
    args = parser.parse_args(argv)
    model, motions, coll_raw = read_disc(args.iso)
    names, bind, nodes, clips = build(model, motions, coll_raw)
    args.out.write_text(render(sha(model), sha(coll_raw), names, bind, nodes, clips), encoding='utf-8', newline='\n')
    print(f'wrote {args.out} ({len(names)} joints, {len(clips)} clips x {SAMPLES}, {len(nodes)} collision nodes)')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
