"""Generate the Gatling Groink (MiniHoudai, 78 / FminiHoudai, 97) collision tables for native.

Read-only over the staged retail content. Evaluates the model-space centre of
every node of the retail ``minihoudai/enemycoll.txt`` tree (joint translation
plus the node offset rotated by the joint matrix) for each clip the Groink FSM
plays, at COLL_SAMPLES evenly spaced frames, with the same J3D path the pose
banks use, and writes ``pc_port/pc_p2_groink_coll_tables.h`` in the native
tree. Same shape as scripts/p2_king_tables.py.

Retail tree: root 'none' r55 plus body (``st__``, the ONLY stickable part) and
asiL/asiR/cov1/cov2/cov3/coll (``_t__``, touch only). cov1..cov3 ride the head
joint and form the front armour cover, so Pikmin cannot latch onto the face.
CollPart::isStickable matches the code against ``s***`` (collinfo.cpp:806-809).

Model-space convention (same as the King tables): +z is the facing direction,
+y up from the feet, world = actor + R_y(heading) * local.

Usage:
  py -3.12 scripts/p2_groink_coll_tables.py --content <dir with MiniHoudai/> --out <header>
"""
import argparse
import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from experimental.pikmin2_breadbug_assets import collision_nodes  # noqa: E402
from experimental.pikmin2_convert import blocks  # noqa: E402
from experimental.pikmin2_mamuta_assets import joints  # noqa: E402
from experimental.pikmin2_purple import bca_pose  # noqa: E402
from experimental.pikmin2_rigid import joint_matrices  # noqa: E402

COLL_SAMPLES = 16
# AnimID order of MiniHoudai.h (walk, search1, turn1, attack1, flick1, dead1, type5, rebirth).
CLIPS = ('walk', 'search1', 'turn1', 'attack1', 'flick1', 'dead1', 'type5', 'rebirth')


def sha(data):
    return hashlib.sha256(data).hexdigest()


def centre(m, joint, offset):
    """Model-space position of `offset` in the joint frame."""
    row = m[joint]
    return [row[r][0] * offset[0] + row[r][1] * offset[1] + row[r][2] * offset[2] + row[r][3] for r in range(3)]


def build(content):
    root = Path(content) / 'MiniHoudai'
    model = (root / 'enemy.bmd').read_bytes()
    names = joints(model)
    b = blocks(model)
    coll_raw = (root / 'enemycoll.txt').read_bytes()
    nodes = collision_nodes(coll_raw, len(names))
    clips, clip_sha = {}, {}
    for stem in CLIPS:
        raw = (root / f'{stem}.bca').read_bytes()
        clip_sha[stem] = sha(raw)
        duration = bca_pose(raw, 0, len(names), allow_scale=True)[0]
        samples = []
        for i in range(COLL_SAMPLES):
            frame = round(i * (duration - 1) / (COLL_SAMPLES - 1))
            _, pose = bca_pose(raw, frame, len(names), allow_scale=True)
            m = joint_matrices(b, pose)
            samples.append([centre(m, n['joint'], n['offset']) for n in nodes])
        clips[stem] = (duration, samples)
    return sha(model), nodes, clips, sha(coll_raw), clip_sha


def render(model_sha, nodes, clips, coll_sha, clip_sha):
    out = ['#pragma once',
           '// GENERATED by scripts/p2_groink_coll_tables.py - do not edit.',
           '// Gatling Groink (MiniHoudai 78 / FminiHoudai 97) retail minihoudai/enemycoll.txt',
           '// collision tree posed through each clip. body is the only stickable part;',
           '// cov1..cov3 (head joint) are the front armour cover.',
           f'// model sha256 {model_sha}',
           f'// enemycoll sha256 {coll_sha}',
           'namespace p2groinkcoll {',
           f'constexpr int kCollNodeCount = {len(nodes)};',
           f'constexpr int kCollSamples = {COLL_SAMPLES};',
           f'constexpr int kCollClipCount = {len(CLIPS)};',
           'struct CollNode {',
           '    const char* id;     // FourCC part id',
           '    const char* code;   // FourCC part code ("st__" stickable, "_t__" touch only)',
           '    float radius;       // model units (scale 1)',
           '    int parent;         // index into kCollNodes, -1 for the root',
           '};',
           'inline constexpr CollNode kCollNodes[kCollNodeCount] = {']
    for n in nodes:
        out.append('    {"%s", "%s", %.3ff, %d},' % (n['id'], n['code'], n['radius'], -1 if n['parent'] is None else n['parent']))
    out += ['};', '',
            'struct CollClip {',
            '    const char* stem;',
            '    int frames;  // clip length in source frames',
            '    float centre[kCollSamples][kCollNodeCount][3]; // model-space node centres',
            '};',
            'inline constexpr CollClip kCollClips[kCollClipCount] = {']
    for stem in CLIPS:
        duration, samples = clips[stem]
        out.append('    {"%s", %d, {   // %s' % (stem, duration, clip_sha[stem][:16]))
        for cs in samples:
            out.append('        {' + ', '.join('{%.3ff, %.3ff, %.3ff}' % tuple(c) for c in cs) + '},')
        out.append('    }},')
    out += ['};', '} // namespace p2groinkcoll', '']
    return '\n'.join(out)


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument('--content', required=True, type=Path)
    parser.add_argument('--out', required=True, type=Path)
    args = parser.parse_args(argv)
    result = build(args.content)
    args.out.write_text(render(*result), encoding='utf-8', newline='\n')
    print(f'wrote {args.out} ({len(result[1])} collision nodes, {len(CLIPS)} clips)')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
