"""Generate the KingChappy (Emperor Bulblax, 53) joint tables for native.

Read-only over the staged retail content. Evaluates joint world translations
with the same J3D path the pose banks use (experimental.pikmin2_rigid
.joint_matrices + experimental.pikmin2_purple.bca_pose) and writes
``pc_port/pc_p2_king_tables.h`` in the native tree.

Tables
  kTongue[95][6]      bero6 (tip) then bero5 (root of the tip) model-space
                      translation for attack.bca frames 0..94. Source
                      StateAttack::exec (kingChappyState.cpp:157-172) traces a
                      radius-5 sphere at bero6 + (0,5,0) moving along
                      normalise(bero6 - bero5) and ends the lick on floor/wall
                      contact.
  kCollNodes / kColl  the retail kingchappy/enemycoll.txt tree (root 'none' r80
                      plus back/ketu/asiL/asiR/head/hana/kuti) and, per clip, the
                      model-space centre of every node (joint translation plus the
                      node offset rotated by the joint matrix) at kCollSamples
                      evenly spaced frames. Native interpolates between samples.
                      kMouth is the kuti joint per clip sample (the swallow slots
                      outside the attack window).

Model-space convention (same as pc_p2_chappy_mouth.h): +z is the facing
direction, +y up from the feet, world = actor + R_y(heading) * local.

Usage:
  py -3.12 scripts/p2_king_tables.py --content <dir with KingChappy/> --out <header>
"""
import argparse
import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from experimental.pikmin2_breadbug_assets import collision_nodes  # noqa: E402
from experimental.pikmin2_convert import blocks  # noqa: E402
from experimental.pikmin2_mamuta_assets import joints  # noqa: E402
from experimental.pikmin2_purple import bca_pose  # noqa: E402
from experimental.pikmin2_rigid import joint_matrices  # noqa: E402

ATTACK_FRAMES = 95
COLL_SAMPLES = 16
# Every clip the Emperor FSM plays (KingChappy.h AnimID stems; 'carry' belongs to the P1 carcass).
CLIPS = ('move1', 'attack', 'dead', 'flick', 'cry', 'damage', 'dive', 'type1', 'type2', 'type3',
         'wait2', 'waitact1', 'waitact2')


def sha(data):
    return hashlib.sha256(data).hexdigest()


def centre(m, joint, offset):
    """World-of-model position of `offset` in the joint frame."""
    row = m[joint]
    return [row[r][0] * offset[0] + row[r][1] * offset[1] + row[r][2] * offset[2] + row[r][3] for r in range(3)]


def build(content):
    king = Path(content) / 'KingChappy'
    model = (king / 'enemy.bmd').read_bytes()
    attack = (king / 'attack.bca').read_bytes()
    names = joints(model)
    b = blocks(model)
    tip, root = names.index('bero6'), names.index('bero5')
    kuti = names.index('kuti')
    rows = []
    for frame in range(ATTACK_FRAMES):
        duration, pose = bca_pose(attack, frame, len(names), allow_scale=True)
        if duration != ATTACK_FRAMES:
            raise SystemExit(f'attack.bca duration {duration} != {ATTACK_FRAMES}')
        m = joint_matrices(b, pose)
        rows.append([m[tip][r][3] for r in range(3)] + [m[root][r][3] for r in range(3)])
    coll_raw = (king / 'enemycoll.txt').read_bytes()
    nodes = collision_nodes(coll_raw, len(names))
    clips = {}
    clip_sha = {}
    for stem in CLIPS:
        raw = (king / f'{stem}.bca').read_bytes()
        clip_sha[stem] = sha(raw)
        duration = bca_pose(raw, 0, len(names), allow_scale=True)[0]
        samples = []
        for i in range(COLL_SAMPLES):
            frame = round(i * (duration - 1) / (COLL_SAMPLES - 1))
            _, pose = bca_pose(raw, frame, len(names), allow_scale=True)
            m = joint_matrices(b, pose)
            samples.append(([centre(m, n['joint'], n['offset']) for n in nodes], [m[kuti][r][3] for r in range(3)]))
        clips[stem] = (duration, samples)
    return sha(model), sha(attack), rows, nodes, clips, sha(coll_raw), clip_sha


def render(model_sha, attack_sha, rows, nodes, clips, coll_sha, clip_sha):
    out = ['#pragma once',
           '// GENERATED by scripts/p2_king_tables.py - do not edit.',
           '// KingChappy (53) joint tables. Source: kingChappyState.cpp StateAttack::exec',
           '// (getTonguePosVel: pos = bero6, vel = normalise(bero6 - bero5)) and the retail',
           '// kingchappy/enemycoll.txt collision tree posed through each clip.',
           f'// model sha256 {model_sha}',
           f'// attack sha256 {attack_sha}',
           f'// enemycoll sha256 {coll_sha}',
           'namespace p2kingtables {',
           f'constexpr int kTongueFrames = {len(rows)};',
           'inline constexpr float kTongue[kTongueFrames][6] = {']
    for frame, r in enumerate(rows):
        out.append('    /* %2d */ {%s},' % (frame, ', '.join('%.3ff' % v for v in r)))
    out += ['};', '',
            f'constexpr int kCollNodeCount = {len(nodes)};',
            f'constexpr int kCollSamples = {COLL_SAMPLES};',
            f'constexpr int kCollClipCount = {len(CLIPS)};',
            'struct CollNode {',
            '    const char* id;     // FourCC part id',
            '    const char* code;   // FourCC part code ("st__" stickable, "_t__" touchable)',
            '    float radius;       // model units (scale 1)',
            '    int parent;         // index into kCollNodes, -1 for the root',
            '};',
            'inline constexpr CollNode kCollNodes[kCollNodeCount] = {']
    for n in nodes:
        out.append('    {"%s", "%s", %.3ff, %d},' % (n['id'], n['code'], n['radius'], -1 if n['parent'] is None else n['parent']))
    out += ['};', '',
            'struct CollClip {',
            '    const char* stem;',
            '    int frames;  // clip length in source frames',
            '    float centre[kCollSamples][kCollNodeCount][3]; // model-space node centres',
            '    float mouth[kCollSamples][3];                  // kuti joint (swallow slots outside the attack window)',
            '};',
            'inline constexpr CollClip kCollClips[kCollClipCount] = {']
    for stem in CLIPS:
        duration, samples = clips[stem]
        out.append('    {"%s", %d, {   // %s' % (stem, duration, clip_sha[stem][:16]))
        for cs, _ in samples:
            out.append('        {' + ', '.join('{%.3ff, %.3ff, %.3ff}' % tuple(c) for c in cs) + '},')
        out.append('    }, {')
        out.append('        ' + ', '.join('{%.3ff, %.3ff, %.3ff}' % tuple(k) for _, k in samples))
        out.append('    }},')
    out += ['};', '} // namespace p2kingtables', '']
    return '\n'.join(out)


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument('--content', required=True, type=Path)
    parser.add_argument('--out', required=True, type=Path)
    args = parser.parse_args(argv)
    result = build(args.content)
    args.out.write_text(render(*result), encoding='utf-8')
    print(f'wrote {args.out} ({len(result[2])} tongue frames, {len(result[3])} collision nodes, {len(CLIPS)} clips)')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
