"""Generate the joint ROTATION tables for the skewered-Pikmin visual (#1020).

P2 draws a Pikmin held in a mouth slot with the slot joint's own matrix times a +90 degree Z turn
(Creature::updateStick, creatureStick.cpp:221-247), so the Pikmin takes the joint's orientation. The earlier
tables only carry joint positions; this adds the joint's rotation (normalised 3x3, model space, columns =
joint X/Y/Z axes) for every frame of the clips where the slot holds a Pikmin:

  Armor (15)      kamujnt, every frame of every clip
  UmiMushi (71/101) kamu_joint1..7, every frame of attack1 and eat1

Writes ``pc_port/pc_p2_skewer_axes.h`` in the native tree.

Usage:
  py -3.12 scripts/p2_skewer_axes.py --armor <dir with enemy.bmd + clips> --umimushi <same> --out <header>
"""
import argparse
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from experimental.pikmin2_convert import blocks  # noqa: E402
from experimental.pikmin2_sheargrub_assets import joints  # noqa: E402
from experimental.pikmin2_purple import bca_pose  # noqa: E402
from experimental.pikmin2_rigid import joint_matrices  # noqa: E402

ARMOR_CLIPS = ('appear', 'attack1', 'attack2', 'attack_fail', 'carry', 'dead', 'dive', 'eat', 'flick', 'move')
UMI_CLIPS = ('attack1', 'eat1')
UMI_JOINTS = tuple('kamu_joint%d' % i for i in range(1, 8))


def rotation(m, joint):
    """Normalised 3x3 (row-major rows of the affine matrix) of one joint."""
    cols = []
    for c in range(3):
        v = [m[joint][r][c] for r in range(3)]
        n = math.sqrt(sum(x * x for x in v)) or 1.0
        cols.append([x / n for x in v])
    return [cols[c][r] for r in range(3) for c in range(3)]  # row-major: R[r][c]


def sample(base, stems, joint_names, extra=False):
    model = (base / 'enemy.bmd').read_bytes()
    names = joints(model)
    b = blocks(model)
    ids = [names.index(n) for n in joint_names]
    out = {}
    for stem in stems:
        raw = (base / f'{stem}.bca').read_bytes()
        duration = bca_pose(raw, 0, len(names), allow_scale=True, extra_tracks=extra)[0]
        rows = []
        for frame in range(duration):
            _, pose = bca_pose(raw, frame, len(names), allow_scale=True, extra_tracks=extra)
            m = joint_matrices(b, pose)
            for j in ids:
                rows.extend(rotation(m, j))
        out[stem] = (duration, rows)
    return out


def emit(name, flat, out):
    out.append('inline constexpr float %s[%d] = {' % (name, len(flat)))
    for i in range(0, len(flat), 9):
        out.append('    ' + ', '.join('%.4ff' % v for v in flat[i:i + 9]) + ',')
    out.append('};')
    out.append('')


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument('--armor', required=True, type=Path)
    parser.add_argument('--umimushi', required=True, type=Path)
    parser.add_argument('--out', required=True, type=Path)
    args = parser.parse_args(argv)
    armor = sample(args.armor, ARMOR_CLIPS, ('kamujnt',))
    umi = sample(args.umimushi, UMI_CLIPS, UMI_JOINTS, extra=True)
    out = ['#pragma once',
           '// GENERATED by scripts/p2_skewer_axes.py - do not edit.',
           '// Slot-joint rotations (normalised, model space, row-major 3x3) for the skewered-Pikmin visual.',
           'namespace p2skeweraxes {',
           'struct Clip { const char* stem; int frames; int offset; };  // offset in floats']
    flat, rows = [], []
    for stem in ARMOR_CLIPS:
        d, r = armor[stem]
        rows.append('    {"%s", %d, %d},' % (stem, d, len(flat)))
        flat.extend(r)
    out.append('constexpr int kArmorClipCount = %d;' % len(ARMOR_CLIPS))
    out.append('inline constexpr Clip kArmorClips[kArmorClipCount] = {')
    out += rows
    out.append('};')
    emit('kArmor', flat, out)
    flat, rows = [], []
    for stem in UMI_CLIPS:
        d, r = umi[stem]
        rows.append('    {"%s", %d, %d},' % (stem, d, len(flat)))
        flat.extend(r)
    out.append('constexpr int kUmiClipCount = %d;' % len(UMI_CLIPS))
    out.append('constexpr int kUmiJoints = %d;' % len(UMI_JOINTS))
    out.append('inline constexpr Clip kUmiClips[kUmiClipCount] = {')
    out += rows
    out.append('};')
    emit('kUmi', flat, out)
    out.append('} // namespace p2skeweraxes')
    args.out.write_text('\n'.join(out) + '\n', encoding='utf-8')
    print('wrote', args.out)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
