"""Generate the UmiMushi (Bloyster 71 / 101) joint tables for native (#995).

Read-only over the staged retail content. Evaluates joint world translations
with the same J3D path the pose banks use (experimental.pikmin2_rigid
.joint_matrices + experimental.pikmin2_purple.bca_pose) and writes
``pc_port/pc_p2_umimushi_tables.h`` in the native tree.

Tables
  kNodes      the retail umimushi/enemycoll.txt tree: root r180 (joint 0), head r80
              (joint 1), kuti r40 (joint 14), ketu r25 (joint 18) and weak r10
              (joint 24, weak_joint2). Only `weak` carries the stickable code
              `st__` (CollPart::isStickable matches 's***', collinfo.cpp:806).
  kColl       per clip, the model-space centre of every node (joint translation
              plus the node offset rotated by the joint matrix), sampled evenly
              (at most MAX_SAMPLES per clip, every frame when the clip is shorter).
  kKamu       the seven mouth-slot joints kamu_joint1..7 (Obj::initMouthSlots,
              umiMushi.cpp:552-566: MouthSlots::setup takes the joint world
              translation) for EVERY frame of attack1 and eat1, the two clips where
              the tongue eats and holds.

Model-space convention (same as pc_p2_chappy_mouth.h): +z is the facing direction,
+y up from the feet, world = actor + R_y(heading) * local * actor scale.

Usage:
  py -3.12 scripts/p2_umimushi_tables.py --content <dir with UmiMushi/> --out <header>
"""
import argparse
import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from experimental.pikmin2_breadbug_assets import collision_nodes  # noqa: E402
from experimental.pikmin2_convert import blocks  # noqa: E402
from experimental.pikmin2_sheargrub_assets import joints  # noqa: E402
from experimental.pikmin2_purple import bca_pose  # noqa: E402
from experimental.pikmin2_rigid import joint_matrices  # noqa: E402

MAX_SAMPLES = 40
# Every clip the Bloyster FSM plays (UmiMushi.h AnimID stems).
CLIPS = ('attack1', 'dead1', 'eat1', 'fsearch1', 'flick1', 'outview1', 'run1', 'search1', 'srun1', 'sturn1',
         'type5', 'wait1')
KAMU_CLIPS = ('attack1', 'eat1')
KAMU = tuple('kamu_joint%d' % i for i in range(1, 8))


def sha(data):
    return hashlib.sha256(data).hexdigest()


def centre(m, joint, offset):
    row = m[joint]
    return [row[r][0] * offset[0] + row[r][1] * offset[1] + row[r][2] * offset[2] + row[r][3] for r in range(3)]


def sample_frames(duration):
    if duration <= MAX_SAMPLES:
        return list(range(duration))
    return [round(i * (duration - 1) / (MAX_SAMPLES - 1)) for i in range(MAX_SAMPLES)]


def build(content):
    base = Path(content) / 'UmiMushi'
    if (base / 'UmiMushi').is_dir():
        base = base / 'UmiMushi'
    model = (base / 'enemy.bmd').read_bytes()
    names = joints(model)
    b = blocks(model)
    kamu = [names.index(n) for n in KAMU]
    coll_raw = (base / 'enemycoll.txt').read_bytes()
    nodes = collision_nodes(coll_raw, len(names))
    stickable = [n['id'] for n in nodes if n['code'].startswith('s')]
    if stickable != ['weak']:
        raise SystemExit(f'expected only the weak tail bulb to be stickable (st__), got {stickable}')
    clips = {}
    clip_sha = {}
    for stem in CLIPS:
        raw = (base / f'{stem}.bca').read_bytes()
        clip_sha[stem] = sha(raw)
        duration = bca_pose(raw, 0, len(names), allow_scale=True, extra_tracks=True)[0]
        coll = []
        for frame in sample_frames(duration):
            _, pose = bca_pose(raw, frame, len(names), allow_scale=True, extra_tracks=True)
            m = joint_matrices(b, pose)
            coll.append([centre(m, n['joint'], n['offset']) for n in nodes])
        tongue = []
        if stem in KAMU_CLIPS:
            for frame in range(duration):
                _, pose = bca_pose(raw, frame, len(names), allow_scale=True, extra_tracks=True)
                m = joint_matrices(b, pose)
                tongue.append([[m[j][r][3] for r in range(3)] for j in kamu])
        clips[stem] = (duration, coll, tongue)
    return sha(model), nodes, clips, sha(coll_raw), clip_sha


def render(model_sha, nodes, clips, coll_sha, clip_sha):
    out = ['#pragma once',
           '// GENERATED by scripts/p2_umimushi_tables.py - do not edit.',
           '// UmiMushi (Bloyster 71 / 101) joint tables. Source: umiMushi.cpp initMouthSlots (kamu_joint1..7)',
           '// and the retail umimushi/enemycoll.txt collision tree posed through each clip.',
           f'// model sha256 {model_sha}',
           f'// enemycoll sha256 {coll_sha}',
           'namespace p2umitables {',
           f'constexpr int kNodeCount = {len(nodes)};',
           f'constexpr int kKamuCount = {len(KAMU)};',
           f'constexpr int kClipCount = {len(CLIPS)};',
           'struct Node {',
           '    const char* id;    // FourCC part id',
           '    const char* code;  // FourCC part code ("st__" stickable, "____" plain)',
           '    float radius;      // model units (scale 1)',
           '    int parent;        // index into kNodes, -1 for the root',
           '};',
           'inline constexpr Node kNodes[kNodeCount] = {']
    for n in nodes:
        out.append('    {"%s", "%s", %.3ff, %d},' % (n['id'], n['code'], n['radius'], -1 if n['parent'] is None else n['parent']))
    out += ['};', '',
            'struct Clip {',
            '    const char* stem;',
            '    int frames;       // clip length in source frames',
            '    int samples;      // coll samples (evenly spaced, last = frames-1)',
            '    int collOffset;   // first float of this clip in kColl (samples * kNodeCount * 3)',
            '    int kamuFrames;   // 0, or frames when kKamu holds every frame',
            '    int kamuOffset;   // first float of this clip in kKamu (kamuFrames * kKamuCount * 3)',
            '};']
    coll_flat, kamu_flat, rows = [], [], []
    for stem in CLIPS:
        duration, coll, tongue = clips[stem]
        rows.append('    {"%s", %d, %d, %d, %d, %d},  // %s' % (stem, duration, len(coll), len(coll_flat), len(tongue),
                                                               len(kamu_flat), clip_sha[stem][:16]))
        for sample in coll:
            for c in sample:
                coll_flat.extend(c)
        for frame in tongue:
            for c in frame:
                kamu_flat.extend(c)
    out.append('inline constexpr Clip kClips[kClipCount] = {')
    out += rows
    out.append('};')
    out.append('')

    def emit(name, flat):
        out.append('inline constexpr float %s[%d] = {' % (name, len(flat)))
        for i in range(0, len(flat), 9):
            out.append('    ' + ', '.join('%.2ff' % v for v in flat[i:i + 9]) + ',')
        out.append('};')
        out.append('')
    emit('kColl', coll_flat)
    emit('kKamu', kamu_flat)
    out += ['} // namespace p2umitables', '']
    return '\n'.join(out)


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument('--content', required=True, type=Path)
    parser.add_argument('--out', required=True, type=Path)
    args = parser.parse_args(argv)
    result = build(args.content)
    args.out.write_text(render(*result), encoding='utf-8')
    print(f'wrote {args.out} ({len(result[1])} collision nodes, {len(CLIPS)} clips)')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
